### ISSUE TITLE
Allow environment variable substitution in recyclarr.yml

### ISSUE THREAD

**Issue by skayo** [recyclarr/recyclarr#105]
It would be very convenient if you could use environment variables in `recyclarr.yml`.  
This would allow me to add my `recyclarr.yml` to my git repository, without exposing my API keys.

It could work similar to environment variable substitution in `docker-compose.yml`:
```yml
sonarr:
  - base_url: ${SONARR_BASE_URL:-http://localhost:8989}
    api_key: ${SONARR_API_KEY}
    quality_definition: hybrid
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
        tags: [tv]

radarr:
  - base_url: ${RADARR_BASE_URL:-http://localhost:7878}
    api_key: ${RADARR_API_KEY}
    quality_definition:
      type: movie
      preferred_ratio: 0.5
```
More info: https://docs.docker.com/compose/environment-variables/

I understand that this could require a lot of work, as I'm not sure such a library exists in DOTNET, so feel free to reject this.

**Comment by rcdailey** [comment]
I was thinking of a different idea. Eventually, I'm going to add named instances to YAML configuration. This would be a great opportunity to decouple the URL and API Key from the main configuration and in a different file. Sort of like `.env` files you might use for DB setup in Docker Compose:

`recyclarr.yml`:

```yml
radarr:
  instance1:
    custom_formats:
      - trash_ids: []
  instance2:
    custom_formats:
      - trash_ids: []
```

`services.yml`:

```yml
instance1:
  base_url: http://localhost:123
  api_key: 123abc

instance2:
  base_url: http://localhost:456
  api_key: 456def

**Comment by pikeas** [comment]
A services file will work but may be overkill. How about new settings called `api_key_env` and `api_key_file`, with usage like:

```
radarr:
  - base_url: http://localhost:7878
    api_key_env: SONARR_API_KEY
sonarr:
  - base_url: http://localhost:8989
    api_key_file: /run/secrets/sonarr
```

Alternately, Recyclarr could read and use `RECYCLARR_*` env vars as overrides.
