### ISSUE TITLE
Missing update regex on "Ignore scene releases" for Sonarr Optionals

### ISSUE THREAD

**Issue by fabricionaweb** [recyclarr/recyclarr#121]
This is about Sonarr

I have set to sync the **Optionals** `76e060895c5b8a765c310933da0a5357` but my **Ignore so called scene releases** `5bc23c3a055a1a5d8bbe4fb49d80e0cb` are outdated.

Just notice it have been updated a while https://github.com/TRaSH-/Guides/commit/e0f9d80d57ee7bd60ec2f574684b323c90095260
But Im not getting this update. Share it in Discord and it is happen to others as well.

How it should be:
- `/^(?!.*(web[ ]dl|-deflate|-inflate))(?=.*([_. ]WEB[_. ]|-CAKES\b|-GGEZ\b|-GGWP\b|-GLHF\b|-KOGI\b|-PECULATE\b|-GOSSIP\b)).*/i`

How it is:
- `/^(?!.*(web[ ]dl|-deflate|-inflate))(?=.*([_. ]WEB[_. ]|-CAKES\\b|-GGEZ\\b|-GGWP\\b|-GLHF\\b|-KOGI\\b)).*/i`

Went into the folder `repo` and git status is updated and right.
I have not notice yet another inconsistence

If it helps, follow my recyclarr.yml
```yaml
sonarr:
  - base_url: http://tower.lan:8989/
    api_key: redacted

    # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
    quality_definition: hybrid

    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
          - 76e060895c5b8a765c310933da0a5357 # Optionals
        filter:
          exclude:
            - 436f5a7d08fbf02ba25cb5e5dfe98e55 # Ignore Dolby Vision without HDR10 fallback.
            - cec8880b847dd5d31d29167ee0112b57 # Golden rule (1080 only x264)
            - 236a3626a07cacf5692c73cc947bc280 # Dislike release containing: 1-
            - ea83f4740cec4df8112f3d6dd7c82751 # Prefer Season Packs
        tags: [tv]
```
