### ISSUE TITLE
Release Profile/CF added across instances

### ISSUE THREAD

**Issue by TheSpoon98** [recyclarr/recyclarr#123]
Running a v3 instance of sonarr with release profiles and a v4 version with custom formats. It appears there is something.  The setup is being imported correctly I believe, however, it appears multiple versions of CFs are being imported into the v4 instance, not just the "final" version.  This was a fresh install/setup of the sonarr v4 docker.

![image](https://user-images.githubusercontent.com/14792646/189448282-22eff60d-d523-440e-84a7-5d563a0adf12.png)

**Comment by rcdailey** [comment]
I need more information than this:

- Relevant log file(s) (under `/config/logs`)
- I know you said "Fresh Install" but I need to be absolutely sure: Did you start the v4 instance with *no* previous data from v3?

**Comment by rcdailey** [comment]
I did a quick test on my end using this YAML:

```yml
sonarr:
  - base_url: http://localhost:8990
    api_key: 8d19e920ec7c40f288f7e9761513d458
    custom_formats:
      - trash_ids: [1b3994c551cbb92a2c781af061f4ab44] # Scene
        quality_profiles:
          - name: HD-1080p - incl scene
          - name: Ultra-HD - incl scene
            score: -25

  - base_url: http://localhost:8989
    api_key: ac13f73973cd401999f75b06d7a14441

    # Quality Definition Settings
    quality_definition: hybrid

    # Release Profile Settings
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
        tags: [tv]
      - trash_ids:
          - d428eda85af1df8904b4bbe4fc2f537c # Anime - First release profile
          - 6cd9e10bb5bb4c63d2d7cd3279924c7b # Anime - Second release profile
        strict_negative_scores: true
        tags: [anime]
      - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
        filter:
          exclude:
            - 436f5a7d08fbf02ba25cb5e5dfe98e55 # Ignore Dolby Vision without HDR10 fallback
            - f3f0f3691c6a1988d4a02963e69d11f2 # Ignore The Group -SCENE
        tags: [tv]
```

And I got this output:

```
E:/code/personal/recyclarr/src/Recyclarr/bin/Debug/net6.0/recyclarr.exe sonarr
[INF] Processing server http://hostname:8990

[INF] All custom formats are already up to date!
[INF] All quality profile scores are already up to date!
[INF] Processing server http://hostname:8989
[INF] Create new profile: [Trash] Low Quality Groups
[INF] Create new profile: [Trash] Release Sources (Streaming Service)
[INF] Create new profile: [Trash] P2P Groups + Repack/Proper
[INF] Create new profile: [Trash] Anime - First release profile
[INF] Create new profile: [Trash] Anime - Second release profile
[INF] Create new profile: [Trash] Optionals
[INF] Processing Quality Definition: hybrid
[INF] Notice: Hybrid only functions on 720/1080 qualities and uses non-anime values for the rest (e.g. 2160)
[INF] Number of updated qualities: 14
```

In Sonarr v3, release profiles got the `[Trash]` prefix. Custom formats do not apply a prefix. So this makes it clear to me that you are importing data from a previous v3 instance.
