### ISSUE TITLE
Support referencing environment variables in configuration

### ISSUE THREAD

**Issue by voltron4lyfe** [recyclarr/recyclarr#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Similar to Secrets support, there is a desire to include "Environment Variables" support to specify **values** within configuration files.  Proposed behavior is to match [Home Assistant's](https://www.home-assistant.io/docs/configuration/yaml/#including-values) implementation that also supports specification of a default value to be used if the environment variable is not defined. 

Sample config:

```yaml
radarr:
  api_key: !env_var ENV_API_KEY # No default specified. 
  url: !env_var RADARR_URL http://radarr:7878 # Default specified
  complicated: !env_var SOME_ENV "value with a space in it" # The default value has a space in it and must be quoted. 
```
The environment variables must be Scalars and will not be interpreted as additional yaml.
