### ISSUE TITLE
Git repo errors on latest docker image

### ISSUE THREAD

**Issue by 2fst4u** [recyclarr/recyclarr#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the latest docker image I get the following errors as shown in the log:
[trash_2022-12-07_11-41-00.log](https://github.com/recyclarr/recyclarr/files/10170887/trash_2022-12-07_11-41-00.log)

### Expected Behavior

Recyclarr runs as normal.

### Steps To Reproduce

1. Run recyclarr on latest docker after previously running on V2

### Environment

Ubuntu 22.04.1 docker (actually kubernetes)

### Recyclarr Version

3

### Sonarr/Radarr Version

Sonarr 3.0.9.1549 Radarr  4.3.0.6671

### Configuration YAML

```
# Configuration specific to Sonarr
sonarr:
  sonarr:
      # Set the URL/API Key to your actual instance
      base_url: http
      api_key: 
  
      # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
      quality_definition: series
  
      # Release profiles from the guide to sync to Sonarr.
      # You can optionally add tags and make negative scores strictly ignored
      release_profiles:
        - trash_ids:
            - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
            - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
            - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
          filter:
            include:
            - cec8880b847dd5d31d29167ee0112b57 # Golden rule
            - 436f5a7d08fbf02ba25cb5e5dfe98e55 # Ignore Dolby Vision without HDR10 fallback.
        #     - f3f0f3691c6a1988d4a02963e69d11f2 # Ignore The Group -SCENE
        #     - 5bc23c3a055a1a5d8bbe4fb49d80e0cb # Ignore so called scene releases
        #     - ea83f4740cec4df8112f3d6dd7c82751 # Prefer Season Packs
            - bc7a6383cbe88c3ee2d6396e1aacc0b3 # Prefer HDR
        #     - fa47da3377076d82d07c4e95b3f13d07 # Prefer Dolby Vision
           - 6f2aefa61342a63387f2a90489e90790 # Dislike retags: rartv, rarbg, eztv, TG
            - 19cd5ecc0a24bf493a75e80a51974cdd # Dislike retagged groups
        #     - 6a7b462c6caee4a991a9d8aa38ce2405 # Dislike release ending: en
        #     - 236a3626a07cacf5692c73cc947bc280 # Dislike release containing: 1-
  sonarr4k:
      base_url: 
      api_key: 
  
      # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
      quality_definition: series
  
      # Release profiles from the guide to sync to Sonarr.
      # You can optionally add tags and make negative scores strictly ignored
      release_profiles:
        - trash_ids:
            - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
            - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
            - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
          filter:
            include:
            - cec8880b847dd5d31d29167ee0112b57 # Golden rule
            - 436f5a7d08fbf02ba25cb5e5dfe98e55 # Ignore Dolby Vision without HDR10 fallback.
        #     - f3f0f3691c6a1988d4a02963e69d11f2 # Ignore The Group -SCENE
        #     - 5bc23c3a055a1a5d8bbe4fb49d80e0cb # Ignore so called scene releases
        #     - ea83f4740cec4df8112f3d6dd7c82751 # Prefer Season Packs
            - bc7a6383cbe88c3ee2d6396e1aacc0b3 # Prefer HDR
        #     - fa47da3377076d82d07c4e95b3f13d07 # Prefer Dolby Vision
            - 6f2aefa61342a63387f2a90489e90790 # Dislike retags: rartv, rarbg, eztv, TG
            - 19cd5ecc0a24bf493a75e80a51974cdd # Dislike retagged groups
        #     - 6a7b462c6caee4a991a9d8aa38ce2405 # Dislike release ending: en
        #     - 236a3626a07cacf5692c73cc947bc280 # Dislike release containing: 1-

# Configuration specific to Radarr.
radarr:
  radarr:
    # Set the URL/API Key to your actual instance
      base_url: 
      api_key: 
  
      # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    #  quality_definition:
    #   type: movie
    #   preferred_ratio: 0.5
  
      # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
      # the guide or your configuration. This will NEVER delete custom formats you manually created!
      delete_old_custom_formats: true
  
      custom_formats:
        # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
        # Do NOT use the heading names here, those do not work! These are case-insensitive.
        - trash_ids:
            - ed38b889b31be83fda192888e2286d83 # BR-DISK
            - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
            - 90a6f9a284dff5103f6346090e6280c8 # LQ
            - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
            - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
            - 1c7d7b04b15cc53ea61204bebbcc1ee2 # HQ
            - 403f3f6266b90439cacc1e07cae4dc2d # HQ-Remux
            - 26fa26253af4001701fedb56cec376dc # HQ-WEBDL
            - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
            - e7c2fcae07cbada050a0af3357491d7b # PCM
            - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
            - 185f1dd7264c4562b9022d963ac37424 # DD+
            - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
            - 1c1a4c5e823891c75bc50380a6866f73 # DTS
            - 240770601cc226190c367ef59aba7463 # AAC
            - c2998bd0d90ed5621d8df281e839436e # DD
            - 6ba9033150e7896bdc9ec4b44f2b230f # MP3
            - a061e2e700f81932daf888599f8a8273 # OPUS
            - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
            - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
            - e61e28db95d22bedcadf030b8f156d96 # HDR
            - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
            - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
            - 9364dd386c9b4a1100dde8264690add7 # HLG
            - 0f12c086e289cf966fa5948eac571f44 # Hybrid
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
            - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
            - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
            - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
            - eecf3a857724171f968a66cb5719e152 # IMAX
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced 
            - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
            - e23edd2482476e595fb990b12e7c609c # Dolby Vision HDR10
            - 58d6a88f13e2db7f5059c41047876f00 # Dolby Vision
            - 55d53828b9d81cbe20b02efd00aa0efd # Dolby Vision HLG
            - a3e19f8f627608af0211acd02bf89735 # Dolby Vision SDR
            - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
            - ae43b294509409a6a13919dedd4764c4 # Repack2
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
            - b124be9b146540f8e62f98fe32e49a2a # 1.0 Mono
            - 89dac1be53d5268a7e10a19d3c896826 # 2.0 Stereo
            - 205125755c411c3b8622ca3175d27b37 # 3.0 
            - 373b58bd188fc00c817bd8c7470ea285 # 4.0
            - 77ff61788dfe1097194fd8743d7b4524 # 5.1 Surround
            - 6fd7b090c3f7317502ab3b63cc7f51e3 # 6.1
            - e77382bcfeba57cb83744c9c5449b401 # 7.1 Surround
            - f2aacebe2c932337fe352fa6e42c1611 # 9.1
            - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
            - 40e9380490e748672c2522eaaeb692f7 # APTV
            - 84272245b2988854bfb76a16e60baea5 # DSNP
            - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
            - 526d445d4c16214309f0fd2b3be18a89 # Hulu
            - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
            - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
            - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
            - 2a6039655313bf5dab1e43523b62c374 # MA
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          quality_profiles:
            - name: HD-1080p
  
        - trash_ids: 
            - 957d0f44b592285f26449575e8b1167e # Special Edition
          quality_profiles:
            - name: HD-1080p
              score: 10000
  
        - trash_ids:
            - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
            - 3cafb66171b47f226146a0770576870f # TrueHD
            - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
            - 2f22d89048b01681dde8afe203bf2e95 # DTS X
            - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          quality_profiles:
            - name: HD-1080p
              score: -100000
  radarr4k:
      base_url: 
      api_key: 
  
      # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
      quality_definition:
        type: movie
        preferred_ratio: 0.5
  
      # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
      # the guide or your configuration. This will NEVER delete custom formats you manually created!
      delete_old_custom_formats: true
  
      custom_formats:
        - trash_ids:
            - ed38b889b31be83fda192888e2286d83 # BR-DISK
            - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
            - 90a6f9a284dff5103f6346090e6280c8 # LQ
            - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
            - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
            - 1c7d7b04b15cc53ea61204bebbcc1ee2 # HQ
            - 403f3f6266b90439cacc1e07cae4dc2d # HQ-Remux
            - 26fa26253af4001701fedb56cec376dc # HQ-WEBDL
            - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
            - e7c2fcae07cbada050a0af3357491d7b # PCM
            - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
            - 185f1dd7264c4562b9022d963ac37424 # DD+
            - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
            - 1c1a4c5e823891c75bc50380a6866f73 # DTS
            - 240770601cc226190c367ef59aba7463 # AAC
            - c2998bd0d90ed5621d8df281e839436e # DD
            - 6ba9033150e7896bdc9ec4b44f2b230f # MP3
            - a061e2e700f81932daf888599f8a8273 # OPUS
            - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
            - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
            - e61e28db95d22bedcadf030b8f156d96 # HDR
            - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
            - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ
            - 9364dd386c9b4a1100dde8264690add7 # HLG
            - 0f12c086e289cf966fa5948eac571f44 # Hybrid
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
            - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
            - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
            - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
            - eecf3a857724171f968a66cb5719e152 # IMAX
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced 
            - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
            - e23edd2482476e595fb990b12e7c609c # Dolby Vision HDR10
            - 58d6a88f13e2db7f5059c41047876f00 # Dolby Vision
            - 55d53828b9d81cbe20b02efd00aa0efd # Dolby Vision HLG
            - a3e19f8f627608af0211acd02bf89735 # Dolby Vision SDR
            - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
            - ae43b294509409a6a13919dedd4764c4 # Repack2
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
            - b124be9b146540f8e62f98fe32e49a2a # 1.0 Mono
            - 89dac1be53d5268a7e10a19d3c896826 # 2.0 Stereo
            - 205125755c411c3b8622ca3175d27b37 # 3.0 
            - 373b58bd188fc00c817bd8c7470ea285 # 4.0
            - 77ff61788dfe1097194fd8743d7b4524 # 5.1 Surround
            - 6fd7b090c3f7317502ab3b63cc7f51e3 # 6.1
            - e77382bcfeba57cb83744c9c5449b401 # 7.1 Surround
            - f2aacebe2c932337fe352fa6e42c1611 # 9.1
            - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
            - 40e9380490e748672c2522eaaeb692f7 # APTV
            - 84272245b2988854bfb76a16e60baea5 # DSNP
            - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
            - 526d445d4c16214309f0fd2b3be18a89 # Hulu
            - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
            - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
            - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
            - 2a6039655313bf5dab1e43523b62c374 # MA
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          quality_profiles:
            - name: Ultra-HD
  
        - trash_ids: 
            - 957d0f44b592285f26449575e8b1167e # Special Edition
          quality_profiles:
            - name: Ultra-HD
              score: 10000
  
        - trash_ids:
            - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
            - 3cafb66171b47f226146a0770576870f # TrueHD
            - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
            - 2f22d89048b01681dde8afe203bf2e95 # DTS X
            - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          quality_profiles:
            - name: Ultra-HD
              score: -100000
```

**Comment by 2fst4u** [comment]
I tried deleting the repo folder but it does the same thing.

**Comment by 2fst4u** [comment]
Sure if you feel it's relevant. It runs on nodes with version 1.24.6. It's run fine up until V3 so I'd be surprised if the kubernetes pod was at fault.

```
apiVersion: v1
kind: Namespace
metadata:
  name: recyclarr
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: recyclarr
  labels:
    app: recyclarr
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recyclarr
            image: ghcr.io/recyclarr/recyclarr:latest
            volumeMounts:
            - mountPath: /config
              name: recyclarr-config
            imagePullPolicy: Always
         #    args: ["sonarr"] #THIS LINE IS COMMENTED OUT BECAUSE I TRIED IT ON ITS OWN INSTEAD OF RUNNING SONARR AND RADARR CONSECUTIVELY 
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                recyclarr sonarr &&
                recyclarr radarr
            resources:
              limits:
                memory: 150Mi
              requests:
                cpu: 100m
                memory: 100Mi
            env:
            - name: TZ
              value: "Pacific/Auckland"
            - name: PUID 
              value: "972" 
            - name: PGID
              value: "972" 
          priorityClassName: recyclarr
          volumes:
          - name: recyclarr-config
            nfs:
              server: storage
              path: /mnt/Volume01/Shared/Kubernetes/recyclarr
          restartPolicy: OnFailure
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: recyclarr
value: 600000
globalDefault: false
description: "recyclarr"
```
