### ISSUE TITLE
Running with --preview deletes current release profiles

### ISSUE THREAD

**Issue by andreiz** [recyclarr/recyclarr#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ran without `--preview` once to create profiles. Ran with `--preview`, which displayed the profile info and also deleted the existing profiles.

### Expected Behavior

According to the docs, `--preview` should not modify any information on the system at all.

### Steps To Reproduce

Config:

See below.

Run:

```
docker-compose run --rm recyclarr sonarr
```

Result:
```
[INF] Processing Sonarr server series
[INF] Create new profile: [Trash] Low Quality Groups
[INF] Create new profile: [Trash] Release Sources (Streaming Service)
[INF] Create new profile: [Trash] P2P Groups + Repack/Proper
[INF] Create new profile: [Trash] Optionals
```

Check Sonarr instance, the profiles are there.

Then run:
```
docker-compose run --rm recyclarr sonarr --preview
```

Result:

```
[... profile definition omitted...]
[INF] Deleting old Trash release profile: [Trash] Low Quality Groups
[INF] Deleting old Trash release profile: [Trash] Release Sources (Streaming Service)
[INF] Deleting old Trash release profile: [Trash] P2P Groups + Repack/Proper
[INF] Deleting old Trash release profile: [Trash] Optionals
```

Check Sonarr instance, the profiles are gone.

### Environment & Versions

```bash
- Operating System: Ubuntu 20.04
- Architecture: Linux
- Recyclarr Version: v4.0.1
- Recyclarr Build: 
- Sonarr Version: 3.0.9.1549
```

### Recyclarr Log File(s)

[trash_2022-12-25_09-37-13.log](https://github.com/recyclarr/recyclarr/files/10300439/trash_2022-12-25_09-37-13.log)
[trash_2022-12-25_09-37-04.log](https://github.com/recyclarr/recyclarr/files/10300441/trash_2022-12-25_09-37-04.log)

### Configuration YAML

```YAML
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: REDACTED
    api_key: REDACTED

    release_profiles:
      # Series
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
        tags: [tv]

      - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
        filter:
          exclude:
            - cec8880b847dd5d31d29167ee0112b57 # Golden rule
        tags: [tv]
```
