### ISSUE TITLE
Whatbox uses different Sonarr/Radarr version numbers

### ISSUE THREAD

**Issue by needo37** [recyclarr/recyclarr#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whatbox uses a custom version of Sonarr/Radarr. So when recylarr tries to do the version detection it does not recognize the version of Sonarr/Radarr.

Sonarr: whatbox-e4c0e80
Radarr: whatbox-9b3770a

### Expected Behavior

The profiles and quality profiles sync correctly.

### Steps To Reproduce

1. Run recyclarr against the Whatbox sonarr/radarr.

### Environment & Versions

```bash
See above
```

### Recyclarr Log File(s)

[13:40:36 DBG] HTTP Request: GET http://REDACTED:19025/api/v3/system/status?apikey=REDACTED
[13:40:36 DBG] HTTP Response: 200 GET http://REDACTED:19025/api/v3/system/status?apikey=REDACTED
[13:40:36 DBG] HTTP Body: {"appName":"Sonarr","instanceName":"Sonarr","version":"10.0.0.35503","buildTime":"2022-12-25T19:43:34.2377865Z","isDebug":false,"isProduction":true,"isAdmin":false,"isUserInteractive":false,"startupPath":"/usr/share/sonarr","appData":"/home/orbitron/.config/Sonarr","osName":"gentoo","osVersion":"2.9","isMonoRuntime":true,"isMono":true,"isLinux":true,"isOsx":false,"isWindows":false,"mode":"console","branch":"master","authentication":"forms","sqliteVersion":"3.40.1","urlBase":"","runtimeVersion":"6.12.0.122","runtimeName":"mono","startTime":"2023-01-18T18:42:22.183511Z","packageUpdateMechanism":"builtIn"}
[13:40:36 DBG] Sonarr Version: 10.0.0.35503
[13:40:36 ERR] Exception
Recyclarr.TrashLib.ExceptionTypes.ServiceIncompatibilityException: Release profiles require Sonarr v3. Please use `custom_formats` instead or use the right version of Sonarr.
   at Recyclarr.TrashLib.Services.Sonarr.Capabilities.SonarrCapabilityEnforcer.Check(SonarrConfiguration config) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.TrashLib/Services/Sonarr/Capabilities/SonarrCapabilityEnforcer.cs:line 34

### Configuration YAML

```YAML
# Configuration specific to Sonarr
sonarr:
    # Set the URL/API Key to your actual instance
  - base_url: http://localhost:19025
    api_key: REDACTED

    # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
    quality_definition: series

    # Release profiles from the guide to sync to Sonarr.
    # You can optionally add tags and make negative scores strictly ignored
    release_profiles:
      # Series
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
```
