### ISSUE TITLE
Ability to exclude CFs from reset_unmatched_scores

### ISSUE THREAD

**Issue by rcdailey** [recyclarr/recyclarr#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Users that manually import and manage the scores for custom CFs are not able to use `reset_unmatched_scores`. There should be a way to ignore certain CFs by name (or, ideally, pattern) so that those manual scores are not interfered with.

An example of what the YAML would be for this is below.

```yml
quality_profiles:
  - name: 1080p
    reset_unmatched_scores:
      exclude_patterns:
        - language # Name of the CF (regex) that you want to leave alone

custom_formats:
  - trash_ids:
      - abc123
      - xyz456
    quality_profiles:
      - name: 1080p
```
