### ISSUE TITLE
Unable to sync to Radarr (HTTP error: Response could not be deserialized to JSON)

### ISSUE THREAD

**Issue by tuxpeople** [recyclarr/recyclarr#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```

===========================================
Processing Radarr Server: [movies]
===========================================

[ERR] HTTP error: Response could not be deserialized to JSON: GET http://REDACTED:7878/api/v3/customformat?apikey=REDACTED
```

However, I can successfully do this:
```
curl http://REDACTED:7878/api/v3/customformat?apikey=REDACTED | jq > curl-result.txt
```

This is the result, which should be correct json: 
[curl-result.txt](https://github.com/recyclarr/recyclarr/files/11182905/curl-result.txt)

### Expected Behavior

Successfully syncing custom formats to Radarr

### Steps To Reproduce

Going into container:  `docker exec -it recyclarr bash`
Run script: `/cron.sh`

Sonarr (top of the config file) works perfectly, Radarr doesn't.

### Environment & Versions

```bash
- Operating System: `Docker`
- Architecture: `x86`
- Recyclarr Version: `4.4.0`
- Recyclarr Build: `4.4.0+Branch.tags-v4.4.0.Sha.503cb7500a81076ff0c1e9279152ebf23418fd62`
- Sonarr Version: `not applicable`
- Radarr Version: `4.3.2.6857-ls166 by linuxserver.io`
```

### Recyclarr Log File(s)

[recyclarr_2023-04-08_11-28-36.debug.log](https://github.com/recyclarr/recyclarr/files/11182903/recyclarr_2023-04-08_11-28-36.debug.log)
[recyclarr_2023-04-08_11-28-36.verbose.log](https://github.com/recyclarr/recyclarr/files/11182904/recyclarr_2023-04-08_11-28-36.verbose.log)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/reference/config-reference

# Configuration specific to Sonarr
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://REDACTED:8989
    api_key: REDACTED

    delete_old_custom_formats: true

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    # Release profiles from the guide to sync to Sonarr v3 (Sonarr v4 does not use this!)
    # Use `recyclarr list release-profiles` for values you can put here.
    # https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/
    custom_formats:
      - trash_ids:
          # Audio Advanced #2
          - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
          - dbe00161b08a25ac6154c55f95e6318d # DD
          - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
          - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
          - 3e8b714263b26f486972ee1e0fe7606c # MP3
          - 28f6ef16d61e2d1adfce3156ed8257e3 # Opus
          - 30f70576671ca933adbdcfc736a69718 # PCM
          # HQ Source Groups
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          # Misc
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - cddfb4e32db826151d97352b8e37c648 # x264
          - c9eafd50846d299b862ca9bb6ea91950 # x265
          # Optional
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          #- 3bc5f395426614e155e585a2f056cdf1 # Season Pack
          # Series Versions
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
          # Streaming Services
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - f27d46a831e6b16fa3fee2c4e5d10984 # CANAL+
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - d34870697c9db575f17700212167be23 # NF
          - b2b980877494b560443631eb1f473867 # NLZ
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
          - c30d2958827d1867c73318a5a2957eb1 # RED
          - b0d6195c23ae254932da00512db7e8a8 # RTBF
          - 0455d6519a550dbf648c97b56e7231d2 # SALTO
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 5d2317d99af813b6529c7ebf01c83533 # VDL
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        quality_profiles:
          - name: _all_to_1080p_ger
          - name: _all_to_720p_ger
          - name: _all_to_1080p_eng
          - name: _all_to_720p_eng
          - name: _all_to_1080p_eng-ger
          - name: _all_to_720p_eng-ger
      - trash_ids:
          # Audio Channels
          - bd6dd5e043aa27ff4696a08d011c7d96 # 1.0 Mono
        quality_profiles:
          - name: _all_to_1080p_ger
            score: -500
          - name: _all_to_720p_ger
            score: -500
          - name: _all_to_1080p_eng
            score: -500
          - name: _all_to_720p_eng
            score: -500
          - name: _all_to_1080p_eng-ger
            score: -500
          - name: _all_to_720p_eng-ger
            score: -500

      # Anime (Uncomment below if you want it)
      #- trash_ids:
      #    - d428eda85af1df8904b4bbe4fc2f537c # Anime - First release profile
      #    - 6cd9e10bb5bb4c63d2d7cd3279924c7b # Anime - Second release profile

# Configuration specific to Radarr.
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: http://REDACTED:7878
    api_key: REDACTED

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          # Audio Advanced #2
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - 6ba9033150e7896bdc9ec4b44f2b230f # MP3
          - a061e2e700f81932daf888599f8a8273 # Opus
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          # HQ Release Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
          - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
          - a58f517a70193f8e578056642178419d # UHD Bluray Tier 02
          - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
          # Misc
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          # Movie Versions
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - 09d9dd29a0fc958f9796e65c2a8864b4 # Open Matte
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
          # Optional
          - cae4ca30163749b891686f95532519bd # AV1
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          # Unwanted
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
        quality_profiles:
          - name: _sdtv_to_1080p_eng
          - name: _sdtv_to_1080p_ger
      - trash_ids:
          # Audio Channels
          - b124be9b146540f8e62f98fe32e49a2a # 1.0 Mono
        quality_profiles:
          - name: _sdtv_to_1080p_eng
            score: -500
          - name: _sdtv_to_1080p_ger
            score: -500
      - trash_ids:
          # x265
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          - 9170d55c319f4fe40da8711ba9d8050d # x265
        quality_profiles:
          - name: _sdtv_to_1080p_eng
            score: +50
          - name: _sdtv_to_1080p_ger
            score: +50
      # - trash_ids:
      #     # x264
      #     - 2899d84dc9372de3408e6d8cc18e9666 # x264
      #   quality_profiles:
      #     - name: _sdtv_to_1080p_eng
      #       score: -100
      #     - name: _sdtv_to_1080p_ger
      #       score: -100

      # Uncomment the below properties to specify one or more quality profiles that should be
      # updated with scores from the guide for each custom format. Without this, custom formats
      # are synced to Radarr but no scores are set in any quality profiles.
      #quality_profiles:
      #  - name: Quality Profile 1
      #  - name: Quality Profile 2
      #    #score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
      #    #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```
