### ISSUE TITLE
api_key env_var substitution doesn't work with quotes

### ISSUE THREAD

**Issue by szinn** [recyclarr/recyclarr#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if the config.yaml has

api_key: !env_var SONARR_APIKEY

it works. However, yaml schema verification fails because the ! is part of yaml tagging.

Using

api_key: "!env_var SONARR_APIKEY"

should work, but recycler fails with an unauthorized call, so it appears the " block the env substitution even though the yaml is valid.

### Expected Behavior

api_key: "!env_var SONARR_APIKEY"

should work and substitute the variable as expected.

### Steps To Reproduce

Use api_key: "!env_var SONARR_APIKEY" to reproduce

### Environment & Versions

```bash
- Operating System: Kubernetes
- Architecture: AMD
- Recyclarr Version: 4.4.1
- Recyclarr Build:
- Sonarr Version: 3.0.10.1567
- Radarr Version:
```

### Recyclarr Log File(s)

===========================================
Processing Sonarr Server: [standard]
===========================================

[INF] Processing Quality Definition: series
[ERR] HTTP error: Call failed with status code 401 (Unauthorized): GET http://REDACTED:8989/api/v3/qualitydefinition?apikey=REDACTED
time="2023-04-19T00:00:02Z" level=error msg="error running command: exit status 1" iteration=0 job.command=/cron.sh job.position=0 job.schedule=@daily

### Configuration YAML

```YAML
sonarr:
  standard:
    base_url: http://sonarr:8989
    api_key: "!env_var SONARR_APIKEY"
    delete_old_custom_formats: true
    quality_definition:
      type: series
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
      - trash_ids:
          - 76e060895c5b8a765c310933da0a5357 # Optionals
        filter:
          include:
            - 436f5a7d08fbf02ba25cb5e5dfe98e55 # Ignore Dolby Vision without HDR10 fallback
            - f3f0f3691c6a1988d4a02963e69d11f2 # Ignore The Group -SCENE
```
