### ISSUE TITLE
CF scores are not updating in sonvarrv4

### ISSUE THREAD

**Issue by dephcon** [recyclarr/recyclarr#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So initially I setup a profile for WEB-1080p and WEB-2160p following trash guides' recommendation.  When I processed the config all the custom formats (CF) were applied to the quality profiles (QP) but there were no scores applied.  I upgraded my recycler container to :edge and then it worked.

Now when i tried to create a new QP for WEB-720, I have the same problem where all the CF scores are zero and it refuses to set them, the debug just says there's nothing to do.

I got around this by just cloning my WEB-1080p CF and changing to for 720p but obviously there's a problem.

I've even attempted to force a score changed by setting one of the QPs to -10000 but the debug says there's nothing to change.

### Expected Behavior

QPs with non-zero scores should be changed from the default of zero for each applied QP on each sync

### Steps To Reproduce

create a new QP and apply CFs to it with non-zero scores, then sync

OR

force a manual score change to an existing QP and then sync

### Environment & Versions

```bash
- Operating System: unraid
- Architecture: docker
- Recyclarr Version: 5.0.0+163
- Recyclarr Build: docker:edge
- Sonarr Version: 4.0.0.470
```

### Recyclarr Log File(s)

Logs taken from when attempting to set a -10000 score for "WEB Tier 03" from the TG's default of 1600

[recyclarr_2023-04-30_14-34-43.verbose.log](https://github.com/recyclarr/recyclarr/files/11362055/recyclarr_2023-04-30_14-34-43.verbose.log)
[recyclarr_2023-04-30_14-34-43.debug.log](https://github.com/recyclarr/recyclarr/files/11362056/recyclarr_2023-04-30_14-34-43.debug.log)

### Configuration YAML

```YAML
sonarr:
  sonarr_v4:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey
    quality_profiles:
      - name: WEB-720p
        reset_unmatched_scores: true
      - name: WEB-1080p
        reset_unmatched_scores: true

    # WEB-720p/1080p
    custom_formats:
      - trash_ids:
        # Unwanted
        - 85c61753df5da1fb2aab6f2a47426b09  # BR-DISK
        - 9c11cd3f07101cdba90a2d81cf0e56b4  # LQ
        - 47435ece6b99a0b477caf360e79ba0bb  # x265 (HD)
        # Misc
        - ec8fa7296b64e8cd390a1600981f3923  # Repack/Proper
        - eb3d5cc0a2be0db205fb823640db6a3c  # Repack v2
        - 44e7c4de10ae50265753082e5dc76047  # Repack v3
        # Streaming Services
        - d660701077794679fd59e8bdf4ce3a29  # AMZN
        - f67c9ca88f463a48346062e8ad07713f  # ATVP
        - 36b72f59f4ea20aad9316f475f2d9fbb  # DCU
        - 89358767a60cc28783cdc3d0be9388a4  # DSNP
        - 7a235133c87f7da4c8cccceca7e3c7a6  # HBO
        - a880d6abc21e7c16884f3ae393f84179  # HMAX
        - f6cce30f1733d5c8194222a7507909bb  # HULU
        - 0ac24a2a68a9700bcb7eeca8e5cd644c  # iT
        - d34870697c9db575f17700212167be23  # NF
        - b2b980877494b560443631eb1f473867  # NLZ
        - 1656adc6d7bb2c8cca6acfb6592db421  # PCOK
        - c67a75ae4a1715f2bb4d492755ba4195  # PMTP
        - 3ac5d84fce98bab1b531393e9c82f467  # QIBI
        - c30d2958827d1867c73318a5a2957eb1  # RED
        - ae58039e1319178e6be73caab5c42166  # SHO
        - 1efe8da11bfd74fbbcd4d8117ddb9213  # STAN
        - 5d2317d99af813b6529c7ebf01c83533  # VDL
        - 77a7b25585c18af08f60b1547bb9b4fb  # CC
        # HQ Source Groups
        - e6258996055b9fbab7e9cb2f75819294  # WEB Tier 01
        - 58790d4e2fdcd9733aa7ae68ba2bb503  # WEB Tier 02
        #- d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 03
        - d0c516558625b04b363fa6c5c2c7cfd4  # WEB Scene
        quality_profiles:
          - name: WEB-720p
          - name: WEB-1080p
      - trash_ids:
          # TEST
          - d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 03
        quality_profiles:
          - name: WEB-720p
            score: -10000
          - name: WEB-1080p
            score: -10000
```

### Sonarr / Radarr Logs

around the sync job, nothing useful in sonarr logs:

2023-04-30 14:29:11.6|Info|ImportListSyncService|Starting Import List Sync
2023-04-30 14:29:11.6|Info|ImportListSyncService|Processing 0 list items
2023-04-30 14:29:11.8|Info|ImportListSyncService|Import List Sync Completed. Items found: 0, Series added: 0
2023-04-30 14:29:41.7|Info|RssSyncService|Starting RSS Sync
2023-04-30 14:29:42.6|Info|DownloadDecisionMaker|Processing 381 releases
2023-04-30 14:29:43.4|Info|RssSyncService|RSS Sync Completed. Reports found: 381, Reports grabbed: 0
2023-04-30 14:34:41.7|Info|ImportListSyncService|Starting Import List Sync
2023-04-30 14:34:41.7|Info|ImportListSyncService|Processing 0 list items
2023-04-30 14:34:41.8|Info|ImportListSyncService|Import List Sync Completed. Items found: 0, Series added: 0
2023-04-30 14:40:11.7|Info|ImportListSyncService|Starting Import List Sync
2023-04-30 14:40:11.7|Info|ImportListSyncService|Processing 0 list items
2023-04-30 14:40:11.9|Info|ImportListSyncService|Import List Sync Completed. Items found: 0, Series added: 0
