### ISSUE TITLE
Default Scores for Anime WEB IDs are Incorrect

### ISSUE THREAD

**Issue by MetalNeo** [recyclarr/recyclarr#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Trash IDs below have incorrect default scores when used for an anime profile. The defaults are coming up as 1700, 1650, and 1600 from the Series profile.

[Source](https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles-anime/#default-scoring) 

`e6258996055b9fbab7e9cb2f75819294`, `58790d4e2fdcd9733aa7ae68ba2bb503`, and `d84935abd3f8556dcd51d4f27e22d0a6`.

### Expected Behavior

Scores should default to 450, 400, and 350 when used in an Anime profile.

### Steps To Reproduce

1. Add Sonarr Anime Profile/Qualities to `recyclarr.yaml`.
2. Sync profile.
3. Note incorrect scores.

### Environment & Versions

```bash
- Operating System: Debian Bullseye
- Architecture: amd64
- Recyclarr Version: 4.4.1
- Recyclarr Build: Docker
- Sonarr Version: 4.0.0.500
- Radarr Version: NA
```

### Recyclarr Log File(s)

[07:04:52 DBG]   - WEB Tier 03: 0 -> 1600 (Updated)
[07:04:52 DBG]   - Anime Web Tier 03 (Official Subs): 0 -> 400 (Updated)
[07:04:52 DBG]   - WEB Tier 02: 0 -> 1650 (Updated)
[07:04:52 DBG]   - WEB Tier 01: 0 -> 1700 (Updated)

### Configuration YAML

```YAML
custom_formats:
      - trash_ids:
          - 949c16fe0a8147f50ba82cc2df9411c9
          - ed7f1e315e000aef424a58517fa48727
          - 096e406c92baa713da4a72d88030b815
          - 30feba9da3030c5ed1e0f7d610bcadc4
          - 545a76b14ddc349b8b185a6344e28b04
          - 25d2afecab632b1582eaf03b63055f72
          - 0329044e3d9137b08502a9f84a7e58db
          - c81bbfb47fed3d5a3ad027d077f889de
          - e0014372773c8f0e1bef8824f00c7dc4
          - 19180499de5ef2b84b6ec59aae444696
          - e6258996055b9fbab7e9cb2f75819294
          - 58790d4e2fdcd9733aa7ae68ba2bb503
          - c27f2ae6a4e82373b0f1da094e2489ad
          - d84935abd3f8556dcd51d4f27e22d0a6
          - 4fd5528a3a8024e6b49f9c67053ea5f3
          - 29c2a13d091144f63307e4a8ce963a39
          - dc262f88d74c651b12e9d90b39f6c753
```

### Sonarr / Radarr Logs

N/A

**Comment by rcdailey** [comment]
Need Sonarr and Recyclarr logs attached.

**Comment by MetalNeo** [comment]
Here are the full logs.

[recyclarr_2023-05-17_07-04-49.verbose.log](https://github.com/recyclarr/recyclarr/files/11501818/recyclarr_2023-05-17_07-04-49.verbose.log)
[sonarr.txt](https://github.com/recyclarr/recyclarr/files/11501820/sonarr.txt)

**Comment by rcdailey** [comment]
Thank you for those! I'd also like the corresponding `recyclarr_2023-05-17_07-04-49.debug.log` attached as well. Much appreciated! Once I have that, I'll have everything I need to start debugging this issue.

**Comment by MetalNeo** [comment]
Here is the last one.

[recyclarr_2023-05-17_07-04-49.debug.log](https://github.com/recyclarr/recyclarr/files/11511608/recyclarr_2023-05-17_07-04-49.debug.log)

**Comment by le0m** [comment]
Just adding some information.

JSON structure for custom formats has a `trash_scores` property beside `trash_score`, for example [e6258996055b9fbab7e9cb2f75819294](https://trash-guides.info/Sonarr/sonarr-collection-of-custom-formats/#web-tier-01):
```json
  "trash_score": 1700,
  "trash_scores": {
    "default": 1700,
    "anime-sonarr": 350
  }
```
The [anime guide](https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles-anime/#default-scoring) mentions that some scores are different than those in the main guide.

What I'm saying is that the data is there, but there needs to be a way to tell recyclarr which one to use (and implement the logic to read from `trash_scores` of course).

This is not very urgent because it's possible to override the score by defining the quality profile for these trash IDs separately for animes, but it would be a nice-to-have feature 🙂

**Comment by rcdailey** [comment]
@le0m There's already a way for you to specify which score set you want to use. See the YAML configuration reference.

**Comment by le0m** [comment]
Oh I found it, thanks! I missed the setting for "quality profiles", was looking in the "custom formats" section, sorry

**Comment by KaXaSA** [comment]
For anyone else wondering, if you have something like this:

```
{
  "trash_id": "e6258996055b9fbab7e9cb2f75819294",
  "trash_scores": {
    "default": 1700,
    "anime-sonarr": 350
  },
```
Notice that there are 2 **trash_scores**, if you don't want to use the default, you can define the **score_set** you want to use in your recyclarr.yml file, example:
```
sonarr:
  anime-sonarr-v4:
    # Set the URL/API Key to your actual instance
    # Secret https://recyclarr.dev/wiki/yaml/secrets-reference/
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey

    replace_existing_custom_formats: true

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: anime

    quality_profiles:
      # name of the quality profile you want to update
      - name: 1080p - Anime
        score_set: anime-sonarr

    custom_formats:
      - trash_ids:
      # Trash id list here
        quality_profiles:
          - name: 1080p - Anime
```

Keep in mind that you have to add the score_set under that first quality_profiles that is directly under the instance id (in my case: anime-sonarr-v4), if you try to add that somewhere else, like custom_formats > quality_profiles you will get an error like "Property 'score_set' not found on type..."

Just posting this because I got here looking for how to use that trash_scores with recyclarr (after I read the [quality-profiles documentation](https://recyclarr.dev/wiki/yaml/config-reference/quality-profiles/)) and I was still using it in the wrong place.
