### ISSUE TITLE
Invalid quality profile name is shown when import configs from trash guides

### ISSUE THREAD

**Issue by huhfoo** [recyclarr/recyclarr#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to import recyclarr configs from trash 
https://github.com/TRaSH-/Guides/blob/master/docs/recyclarr-configs/sonarr/web-1080p-v4.yml
https://github.com/TRaSH-/Guides/blob/master/docs/recyclarr-configs/sonarr/web-2160p-v4.yml

Formats are imported successfully, but at the end there is a WARN level messaage, depending on the format
```
[WRN] The following quality profile names are not valid and should either be removed or renamed in your YAML config
[WRN] ["WEB-1080p"]
```

or 
```
[WRN] The following quality profile names are not valid and should either be removed or renamed in your YAML config
[WRN] ["WEB-2160p"]
```

### Expected Behavior

Warn message should not be shown

### Steps To Reproduce

1. run sonarr and recyclarr in docker 
2. get the api key
3. paste api key to config files
5. execute to recyclarr container and run ./cron.sh

docker compose:
```
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - $HOME/appdata/sonarr:/config
      - $HOME/media/tvseries:/tv
      - $HOME/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:4.4.1
    container_name: recyclarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - $HOME/appdata/recyclarr:/config
      - $HOME/config/recyclarr:/config/configs
    restart: unless-stopped
```
### Environment & Versions

```bash
- Operating System:
- Architecture:
- Recyclarr Version: edge, 4.4.1
- Recyclarr Build: linux/amd64
- Sonarr Version: 4.0.0.535
- Radarr Version: didn't test with radarr
```

### Recyclarr Log File(s)

/ $ ./cron.sh

-------------------------------------------------------------
 Executing Tasks: Sun Jun  4 19:49:11 EEST 2023
-------------------------------------------------------------

===========================================
Processing Sonarr Server: [sonarr]
===========================================

[INF] Created 28 New Custom Formats
> Created: 85c61753df5da1fb2aab6f2a47426b09 (BR-DISK)
> Created: 9c11cd3f07101cdba90a2d81cf0e56b4 (LQ)
> Created: 47435ece6b99a0b477caf360e79ba0bb (x265 (HD))
> Created: ec8fa7296b64e8cd390a1600981f3923 (Repack/Proper)
> Created: eb3d5cc0a2be0db205fb823640db6a3c (Repack v2)
> Created: 44e7c4de10ae50265753082e5dc76047 (Repack v3)
> Created: d660701077794679fd59e8bdf4ce3a29 (AMZN)
> Created: f67c9ca88f463a48346062e8ad07713f (ATVP)
> Created: 36b72f59f4ea20aad9316f475f2d9fbb (DCU)
> Created: 89358767a60cc28783cdc3d0be9388a4 (DSNP)
> Created: 7a235133c87f7da4c8cccceca7e3c7a6 (HBO)
> Created: a880d6abc21e7c16884f3ae393f84179 (HMAX)
> Created: f6cce30f1733d5c8194222a7507909bb (HULU)
> Created: 0ac24a2a68a9700bcb7eeca8e5cd644c (iT)
> Created: d34870697c9db575f17700212167be23 (NF)
> Created: b2b980877494b560443631eb1f473867 (NLZ)
> Created: 1656adc6d7bb2c8cca6acfb6592db421 (PCOK)
> Created: c67a75ae4a1715f2bb4d492755ba4195 (PMTP)
> Created: 3ac5d84fce98bab1b531393e9c82f467 (QIBI)
> Created: c30d2958827d1867c73318a5a2957eb1 (RED)
> Created: ae58039e1319178e6be73caab5c42166 (SHO)
> Created: 1efe8da11bfd74fbbcd4d8117ddb9213 (STAN)
> Created: 5d2317d99af813b6529c7ebf01c83533 (VDL)
> Created: 77a7b25585c18af08f60b1547bb9b4fb (CC)
> Created: e6258996055b9fbab7e9cb2f75819294 (WEB Tier 01)
> Created: 58790d4e2fdcd9733aa7ae68ba2bb503 (WEB Tier 02)
> Created: d84935abd3f8556dcd51d4f27e22d0a6 (WEB Tier 03)
> Created: d0c516558625b04b363fa6c5c2c7cfd4 (WEB Scene)
[INF] Total of 28 custom formats were synced
[INF] All quality profile scores are already up to date!
[WRN] The following quality profile names are not valid and should either be removed or renamed in your YAML config
[WRN] ["WEB-1080p"]
[INF] Processing Quality Definition: series
[INF] Number of updated qualities: 14

===========================================
Processing Sonarr Server: [sonarr]
===========================================

[INF] Created 12 New Custom Formats
> Created: 7878c33f1963fefb3d6c8657d46c2f0a (DV HDR10)
> Created: 1f733af03141f068a540eec352589a89 (DV HLG)
> Created: 27954b0a80aab882522a88a4d9eae1cd (DV SDR)
> Created: 6d0d8de7b57e35518ac0308b0ddf404e (DV)
> Created: bb019e1cd00f304f80971c965de064dc (HDR (undefined))
> Created: 3e2c4e748b64a1a1118e0ea3f4cf6875 (HDR)
> Created: 3497799d29a085e2ac2df9d468413c94 (HDR10)
> Created: a3d82cbef5039f8d295478d28a887159 (HDR10+)
> Created: 17e889ce13117940092308f48b48b45b (HLG)
> Created: 2a7e3be05d3861d6df7171ec74cad727 (PQ)
> Created: 9b27ab6498ec0f31a3353992e19434ca (DV (WEBDL))
> Created: 2016d1676f5ee13a5b7257ff86ac9a93 (SDR)
[INF] Skipped 27 Custom Formats that did not change
[INF] Deleted 1 Custom Formats
> Deleted: 47435ece6b99a0b477caf360e79ba0bb (x265 (HD))
[INF] Total of 13 custom formats were synced
[INF] All quality profile scores are already up to date!
[WRN] The following quality profile names are not valid and should either be removed or renamed in your YAML config
[WRN] ["WEB-2160p"]
[INF] Processing Quality Definition: series
[INF] Number of updated qualities: 14

### Configuration YAML

```YAML
# This config file is for use with Sonarr V4 only
sonarr:
  sonarr:  # A custom name used to identify this particular instance.
    base_url: http://sonarr:8989
    api_key: $API_KEY

    quality_definition:
      type: series

    quality_profiles:
      - name: WEB-1080p
        reset_unmatched_scores: true

    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09  # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4  # LQ
          - 47435ece6b99a0b477caf360e79ba0bb  # x265 (HD)
          # Misc
          - ec8fa7296b64e8cd390a1600981f3923  # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c  # Repack v2
          - 44e7c4de10ae50265753082e5dc76047  # Repack v3
          # Streaming Services
          - d660701077794679fd59e8bdf4ce3a29  # AMZN
          - f67c9ca88f463a48346062e8ad07713f  # ATVP
          - 36b72f59f4ea20aad9316f475f2d9fbb  # DCU
          - 89358767a60cc28783cdc3d0be9388a4  # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6  # HBO
          - a880d6abc21e7c16884f3ae393f84179  # HMAX
          - f6cce30f1733d5c8194222a7507909bb  # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c  # iT
          - d34870697c9db575f17700212167be23  # NF
          - b2b980877494b560443631eb1f473867  # NLZ
          - 1656adc6d7bb2c8cca6acfb6592db421  # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195  # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467  # QIBI
          - c30d2958827d1867c73318a5a2957eb1  # RED
          - ae58039e1319178e6be73caab5c42166  # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213  # STAN
          - 5d2317d99af813b6529c7ebf01c83533  # VDL
          - 77a7b25585c18af08f60b1547bb9b4fb  # CC
          # HQ Source Groups
          - e6258996055b9fbab7e9cb2f75819294  # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503  # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4  # WEB Scene
        quality_profiles:
          - name: WEB-1080p
---
# This config file is for use with Sonarr V4 only
sonarr:
  sonarr:  # A custom name used to identify this particular instance.
    base_url: http://sonarr:8989
    api_key: $API_KEY

    quality_definition:
      type: series

    quality_profiles:
      - name: WEB-2160p
        reset_unmatched_scores: true

    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # HDR Formats
          - 7878c33f1963fefb3d6c8657d46c2f0a  # DV HDR10
          - 1f733af03141f068a540eec352589a89  # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd  # DV SDR
          - 6d0d8de7b57e35518ac0308b0ddf404e  # DV
          - bb019e1cd00f304f80971c965de064dc  # HDR (undefined)
          - 3e2c4e748b64a1a1118e0ea3f4cf6875  # HDR
          - 3497799d29a085e2ac2df9d468413c94  # HDR10
          - a3d82cbef5039f8d295478d28a887159  # HDR10+
          - 17e889ce13117940092308f48b48b45b  # HLG
          - 2a7e3be05d3861d6df7171ec74cad727  # PQ
          # DV (WEBDL) - The next line is uncommented by default, and ensures that releases with Dolby Vision will only be grabbed if they have HDR10 fallback. You can comment the line out if you do not need HDR10 fallback
          - 9b27ab6498ec0f31a3353992e19434ca  # DV (WEBDL)
          # HDR10Plus Boost - Uncomment the next line if any of your devices DO support HDR10+
          # - 0dad0a507451acddd754fe6dc3a7f5e7  # HDR10Plus Boost
          # Unwanted UHD
          - 85c61753df5da1fb2aab6f2a47426b09  # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4  # LQ
          - 2016d1676f5ee13a5b7257ff86ac9a93  # SDR
          # Misc
          - ec8fa7296b64e8cd390a1600981f3923  # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c  # Repack v2
          - 44e7c4de10ae50265753082e5dc76047  # Repack v3
          # Streaming Services
          - d660701077794679fd59e8bdf4ce3a29  # AMZN
          - f67c9ca88f463a48346062e8ad07713f  # ATVP
          - 36b72f59f4ea20aad9316f475f2d9fbb  # DCU
          - 89358767a60cc28783cdc3d0be9388a4  # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6  # HBO
          - a880d6abc21e7c16884f3ae393f84179  # HMAX
          - f6cce30f1733d5c8194222a7507909bb  # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c  # iT
          - d34870697c9db575f17700212167be23  # NF
          - b2b980877494b560443631eb1f473867  # NLZ
          - 1656adc6d7bb2c8cca6acfb6592db421  # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195  # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467  # QIBI
          - c30d2958827d1867c73318a5a2957eb1  # RED
          - ae58039e1319178e6be73caab5c42166  # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213  # STAN
          - 5d2317d99af813b6529c7ebf01c83533  # VDL
          - 77a7b25585c18af08f60b1547bb9b4fb  # CC
          # HQ Source Groups
          - e6258996055b9fbab7e9cb2f75819294  # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503  # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4  # WEB Scene
        quality_profiles:
          - name: WEB-2160p
```
