### ISSUE TITLE
rework config for sane composition of quality profiles

### ISSUE THREAD

**Issue by ftc2** [recyclarr/recyclarr#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i see there is already discussion about changing up the config's data structures here: https://github.com/recyclarr/recyclarr/issues/144
i have some thoughts specifically about ease of composing quality profiles (QPs).

this is my first time using the software, and i think it's pretty sweet. thanks a lot.

i was struck by the impression that it seems very awkward to compose QPs.

my assumption is that the custom format (CF) sync feature originally did not include QP score support, and this feature was added on later.

regardless, consider the following config sample:

```yaml
custom_formats:
  - trash_ids:
      - ed38b889b31be83fda192888e2286d83 # CF1
      - 5763d1b0ce84aff3b21038eea8e9b8ad # CF6
    quality_profiles:
      - name: QP1
        score: 10
      - name: QP2
        score: 5
  - trash_ids:
      - 90cedc1fea7ea5d11298bebd3d1d3223 # CF2
    quality_profiles:
      - name: QP1
        score: 20
      - name: QP2
        score: 10
  - trash_ids:
      - 90a6f9a284dff5103f6346090e6280c8 # CF3
    quality_profiles:
      - name: QP1
        score: 30
      - name: QP2
        score: 15
  - trash_ids:
      - eecf3a857724171f968a66cb5719e152 # CF4
    quality_profiles:
      - name: QP2
        score: 80
  - trash_ids:
      - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # CF5
    quality_profiles:
      - name: QP1
        score: 50
```

consider this alternative structure that represents the same information:

```yaml
quality_profiles:
  - QP1:
      custom_formats:
        ed38b889b31be83fda192888e2286d83: 10 # CF1
        90cedc1fea7ea5d11298bebd3d1d3223: 20 # CF2
        90a6f9a284dff5103f6346090e6280c8: 30 # CF3
        9f6cbff8cfe4ebbc1bde14c7b7bec0de: 50 # CF5
        5763d1b0ce84aff3b21038eea8e9b8ad: 10 # CF6
  - QP2:
      custom_formats:
        ed38b889b31be83fda192888e2286d83: 5  # CF1
        90cedc1fea7ea5d11298bebd3d1d3223: 10 # CF2
        90a6f9a284dff5103f6346090e6280c8: 15 # CF3
        eecf3a857724171f968a66cb5719e152: 80 # CF4
        5763d1b0ce84aff3b21038eea8e9b8ad: 5  # CF6
```

the latter is more concise and imo saner to compose. i think it also simplifies sharing QPs with friends and the community.

i think an approach like this is also much more intuitive and better matches the thought process used in configuring sonarr/radarr.

i appreciate your thoughts. thanks :)
