### ISSUE TITLE
Not applying preferred ratio for qualities in Sonarr (Radarr ok)

### ISSUE THREAD

**Issue by 6twenty** [recyclarr/recyclarr#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've set up a preferred ratio of 0.5 for the "series" quality definition for Sonarr v4. `recyclarr sync -p` shows the correct preview for the quality size settings, but `recylarr sync` doesn't actually apply the preferred size. Sonarr shows that the preferred size is equal to the max size, although I can't recall if that's been set by recyclarr or if I already had them set that way.

I also have Radarr set up the same way but the sizes got applied ok there.

Using docker (both for radarr/sonarr as well as recyclarr) and on the latest images.

Tried changing the ratio to other values, but none get applied in Sonarr.

### Expected Behavior

Preferred size for each quality should be set according to the defined ratio.

### Steps To Reproduce

My config is set up in `configs/sonarr.yml` (alongside `configs/radarr.yml`, as well as 4k variants of both).

Running `docker compose exec recyclarr recyclarr sync` shows a successful sync, but the qualities in Sonarr do not have the correct preferred sizes.

Example WEBDL-1080p sizes: 15 / 395 / 400
<img width="430" alt="image" src="https://github.com/recyclarr/recyclarr/assets/169607/4fb35346-6ceb-4d7d-ad4d-b54cd2e49c4c">

### Environment & Versions

```bash
- Operating System: Raspberry Pi OS
- Architecture: arm64
- Recyclarr Version: 5.1.1+Branch.tags-v5.1.1.Sha.4d0ce0d09f367ce2520eca53c4043568efa328fd
- Recyclarr Build: Docker
- Sonarr Version: 4.0.0.552
- Radarr Version: 4.6.4.7568
```

### Recyclarr Log File(s)

Note that there are 4x services configured: radarr, radarr4k, sonarr, and sonarr4k. Both sonarr's are experiencing the same problem.

[recyclarr_2023-07-05_20-37-04.debug.log](https://github.com/recyclarr/recyclarr/files/11955816/recyclarr_2023-07-05_20-37-04.debug.log)

### Configuration YAML

```YAML
# Updated: 2023-07-03
sonarr: # Service type
  sonarr: # Instance name
    base_url: "http://sonarr:8989"
    api_key: "REDACTED"

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_definition:
      type: series
      preferred_ratio: 0.5

    quality_profiles:
      - name: "1080p"
        reset_unmatched_scores: true

    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09  # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4  # LQ
          - 47435ece6b99a0b477caf360e79ba0bb  # x265 (HD)

          # Misc
          - ec8fa7296b64e8cd390a1600981f3923  # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c  # Repack v2
          - 44e7c4de10ae50265753082e5dc76047  # Repack v3

          # Streaming Services
          - d660701077794679fd59e8bdf4ce3a29  # AMZN
          - f67c9ca88f463a48346062e8ad07713f  # ATVP
          - 4e9a630db98d5391aec1368a0256e2fe  # CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb  # DCU
          - 89358767a60cc28783cdc3d0be9388a4  # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6  # HBO
          - a880d6abc21e7c16884f3ae393f84179  # HMAX
          - f6cce30f1733d5c8194222a7507909bb  # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c  # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c  # MAX
          - d34870697c9db575f17700212167be23  # NF
          - b2b980877494b560443631eb1f473867  # NLZ
          - 1656adc6d7bb2c8cca6acfb6592db421  # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195  # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467  # QIBI
          - c30d2958827d1867c73318a5a2957eb1  # RED
          - ae58039e1319178e6be73caab5c42166  # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213  # STAN
          - 5d2317d99af813b6529c7ebf01c83533  # VDL
          - 77a7b25585c18af08f60b1547bb9b4fb  # CC

          # HQ Source Groups
          - e6258996055b9fbab7e9cb2f75819294  # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503  # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6  # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4  # WEB Scene
        quality_profiles:
          - name: "1080p"
```

### Sonarr / Radarr Logs

```
2023-07-05 20:46:25.4|Trace|Scheduler|Pending Tasks: 0
2023-07-05 20:46:25.6|Trace|Http|Req: 1530 [GET] /api/v3/system/status (from 172.18.0.13)
2023-07-05 20:46:25.6|Trace|Http|Res: 1530 [GET] /api/v3/system/status: 200.OK (3 ms)
2023-07-05 20:46:25.6|Debug|Api|[GET] /api/v3/system/status: 200.OK (3 ms)
2023-07-05 20:46:26.6|Trace|Http|Req: 1531 [GET] /api/v3/customformat (from 172.18.0.13)
2023-07-05 20:46:26.6|Trace|Http|Res: 1531 [GET] /api/v3/customformat: 200.OK (22 ms)
2023-07-05 20:46:26.6|Debug|Api|[GET] /api/v3/customformat: 200.OK (22 ms)
2023-07-05 20:46:27.1|Trace|Http|Req: 1532 [GET] /api/v3/qualityprofile (from 172.18.0.13)
2023-07-05 20:46:27.1|Trace|Http|Res: 1532 [GET] /api/v3/qualityprofile: 200.OK (8 ms)
2023-07-05 20:46:27.1|Debug|Api|[GET] /api/v3/qualityprofile: 200.OK (8 ms)
2023-07-05 20:46:27.2|Trace|Http|Req: 1533 [GET] /api/v3/qualitydefinition (from 172.18.0.13)
2023-07-05 20:46:27.2|Trace|Http|Res: 1533 [GET] /api/v3/qualitydefinition: 200.OK (3 ms)
2023-07-05 20:46:27.2|Debug|Api|[GET] /api/v3/qualitydefinition: 200.OK (3 ms)
2023-07-05 20:46:27.3|Trace|Http|Req: 1534 [PUT] /api/v3/qualityDefinition/update (from 172.18.0.13)
2023-07-05 20:46:27.3|Trace|Http|Res: 1534 [PUT] /api/v3/qualityDefinition/update: 202.Accepted (4 ms)
2023-07-05 20:46:27.3|Debug|Api|[PUT] /api/v3/qualityDefinition/update: 202.Accepted (4 ms)
```
