### ISSUE TITLE
Sonarr v4 Connection refused

### ISSUE THREAD

**Issue by andresatierf** [recyclarr/recyclarr#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when runnning `docker compose run recyclarr sync sonarr` with the below configuration I get the following error:
```shell
===========================================
Processing Sonarr Server: [sonarr]
===========================================

[ERR] Exception trying to obtain service version: Call failed. Connection refused : GET http://REDACTED:8989/api/v3/system/status
[ERR] Exception: Capabilities could not be obtained
```
when using curl to fetch the same endpoint, I get the correct output

radarr works just fine

[output.log](https://github.com/recyclarr/recyclarr/files/12136580/output.log)

### Expected Behavior

Expected sonarr to work, just like radarr

### Steps To Reproduce

1. use 3 docker containers for sonarr, radarr and recyclarr on the same network
2. use config used above
3. run `docker compose run --rm recyclarr sync radarr`
4. run `docker compose run --rm recyclarr sync sonarr`

### Environment & Versions

```bash
- Operating System: Linux
- Architecture: x64
- Recyclarr Version: 5.1.1
- Recyclarr Build: Docker
- Sonarr Version: 4.0.0
- Radarr Version: 4.6.4
```

### Recyclarr Log File(s)

[recyclarr_2023-07-22_14-24-28.debug.log](https://github.com/recyclarr/recyclarr/files/12136564/recyclarr_2023-07-22_14-24-28.debug.log)
[recyclarr_2023-07-22_14-24-28.verbose.log](https://github.com/recyclarr/recyclarr/files/12136565/recyclarr_2023-07-22_14-24-28.verbose.log)

### Configuration YAML

```YAML
sonarr:
  sonarr:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr:8989
    api_key: <apikey>

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    quality_profiles:
      - name: WEB-1080p
        reset_unmatched_scores: true

    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)

          # Misc
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3

          # Streaming Services
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - 4e9a630db98d5391aec1368a0256e2fe # CRAV
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
          - d34870697c9db575f17700212167be23 # NF
          - b2b980877494b560443631eb1f473867 # NLZ
          - fb1a91cdc0f26f7ca0696e0e95274645 # OViD
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
          - c30d2958827d1867c73318a5a2957eb1 # RED
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
          - 5d2317d99af813b6529c7ebf01c83533 # VDL
          - 77a7b25585c18af08f60b1547bb9b4fb # CC

          # HQ Source Groups
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene

        quality_profiles:
          - name: WEB-1080p

radarr:
  radarr:
    # Set the URL/API Key to your actual instance
    base_url: http://radarr:7878
    api_key: <apikey>

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    quality_profiles:
      - name: HD Bluray + WEB
        reset_unmatched_scores: true

    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      # Scores from TRaSH json
      - trash_ids:
          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          # HQ Release Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03

          # Misc
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2

          # Unwanted
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D

          # Streaming Services
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
        quality_profiles:
          - name: HD Bluray + WEB

      # Custom Scoring
      - trash_ids:
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - fbca986396c5e695ef7b2def3c755d01 # OViD
          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
        quality_profiles:
          - name: HD Bluray + WEB
            score: 0
```

### Sonarr / Radarr Logs

_No output_
