### ISSUE TITLE
Getting "The following quality profile names are not valid and should either be removed or renamed in your YAML config"

### ISSUE THREAD

**Issue by mpwg** [recyclarr/recyclarr#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

its the same issue as in #26.
Running sync gets me
`[WRN] The following quality profile names are not valid and should either be removed or renamed in your YAML config
[WRN] ["Remux + WEB 2160p"]
`

I've tried renaming  `"Remux + WEB 2160p"` to something else (removing space, '+') but it didn't change the behavior. 
Am I doing something wrong?

### Expected Behavior

it should sync the quality profile. It only syncs the custom formats.

I've used your (great) templates and only changed the url/key to env. variables

`    base_url: !env_var RADARR_BASE_URL
    api_key: !env_var RADARR_API_KEY
`

### Steps To Reproduce

run `recyclarr sync`

### Environment & Versions

```bash
- Operating System: unraid
- Architecture: x64
- Recyclarr Version: 5.1.1+Branch.tags-v5.1.1.Sha.4d0ce0d09f367ce2520eca53c4043568efa328fd
- Recyclarr Build: Docker
- Sonarr Version:
- Radarr Version:4.6.4.7568
```

### Recyclarr Log File(s)

[recyclarr_2023-07-28_21-04-05.verbose.log](https://github.com/recyclarr/recyclarr/files/12197642/recyclarr_2023-07-28_21-04-05.verbose.log)
[recyclarr_2023-07-28_21-04-05.debug.log](https://github.com/recyclarr/recyclarr/files/12197644/recyclarr_2023-07-28_21-04-05.debug.log)

### Configuration YAML

```YAML
# Updated: 2023-07-19
radarr:
  radarr:  # A custom name used to identify this particular instance.
    base_url: !env_var RADARR_BASE_URL
    api_key: !env_var RADARR_API_KEY

    quality_definition:
      type: movie

    quality_profiles:
      - name: RemuxWEB1080p
        reset_unmatched_scores: true

    custom_formats:
      # Scores from TRaSH json
      - trash_ids:
          # Audio - Uncomment the next section if you are using the Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169  # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95  # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475  # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e  # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f  # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd  # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b  # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b  # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db  # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424  # DD+
          # - f9f847ac70a0af62ea4a08280b859636  # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73  # DTS
          # - 240770601cc226190c367ef59aba7463  # AAC
          # - c2998bd0d90ed5621d8df281e839436e  # DD
          
          # Movie Versions
          - 0f12c086e289cf966fa5948eac571f44  # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c  # Remaster
          - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e  # Special Edition
          - eecf3a857724171f968a66cb5719e152  # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de  # IMAX Enhanced
          
          # HQ Release Groups
          - 3a3ff47579026e76d6504ebea39390de  # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a  # Remux Tier 02
          - 8baaf0b3142bf4d94c42a724f034e27a  # Remux Tier 03
          - c20f169ef63c5f40c2def54abaf4438e  # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4  # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b  # WEB Tier 03
          
          # Misc
          - e7718d7a3ce595f289bfee26adc178f5  # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4  # Repack2
          
          # Unwanted
          - ed38b889b31be83fda192888e2286d83  # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8  # LQ
          - dc98083864ea246d05a42df0d05f81cc  # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6  # 3D
          
          # Streaming Services
          - cc5e51a9e85a6296ceefe097a77f12f4  # BCORE
          - 2a6039655313bf5dab1e43523b62c374  # MA
          - 16622a6911d1ab5d5b8b713d5b0036d4  # CRiT
        quality_profiles:
          - name: RemuxWEB1080p

      # Custom Scoring
      - trash_ids:
          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df  # AMZN
          - 40e9380490e748672c2522eaaeb692f7  # ATVP
          - f6ff65b3f4b464a79dcc75950fe20382  # CRAV
          - 84272245b2988854bfb76a16e60baea5  # DSNP
          - 509e5f41146e278f9eab1ddaceb34515  # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad  # HMAX
          - 526d445d4c16214309f0fd2b3be18a89  # Hulu
          - 6a061313d22e51e0f25b7cd4dc065233  # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6  # NF
          - fbca986396c5e695ef7b2def3c755d01  # OViD
          - bf7e73dd1d85b12cc527dc619761c840  # Pathe
          - c9fd353f8f5f1baf56dc601c4cb29920  # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd  # PMTP
          - c2863d2a50c9acad1fb50e53ece60817  # STAN
        quality_profiles:
          - name: RemuxWEB1080p
            score: 0
```
