### ISSUE TITLE
Quality group cannot be the same name as quality

### ISSUE THREAD

**Issue by calvinbui** [recyclarr/recyclarr#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yaml
qualities:
  -
    name: Bluray-1080p
    enabled: true
    qualities:
      - Bluray-1080p Remux
      - Bluray-1080p
```

Results in:

```
[ERR] Config Validation: For profile Anime, 'qualities' contains duplicates for quality 'Bluray-1080p'
[ERR] Config validation failed with 1 errors
```

### Expected Behavior

The group name can be the same as the quality:

![image](https://github.com/recyclarr/recyclarr/assets/3604363/b59d200e-efd2-4f09-b2bb-51c52d924999)

![image](https://github.com/recyclarr/recyclarr/assets/3604363/dedc0cfd-1786-4659-a47c-dde57a982364)

### Steps To Reproduce

N/A

### Environment & Versions

```bash
- Operating System: Ubuntu 22.04
- Architecture: x64
- Recyclarr Version: 5.2.0
- Recyclarr Build: Docker
- Sonarr Version: 4.0.0.602
- Radarr Version: N/A
```

### Recyclarr Log File(s)

N/A

### Configuration YAML

```YAML
sonarr:
    quality_profiles:
      - name: Anime
        reset_unmatched_scores: true
        min_format_score: 100
        upgrade:
          allowed: true
          until_quality: Bluray 1080p
          until_score: 10000
        quality_sort: top
        qualities:
          -
            name: Bluray-1080p
            enabled: true
            qualities:
              - Bluray-1080p Remux
              - Bluray-1080p
```
```


### Sonarr / Radarr Logs

N/A
