### ISSUE TITLE
Recyclarr 5.3 errors in parsing quality_profiles

### ISSUE THREAD

**Issue by mirolm** [recyclarr/recyclarr#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My config worked fine with recyclarr 5.2.1. With upgrade to 5.3 sync errors with a stacktrace without telling what is wrong in my config.

### Expected Behavior

Expected to sync without issues.

### Steps To Reproduce

1. With my config both executable and config are in the same directory.
2. OS is quite old - Debian Buster 10
3. Run the command - /opt/recyclarr/recyclarr sync -c /opt/recyclarr/recyclarr.yml
4. Recyclarr errors with the below:

```
===========================================
Processing Sonarr Server: [anime]
===========================================

[INF] Skipped 42 Custom Formats that did not change
[INF] All custom formats are already up to date!
[ERR] Non-recoverable Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Recyclarr.Cli.Processors.ConsoleExceptionHandler.HandleException(Exception sourceException) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Processors/ConsoleExceptionHandler.cs:line 63
   at Recyclarr.Cli.Processors.Sync.SyncProcessor.ProcessConfigs(ISyncSettings settings) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Processors/Sync/SyncProcessor.cs:line 52
   at Recyclarr.Cli.Console.Commands.SyncCommand.ExecuteAsync(CommandContext context, CliSettings settings) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Console/Commands/SyncCommand.cs:line 66
   at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in /_/src/Spectre.Console.Cli/Internal/CommandExecutor.cs:line 85
   at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in /_/src/Spectre.Console.Cli/CommandApp.cs:line 84
   at Spectre.Console.Cli.CommandApp.Run(IEnumerable`1 args) in /_/src/Spectre.Console.Cli/CommandApp.cs:line 58
   at Recyclarr.Cli.Program.Main(String[] args) in /home/runner/work/recyclarr/recyclarr/src/Recyclarr.Cli/Program.cs:line 52
```

### Environment & Versions

```bash
- Operating System: Debian Buster 10
- Architecture: x86-64
- Recyclarr Version: 5.3
- Recyclarr Build: 5.3.0+Branch.tags-v5.3.0.Sha.f3f95b3cd6905335b94b48502a0f44b7b2f1e4e2
- Sonarr Version: 4.0.0.645
- Radarr Version:
```

### Recyclarr Log File(s)

[recyclarr_2023-08-21_20-58-11.debug.log](https://github.com/recyclarr/recyclarr/files/12402501/recyclarr_2023-08-21_20-58-11.debug.log)
[recyclarr_2023-08-21_20-58-11.verbose.log](https://github.com/recyclarr/recyclarr/files/12402502/recyclarr_2023-08-21_20-58-11.verbose.log)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# https://github.com/TRaSH-/Guides

# https://recyclarr.dev/wiki/
# https://github.com/recyclarr/recyclarr

# /opt/recyclarr/recyclarr list qualities sonarr
# /opt/recyclarr/recyclarr list custom-formats sonarr

# Configuration specific to Sonarr
sonarr:
  # Set the URL/API Key to your actual instance
  anime:
    base_url: http://localhost:8989
    api_key: {REDACTED_KEY}

    # Only enable to do manual cleanup.
    delete_old_custom_formats: false

    # Replace custom formats.
    replace_existing_custom_formats: true

    # Quality definitions from the guide to sync.
    quality_definition:
      type: anime

    quality_profiles:
      - name: HD-1080p

    # Custom formats from the guide to sync.
    custom_formats:
      - trash_ids:
          - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers)
        quality_profiles:
          - name: HD-1080p
            score: 2700

      - trash_ids:
          - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers)
        quality_profiles:
          - name: HD-1080p
            score: 2600

      - trash_ids:
          - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers)
        quality_profiles:
          - name: HD-1080p
            score: 2500

      - trash_ids:
          - 30feba9da3030c5ed1e0f7d610bcadc4 # Anime BD Tier 04 (SeaDex Muxers)
        quality_profiles:
          - name: HD-1080p
            score: 2400

      - trash_ids:
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
        quality_profiles:
          - name: HD-1080p
            score: 2300

      - trash_ids:
          - 545a76b14ddc349b8b185a6344e28b04 # Anime BD Tier 05 (Remuxes)
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02
        quality_profiles:
          - name: HD-1080p
            score: 2200

      - trash_ids:
          - 25d2afecab632b1582eaf03b63055f72 # Anime BD Tier 06 (FanSubs)
        quality_profiles:
          - name: HD-1080p
            score: 2100

      - trash_ids:
          - 0329044e3d9137b08502a9f84a7e58db # Anime BD Tier 07 (P2P/Scene)
        quality_profiles:
          - name: HD-1080p
            score: 2000

      - trash_ids:
          - c81bbfb47fed3d5a3ad027d077f889de # Anime BD Tier 08 (Mini Encodes)
        quality_profiles:
          - name: HD-1080p
            score: 1900

      - trash_ids:
          - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01 (Muxers)
        quality_profiles:
          - name: HD-1080p
            score: 1800

      - trash_ids:
          - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02 (Top FanSubs)
        quality_profiles:
          - name: HD-1080p
            score: 1700

      - trash_ids:
          - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03 (Official Subs)
        quality_profiles:
          - name: HD-1080p
            score: 1600

      - trash_ids:
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
        quality_profiles:
          - name: HD-1080p
            score: 1500

      - trash_ids:
          - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04 (Official Subs)
        quality_profiles:
          - name: HD-1080p
            score: 1400

      - trash_ids:
          - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 05 (FanSubs)
        quality_profiles:
          - name: HD-1080p
            score: 1300

      - trash_ids:
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
        quality_profiles:
          - name: HD-1080p
            score: 1200

      - trash_ids:
          - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 06 (FanSubs)
        quality_profiles:
          - name: HD-1080p
            score: 1100

      - trash_ids:
          - 3e0b26604165f463f3e8e192261e7284 # CR
        quality_profiles:
          - name: HD-1080p
            score: 50

      - trash_ids:
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
        quality_profiles:
          - name: HD-1080p
            score: 45

      - trash_ids:
          - d34870697c9db575f17700212167be23 # NF
        quality_profiles:
          - name: HD-1080p
            score: 40

      - trash_ids:
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV
        quality_profiles:
          - name: HD-1080p
            score: 35

      - trash_ids:
          - 1284d18e693de8efe0fe7d6b3e0b9170 # FUNi
        quality_profiles:
          - name: HD-1080p
            score: 30

      - trash_ids:
          - d54cd2bf1326287275b56bccedb72ee2 # ADN
        quality_profiles:
          - name: HD-1080p
            score: 25

      - trash_ids:
          - 570b03b3145a25011bf073274a407259 # HIDIVE
          - 7dd31f3dee6d2ef8eeaa156e23c3857e # B-Global
          - 4c67ff059210182b59cdd41697b8cb08 # Bilibili
        quality_profiles:
          - name: HD-1080p
            score: 20

      - trash_ids:
          - 4fc15eeb8f2f9a749f918217d4234ad8 # v4
        quality_profiles:
          - name: HD-1080p
            score: 8

      - trash_ids:
          - 0e5833d3af2cc5fa96a0c29cd4477feb # v3
        quality_profiles:
          - name: HD-1080p
            score: 7

      - trash_ids:
          - 228b8ee9aa0a609463efca874524a6b8 # v2
        quality_profiles:
          - name: HD-1080p
            score: 6

      - trash_ids:
          - 273bd326df95955e1b6c26527d1df89b # v1
        quality_profiles:
          - name: HD-1080p
            score: 5

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        quality_profiles:
          - name: HD-1080p
            score: 1

      - trash_ids:
          - d2d7b8a9d39413da5f44054080e028a3 # v0
        quality_profiles:
          - name: HD-1080p
            score: -101

      - trash_ids:
          - e3515e519f3b1360cbfc17651944354c # Anime LQ Groups
          - b4a1b3d705159cdca36d71e57ca86871 # Anime Raws
          - 9c14d194486c4014d422adc64092d794 # Dubs Only
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 07a32f77690263bb9fda1842db7e273f # VOSTFR
        quality_profiles:
          - name: HD-1080p
            score: -10000
```
