### ISSUE TITLE
Unable to add a single CF to Sonarr v4

### ISSUE THREAD

**Issue by biship** [recyclarr/recyclarr#214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add a single CF to Sonarr v4.
I have 4 Quality Profiles and zero Custom Formats in Sonarr v4.
Recyclarr fails to parse my reclarr.yml and is expecting a - on the line:  quality_profiles:
I can use quality_profiles: after trash-ids. according to https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/

### Expected Behavior

Create a 'AMZN' CF.
Add that CF to all 4 Quality Profiles

### Steps To Reproduce

cd C:\Users\nick\AppData\Roaming\recyclarr
./recyclarr.exe sync sonarr -p -d

### Environment & Versions

```bash
- Operating System: Win 11
- Architecture: x64
- Recyclarr Version: 5.4.3+Branch.tags-v5.4.3.Sha.d4e8be42ddd69f6b226f5e9ca6246957d439eb9f
- Recyclarr Build: win-x64
- Sonarr Version: 4.0.0.682
- Radarr Version:
```

### Recyclarr Log File(s)

[recyclarr_2023-09-20_14-51-17.verbose.log](https://github.com/recyclarr/recyclarr/files/12676622/recyclarr_2023-09-20_14-51-17.verbose.log)
[recyclarr_2023-09-20_14-51-17.debug.log](https://github.com/recyclarr/recyclarr/files/12676624/recyclarr_2023-09-20_14-51-17.debug.log)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  sonarr:
    # Set the URL/API Key to your actual instance
    base_url: http://192.168.0.99:8989/sonarr
    api_key: <redacted>

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    custom_formats:
       - trash_ids:
          # [No Category]
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
       quality_profiles:
          - name: 1080p to 4K Remux
          - name: 720p to 4K Remux
          - name: Any
          - name: SDTV to 1080p
```

**Comment by rcdailey** [comment]
Your YAML is malformed. You can use any yaml lint tool online to see this. I recommend you use [VS Code with Schema Validaton](https://recyclarr.dev/wiki/schema-validation/) for editing in the future as it will easily point out these issues.

The correct YAML should be:

```yml
    custom_formats:
       - trash_ids:
          # [No Category]
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
         quality_profiles:
          - name: 1080p to 4K Remux
          - name: 720p to 4K Remux
          - name: Any
          - name: SDTV to 1080p
```
