### ISSUE TITLE
Allow custom format definition in Recyclarr config 

### ISSUE THREAD

**Issue by qwedass** [recyclarr/recyclarr#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Recyclarr allows for synchronization of CF from the TRaSH guides. However, the guide feature some CF which cannot be synced (they do not have TRaSH IDs) due to the almost endless possible combinations.

I am talking about language CF. While the guides can be updated to provide some popular ones such as "original language" or "English language", it is almost impossible to cover all combinations ("XXX language", "Prefer XXX, then YYY").

Currently the user must import/create their desired language CF manually in Radarr and Sonarr. This is less than ideal for several reasons:
- Duplicated effort: CF must be manually created/imported/updated for every instance of Radarr and Sonarr
- Extra Recyclarr config: Recyclarr neeeds to be manually configured to not reset their scores in the quality profiles it manages. 

A better option will be to allow the user to define a CF in Recyclarr config.  They can give it a name, which can serve as a unique ID, and include it in quality profiles. 

Example:
```yaml
custom_formats:
  - ids:
        # 'trash_id' and 'id' are mutually exclusive
        # 'definition' is only allowed in combination with 'id'
      -  trash_id: 570bc9ebecd92723d2d21500f4be314c
      -  id: my-cf
         definition: # object allowing for arbitrary keys and values  OR a string allowing for a raw JSON string
  quality_profiles:
    - My Profile
```

NOTE: Technically in the example above the 'id' attribute can be ommitted and 'trash_id' and 'definition' can be mutually exclusive. However, I think it will be good to have it anyway, as a way to reference the CF in overrides or (depending on implementation) when #188 is implemented.

**Comment by absywabsy** [comment]
I have created my own custom format and I assign it a score (manually within sonarr and radarr) in a quality profile that is also managed by Recyclarr.

When I do recyclarr sync, it removes the score I added to the profile and assigns it 0. 

I am not very technical, but I think I understand that if your suggestion was implemented, I would be able to specify my own custom format within recyclarr and provide it a score and the score won't be overwritten with a 0 during sync?

**Comment by elvismercado** [comment]
I also did the same as @absywabsy 
Resulting in custom added format scoring being reset every time the sync runs.

Would highly appreciate being able te define my own custom format like @qwedass was asking.

**Comment by rcdailey** [comment]
Has anyone considered forking the Trash Guides to add your own custom CFs there, with their own trash IDs, and syncing them that way? I realize a fork is not really ideal, but it's the best workaround I have right now. Any customizations users want to make that deviate from what the official guides provide can be done this way.

**Comment by elvismercado** [comment]
Yeah thats exactly what i'm thinking of doing.

**Comment by rcdailey** [comment]
@absywabsy @qwedass does the solution posted in my previous comment also work for you both?

**Comment by Jonas-Sander** [comment]
> Yeah thats exactly what i'm thinking of doing.
> 
> Edit: Forked and added my custom formats. Configed recyclarr to use my fork and now its all fine. It would still be great to be able to add custom formats through configuration

How did you configure recyclarr to use your own fork? @elvismercado

**Comment by elvismercado** [comment]
great to see you already found it.

i havent updated my fork from master in quite a while. i should do that soon.

May have to just check configarr

**Comment by kserge1t** [comment]
Just encountered the same problem. Created a few manual custom language formats but could not use them with the recyclarr managed profiles. 

So forking is the best workaround to date? 

Do we know if recyclarr will be supporting manual custom formats in the future?!

**Comment by kserge1t** [comment]
Found a solution/workaround to the problem:

The example below will not reset scores for the "Language: Original" and "Language: Russian" custom formats in the "UHD Bluray + WEB" quality profile. Modify as needed and add to your configuration file.

```
    quality_profiles:
      - name: UHD Bluray + WEB
        reset_unmatched_scores:
          except:
            - "Language: Original"
            - "Language: Russian"
```


![image](https://github.com/user-attachments/assets/006c0632-c49c-4a72-a26e-97f6a5e24a6f)
