### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by gunysa1** [recyclarr/recyclarr#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to use the latest build i get this error:
[ERR] Non-recoverable Exception
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
SonarrConfigYaml -> SonarrConfiguration
Recyclarr.Config.Parsing.SonarrConfigYaml -> Recyclarr.Config.Models.SonarrConfiguration

Type Map configuration:
SonarrConfigYaml -> SonarrConfiguration
Recyclarr.Config.Parsing.SonarrConfigYaml -> Recyclarr.Config.Models.SonarrConfiguration

Destination Member:
BaseUrl

 ---> System.UriFormatException: Invalid URI: The URI scheme is not valid.

### Expected Behavior

It should start the config

### Steps To Reproduce

i dont know, it happens with the default configs.

### Environment & Versions

```bash
- Operating System: windows 11 & debian (happens on both)
- Architecture: x64
- Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
- Recyclarr Build:
- Sonarr Version: 3.0.10.1567
- Radarr Version: 4.7.5.7809
```

### Recyclarr Log File(s)

[11:09:38 DBG] Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
[11:09:38 DBG] App Data Dir: C:\Users\Guny\AppData\Roaming\recyclarr
[11:09:38 DBG] Config Templates Repo: Using Branch & Clone URL: master, https://github.com/recyclarr/config-templates.git
[11:09:38 DBG] Trash Guides Repo: Using Branch & Clone URL: master, https://github.com/TRaSH-Guides/Guides.git
[11:09:38 DBG] Trash Guides Repo: Executing git command with args: ["status"]
[11:09:38 DBG] Config Templates Repo: Executing git command with args: ["status"]
[11:09:38 DBG] Trash Guides Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\trash-guides
[11:09:38 DBG] Config Templates Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\config-templates
[11:09:38 DBG] Config Templates Repo: Command Output: On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[11:09:38 DBG] Config Templates Repo: Executing git command with args: ["remote","set-url","origin","https://github.com/recyclarr/config-templates.git"]
[11:09:38 DBG] Config Templates Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\config-templates
[11:09:38 DBG] Trash Guides Repo: Command Output: On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[11:09:38 DBG] Trash Guides Repo: Executing git command with args: ["remote","set-url","origin","https://github.com/TRaSH-Guides/Guides.git"]
[11:09:38 DBG] Trash Guides Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\trash-guides
[11:09:38 DBG] Config Templates Repo: Command Output: 
[11:09:38 DBG] Config Templates Repo: Remote 'origin' set to https://github.com/recyclarr/config-templates.git
[11:09:38 DBG] Config Templates Repo: Executing git command with args: ["checkout","-f","master"]
[11:09:38 DBG] Config Templates Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\config-templates
[11:09:38 DBG] Trash Guides Repo: Command Output: 
[11:09:38 DBG] Trash Guides Repo: Remote 'origin' set to https://github.com/TRaSH-Guides/Guides.git
[11:09:38 DBG] Trash Guides Repo: Executing git command with args: ["checkout","-f","master"]
[11:09:38 DBG] Trash Guides Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\trash-guides
[11:09:38 DBG] Trash Guides Repo: Command Output: Your branch is up to date with 'origin/master'.
[11:09:38 DBG] Config Templates Repo: Command Output: Your branch is up to date with 'origin/master'.
[11:09:38 DBG] Config Templates Repo: Executing git command with args: ["fetch","origin"]
[11:09:38 DBG] Trash Guides Repo: Executing git command with args: ["fetch","origin"]
[11:09:38 DBG] Config Templates Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\config-templates
[11:09:38 DBG] Trash Guides Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\trash-guides
[11:09:39 DBG] Config Templates Repo: Command Output: 
[11:09:39 DBG] Config Templates Repo: Executing git command with args: ["reset","--hard","origin/master"]
[11:09:39 DBG] Config Templates Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\config-templates
[11:09:39 DBG] Trash Guides Repo: Command Output: 
[11:09:39 DBG] Trash Guides Repo: Executing git command with args: ["reset","--hard","origin/master"]
[11:09:39 DBG] Trash Guides Repo: Using working directory: C:\Users\Guny\AppData\Roaming\recyclarr\repositories\trash-guides
[11:09:39 DBG] Config Templates Repo: Command Output: HEAD is now at e551b98 feat: Add DV HDR10 Plus Custom Format (#63)
[11:09:39 DBG] Trash Guides Repo: Command Output: HEAD is now at 5594a16 chore(gha): fix labeler (#1687)
[11:09:39 DBG] recyclarr.yml: Loading config file: C:\Users\Guny\AppData\Roaming\recyclarr\recyclarr.yml
[11:09:39 ERR] Non-recoverable Exception
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
RadarrConfigYaml -> RadarrConfiguration
Recyclarr.Config.Parsing.RadarrConfigYaml -> Recyclarr.Config.Models.RadarrConfiguration

Type Map configuration:
RadarrConfigYaml -> RadarrConfiguration
Recyclarr.Config.Parsing.RadarrConfigYaml -> Recyclarr.Config.Models.RadarrConfiguration

Destination Member:
BaseUrl

 ---> System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at lambda_method222(Closure, Object, RadarrConfiguration, ResolutionContext)
   --- End of inner exception stack trace ---
   at lambda_method222(Closure, Object, RadarrConfiguration, ResolutionContext)
   at Recyclarr.Config.Parsing.ConfigurationLoader.<MapConfigs>b__10_0[TConfigYaml,TServiceConfig](KeyValuePair`2 x) in D:\a\recyclarr\recyclarr\src\Recyclarr.Config\Parsing\ConfigurationLoader.cs:line 83
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Recyclarr.Config.Parsing.ConfigurationLoader.ProcessLoadedConfigs(RootConfigYaml config) in D:\a\recyclarr\recyclarr\src\Recyclarr.Config\Parsing\ConfigurationLoader.cs:line 68
   at Recyclarr.Config.Parsing.ConfigurationLoader.Load(IFileInfo file) in D:\a\recyclarr\recyclarr\src\Recyclarr.Config\Parsing\ConfigurationLoader.cs:line 35
   at Recyclarr.Config.ConfigurationRegistry.<LoadAndFilterConfigs>b__6_0(IFileInfo x) in D:\a\recyclarr\recyclarr\src\Recyclarr.Config\ConfigurationRegistry.cs:line 52
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Recyclarr.Config.ConfigurationRegistry.LoadAndFilterConfigs(IEnumerable`1 configs, ConfigFilterCriteria filterCriteria) in D:\a\recyclarr\recyclarr\src\Recyclarr.Config\ConfigurationRegistry.cs:line 52
   at Recyclarr.Config.ConfigurationRegistry.FindAndLoadConfigs(ConfigFilterCriteria filterCriteria) in D:\a\recyclarr\recyclarr\src\Recyclarr.Config\ConfigurationRegistry.cs:line 31
   at Recyclarr.Cli.Processors.Sync.SyncProcessor.ProcessConfigs(ISyncSettings settings) in D:\a\recyclarr\recyclarr\src\Recyclarr.Cli\Processors\Sync\SyncProcessor.cs:line 43
   at Recyclarr.Cli.Processors.Sync.SyncProcessor.ProcessConfigs(ISyncSettings settings) in D:\a\recyclarr\recyclarr\src\Recyclarr.Cli\Processors\Sync\SyncProcessor.cs:line 57
   at Recyclarr.Cli.Console.Commands.SyncCommand.ExecuteAsync(CommandContext context, CliSettings settings) in D:\a\recyclarr\recyclarr\src\Recyclarr.Cli\Console\Commands\SyncCommand.cs:line 66
   at Spectre.Console.Cli.CommandExecutor.Execute(IConfiguration configuration, IEnumerable`1 args) in /_/src/Spectre.Console.Cli/Internal/CommandExecutor.cs:line 85
   at Spectre.Console.Cli.CommandApp.RunAsync(IEnumerable`1 args) in /_/src/Spectre.Console.Cli/CommandApp.cs:line 84
   at Spectre.Console.Cli.CommandApp.Run(IEnumerable`1 args) in /_/src/Spectre.Console.Cli/CommandApp.cs:line 58
   at Recyclarr.Cli.Program.Main(String[] args) in D:\a\recyclarr\recyclarr\src\Recyclarr.Cli\Program.cs:line 52
[11:09:39 DBG] Cleaning up logs using max files of 20

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: 
    api_key: 

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    # Release profiles from the guide to sync to Sonarr v3 (Sonarr v4 does not use this!)
    # Use `recyclarr list release-profiles` for values you can put here.
    # https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/
    release_profiles:
      # Series
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
      # Anime (Uncomment below if you want it)
      #- trash_ids:
      #    - d428eda85af1df8904b4bbe4fc2f537c # Anime - First release profile
      #    - 6cd9e10bb5bb4c63d2d7cd3279924c7b # Anime - Second release profile

# Configuration specific to Radarr.
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: 
    api_key: 

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: false

    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (720/1080p)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.
        #quality_profiles:
        #  - name: Quality Profile 1
        #  - name: Quality Profile 2
        #    #score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
        #    #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```
