### ISSUE TITLE
TrashGuide scores not Auto Applying to Profiles in Sonarr 4.0

### ISSUE THREAD

**Issue by deadchimis** [recyclarr/recyclarr#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I began adding in recyclarr settings to my existing Sonarr & Radarr instances recently.  Radarr added custom formats without issue, when attempting to add Sonarr to recyclarr's custom format sync it does not weigh them as scores in the quality profiles.

### Expected Behavior

Sonarr should add the default Trash Guide scores to the profile's associated to the custom formats.

### Steps To Reproduce

Adjust Recyclarr.yml to include trash_ids for custom formats.
quality_profiles: - name: any

run recyclarr sync it updates the quality profiles, but does not adjust the scores

### Environment & Versions

```bash
- Operating System: unraid docker
- Architecture: x64
- Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
- Recyclarr Build:
- Sonarr Version: 4.0.0.741 by linuxserver.io
- Radarr Version: 5.2.6.8376-ls197 by linuxserver.io
```

### Recyclarr Log File(s)

[cli.zip](https://github.com/recyclarr/recyclarr/files/13799949/cli.zip)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://REDACTED:8989
    api_key: REDACTED

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    # Release profiles from the guide to sync to Sonarr v3 (Sonarr v4 does not use this!)
    # Use `recyclarr list release-profiles` for values you can put here.
    # https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/
    custom_formats:
      # Series
      - trash_ids:
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # Low Quality Groups
         # - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (release title)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          
          
      # Anime (Uncomment below if you want it)
     # - trash_ids:
       #   - d428eda85af1df8904b4bbe4fc2f537c # Anime - First release profile
        #  - 6cd9e10bb5bb4c63d2d7cd3279924c7b # Anime - Second release profile

    quality_profiles:
          - name: SonarrStandard
          - name: all
          
          
# Configuration specific to Radarr.
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: http://REDACTED:7878
    api_key: REDACTED

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: false

    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (720/1080p)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
          - e61e28db95d22bedcadf030b8f156d96 # HDR
          - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (no WEBDL)
          - b6832f586342ef70d9c128d40c07b872 # Bad DUal Groups
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.
        quality_profiles:
          - name: HD
          - name: Any
        #    #score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
        #    #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```

### Sonarr / Radarr Logs

[sonarr.txt](https://github.com/recyclarr/recyclarr/files/13799950/sonarr.txt)
