### ISSUE TITLE
[Radarr] HTTP error: Response could not be deserialized to JSON

### ISSUE THREAD

**Issue by glassbase** [recyclarr/recyclarr#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I keep receiving this to sync to my Radarr 
`HTTP error: Response could not be deserialized to JSON`

Slightly different config syncs to my 4k Radarr no problem. I am only using recyclarr to keep CFs in sync with Trash Guides. Not creating profiles, setting scores, etc

I noticed the other issues related to this error, users have size custom formats, which I also do. Maybe related?

### Expected Behavior

To sync :)

### Steps To Reproduce

1. `recyclarr sync -p`
2. Observe error

### Environment & Versions

```bash
- Operating System: Unraid
- Architecture: Linux 5.19.17-Unraid x86_64
- Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
- Recyclarr Build: see above
- Sonarr Version: n/a
- Radarr Version: 5.3.3.8523
```

### Recyclarr Log File(s)

[recyclarr_2024-01-26_15-37-34.verbose.log](https://github.com/recyclarr/recyclarr/files/14069210/recyclarr_2024-01-26_15-37-34.verbose.log)

### Configuration YAML

```YAML
radarr:
  Radarr:
    base_url: !secret radarr_url
    api_key: !secret radarr_apikey

    # Custom Format Configuration
    delete_old_custom_formats: false
    replace_existing_custom_formats: true

    custom_formats:

      - trash_ids:
          # HDR Formats
#          - 58d6a88f13e2db7f5059c41047876f00 # DV
#          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
#          - e23edd2482476e595fb990b12e7c609c # DV HDR10
#          - c53085ddbd027d9624b320627748612f # DV HDR10+
#          - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
#          - a3e19f8f627608af0211acd02bf89735 # DV SDR
#          - e61e28db95d22bedcadf030b8f156d96 # HDR
#          - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
#          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
#          - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
#          - 9364dd386c9b4a1100dde8264690add7 # HLG
#          - 08d6d8834ad9ec87b1dc7ec8148e7a1f # PQ

          # Audio Advanced #1
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS

          # Audio Advanced #2
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - 6ba9033150e7896bdc9ec4b44f2b230f # MP3
          - a061e2e700f81932daf888599f8a8273 # Opus
          - e7c2fcae07cbada050a0af3357491d7b # PCM

          # Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - f6ff65b3f4b464a79dcc75950fe20382 # CRAV
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX (new name for HBO Max)
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 6185878161f1e2eef9cd0641a0d09eae # IP (BBC iPlayer)
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
#          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE (Bravia Core)
#          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
#          - 917d1f2c845b2b466036b0cc2d7c72a3 # FOD (foreign)
#          - fbca986396c5e695ef7b2def3c755d01 # OViD
#          - bf7e73dd1d85b12cc527dc619761c840 # Pathe
#          - c2863d2a50c9acad1fb50e53ece60817 # STAN
#          - f1b0bae9bc222dab32c1b38b5a7a1088 # TVer
#          - 279bda7434fd9075786de274e6c3c202 # U-NEXT

          # Movie Versions
#          - 0f12c086e289cf966fa5948eac571f44 # Hybrid

          # UNWANTED
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 0a3f082873eb454bde444150b70253cc # Extras
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
#          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)

          # Optional
          - ae4cfaa9283a4f2150ac3da08e388723 # VP9 (new codec, low support)
          - cae4ca30163749b891686f95532519bd # AV1 (new codec, low support)
          - c465ccc73923871b3eb1802042331306 # Line/Mic Dubbed
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
#          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
#          - b17886cb4158d9fea189859409975758 # HDR10+ Boost

          # Misc
          - 4b900e171accbfb172729b63323ea8ca # Multi
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 2899d84dc9372de3408e6d8cc18e9666 # x264
          - 9170d55c319f4fe40da8711ba9d8050d # x265
```
