### ISSUE TITLE
Outdated code example in the documentation

### ISSUE THREAD

**Issue by ScribbleGhost** [recyclarr/recyclarr#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The example called "[Update as much as possible in both Sonarr and Radarr with a single config](https://recyclarr.dev/wiki/yaml/config-examples/#update-as-much-as-possible-in-both-sonarr-and-radarr-with-a-single-config)" seems to be out of date. It does not work with Sonarr 4.

### Expected Behavior

The code example should work with the newest version of Sonarr. That is Sonarr 4.x.x which is now out of beta and the recommended release.

### Steps To Reproduce

1. Copy the code from the example called "[Update as much as possible in both Sonarr and Radarr with a single config](https://recyclarr.dev/wiki/yaml/config-examples/#update-as-much-as-possible-in-both-sonarr-and-radarr-with-a-single-config)"
2. Paste the code in recyclarr.yml
3. Make sure you have a secrets.yml properly set up.
4. Run `recyclarr sync --preview`
5. You will get the error: `[ERR] Release profiles require Sonarr v3. Please use `custom_formats` instead or use the right version of Sonarr.`

### Environment & Versions

```bash
- Operating System: Microsoft Windows [Version 10.0.19044.3930]
- Architecture: x64
- Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
- Recyclarr Build: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
- Sonarr Version: 4.0.1.929
- Radarr Version: 5.2.6.8376
```

### Recyclarr Log File(s)

N/R

### Configuration YAML

```YAML
sonarr:
  sonarr_main:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_apikey
    quality_definition:
      type: series
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
        tags: [tv]

radarr:
  radarr_main:
    base_url: !secret radarr_url
    api_key: !secret radarr_apikey
    quality_definition:
      type: movie
      preferred_ratio: 0.5
```

### Sonarr / Radarr Logs

N/R
