### ISSUE TITLE
recyclarr sync - [ERR] Release profiles require Sonarr v3.

### ISSUE THREAD

**Issue by rr0ss0rr** [recyclarr/recyclarr#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Receiving the following on the initial sync

```
===========================================
Processing Radarr Server: [movies]
===========================================

[INF] Created 4 New Custom Formats
[INF] Total of 4 custom formats were synced
[INF] Processing Quality Definition: movie
[INF] Number of updated qualities: 14
[INF] Completed at 4/14/2024 3:09:34PM

===========================================
Processing Sonarr Server: [series]
===========================================

[ERR] Release profiles require Sonarr v3. Please use `custom_formats` instead or use the right version of Sonarr.
```
```
recyclarr --version
6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
```
```
Sonarr Version
4.0.4.1491
.NET
Yes (6.0.13)
Database
Sqlite 3.36.0
Database Migration
205
AppData Directory
/Users/richard/.config/Sonarr
Startup Directory
/Applications/Sonarr.app/Contents/MacOS
```

Thanks

### Expected Behavior

Not get the error

### Steps To Reproduce

`recyclarr sync`

### Environment & Versions

```bash
- Operating System: MacOS 14.4.1
- Architecture: x86
- Recyclarr Version:
- Recyclarr Build:
- Sonarr Version:
- Radarr Version:
```

### Recyclarr Log File(s)

[15:35:54 DBG] Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
[15:35:54 DBG] App Data Dir: /Users/richard/.config/recyclarr
[15:35:54 DBG] Config Templates Repo: Using Branch & Clone URL: master, https://github.com/recyclarr/config-templates.git
[15:35:54 DBG] Trash Guides Repo: Using Branch & Clone URL: master, https://github.com/TRaSH-Guides/Guides.git
[15:35:54 DBG] Config Templates Repo: Executing git command with args: ["status"]
[15:35:54 DBG] Config Templates Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/config-templates
[15:35:54 DBG] Trash Guides Repo: Executing git command with args: ["status"]
[15:35:54 DBG] Trash Guides Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/trash-guides
[15:35:54 DBG] Config Templates Repo: Command Output: On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[15:35:54 DBG] Trash Guides Repo: Command Output: On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[15:35:54 DBG] Config Templates Repo: Executing git command with args: ["remote","set-url","origin","https://github.com/recyclarr/config-templates.git"]
[15:35:54 DBG] Config Templates Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/config-templates
[15:35:54 DBG] Trash Guides Repo: Executing git command with args: ["remote","set-url","origin","https://github.com/TRaSH-Guides/Guides.git"]
[15:35:54 DBG] Trash Guides Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/trash-guides
[15:35:54 DBG] Config Templates Repo: Command Output: 
[15:35:54 DBG] Trash Guides Repo: Command Output: 
[15:35:54 DBG] Trash Guides Repo: Remote 'origin' set to https://github.com/TRaSH-Guides/Guides.git
[15:35:54 DBG] Config Templates Repo: Remote 'origin' set to https://github.com/recyclarr/config-templates.git
[15:35:54 DBG] Config Templates Repo: Executing git command with args: ["checkout","-f","master"]
[15:35:54 DBG] Config Templates Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/config-templates
[15:35:54 DBG] Trash Guides Repo: Executing git command with args: ["checkout","-f","master"]
[15:35:54 DBG] Trash Guides Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/trash-guides
[15:35:54 DBG] Config Templates Repo: Command Output: Your branch is up to date with 'origin/master'.
[15:35:54 DBG] Config Templates Repo: Executing git command with args: ["fetch","origin"]
[15:35:54 DBG] Config Templates Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/config-templates
[15:35:54 DBG] Trash Guides Repo: Command Output: Your branch is up to date with 'origin/master'.
[15:35:54 DBG] Trash Guides Repo: Executing git command with args: ["fetch","origin"]
[15:35:54 DBG] Trash Guides Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/trash-guides
[15:35:54 DBG] Trash Guides Repo: Command Output: 
[15:35:54 DBG] Config Templates Repo: Command Output: 
[15:35:54 DBG] Trash Guides Repo: Executing git command with args: ["reset","--hard","origin/master"]
[15:35:54 DBG] Config Templates Repo: Executing git command with args: ["reset","--hard","origin/master"]
[15:35:54 DBG] Config Templates Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/config-templates
[15:35:54 DBG] Trash Guides Repo: Using working directory: /Users/richard/.config/recyclarr/repositories/trash-guides
[15:35:54 DBG] Config Templates Repo: Command Output: HEAD is now at a89613b fix: Add French includes to include library (#76)
[15:35:54 DBG] Trash Guides Repo: Command Output: HEAD is now at dc82f90 update(imax-descriptions): language and descriptions around imax(e) (#1879)
[15:35:55 DBG] recyclarr.yml: Loading config file: /Users/richard/.config/recyclarr/recyclarr.yml
[15:35:55 DBG] Processing Sonarr server series
[15:35:55 DBG] HTTP Request: GET http://REDACTED:8989/api/v3/system/status
[15:35:55 DBG] HTTP Response: 200 GET http://REDACTED:8989/api/v3/system/status
[15:35:55 DBG] Sonarr Version: 4.0.4.1491
[15:35:55 ERR] Release profiles require Sonarr v3. Please use `custom_formats` instead or use the right version of Sonarr.
[15:35:55 DBG] Cleaning up logs using max files of 20

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://localhost:8989
    api_key: redacted

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    # Release profiles from the guide to sync to Sonarr v3 (Sonarr v4 does not use this!)
    # Use `recyclarr list release-profiles` for values you can put here.
    # https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/
    release_profiles:
      # Series
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
      # Anime (Uncomment below if you want it)
      #- trash_ids:
      #    - d428eda85af1df8904b4bbe4fc2f537c # Anime - First release profile
      #    - 6cd9e10bb5bb4c63d2d7cd3279924c7b # Anime - Second release profile

# Configuration specific to Radarr.
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: http://localhost:7878
    api_key: redacted

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - dc98083864ea246d05a42df0d05f81cc # x265 (720/1080p)

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.
        #quality_profiles:
        #  - name: Quality Profile 1
        #  - name: Quality Profile 2
        #    #score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
        #    #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```
