### ISSUE TITLE
`delete_old_custom_formats` not removing CFs after removing `include`s from conf

### ISSUE THREAD

**Issue by ftc2** [recyclarr/recyclarr#237]
### Observed Behavior

recyclarr did not remove any CFs it added despite `delete_old_custom_formats: true` and the relevant section of the conf being removed.

### Expected Behavior

recyclarr would remove the CFs it added, and i'd be left with only the one original CF that i had added manually.

### Steps To Reproduce

1. start with a radarr instance with a single CF (manually created in radarr). `SQP-5` QP does not exist yet.

2. run `recyclarr sync radarr` with:
```yaml
radarr:
  radarr_hq:
    base_url: !secret radarr_hq_url
    api_key: !secret radarr_hq_key
    quality_definition:
      type: sqp-uhd
    delete_old_custom_formats: true
    include:
      - template: radarr-custom-formats-sqp-5
      - template: radarr-quality-profile-sqp-5
```

output:
```
[INF] Created 80 New Custom Formats
[INF] Total of 80 custom formats were synced
[INF] Created 1 Profiles: ["SQP-5"]
[INF] A total of 1 profiles were synced. 1 contain quality changes and 1 contain updated scores
[INF] Processing Quality Definition: sqp-uhd
[INF] Number of updated qualities: 0
[INF] Completed at 04/18/2024 21:38:03
```

debug log:
[recyclarr_2024-04-18_21-38-00.debug.log](https://github.com/recyclarr/recyclarr/files/15032495/recyclarr_2024-04-18_21-38-00.debug.log)

3. run `recyclarr sync radarr` again with:
```yaml
radarr:
  radarr_hq:
    base_url: !secret radarr_hq_url
    api_key: !secret radarr_hq_key
    quality_definition:
      type: sqp-uhd
    delete_old_custom_formats: true
```

output:
```
[INF] Processing Quality Definition: sqp-uhd
[INF] Number of updated qualities: 0
[INF] Completed at 04/18/2024 21:39:26
```

debug log:
[recyclarr_2024-04-18_21-39-25.debug.log](https://github.com/recyclarr/recyclarr/files/15032497/recyclarr_2024-04-18_21-39-25.debug.log)

### Environment & Versions

```bash
- Operating System: fedora server fc39
- Architecture: x64
- Recyclarr Version: 6.0.2+Branch.tags-v6.0.2.Sha.5b163d9dc621f28624270e2543334d8ee8599d98
- Recyclarr Build: docker
- Radarr Version: 5.4.6.8723
```

**Comment by rcdailey** [comment]
Are you able to consistently reproduce this? If you add the include back, sync, remove, do another sync -- do you see those CFs appear but not disappear?

**Comment by ftc2** [comment]
yes ofc lol :)

reproduced once more to be sure:
```bash
docker compose run --rm recyclarr delete custom-formats radarr_hq --all

docker compose run --rm recyclarr sync radarr -i radarr_hq
# result: CFs were added by includes

# after editing conf to remove includes:
docker compose run --rm recyclarr sync radarr -i radarr_hq
result: CFs are still there
```

**Comment by ftc2** [comment]
complete config used just now

before:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

radarr:
  radarr_hq:
    base_url: !secret radarr_hq_url
    api_key: !secret radarr_hq_key
    delete_old_custom_formats: true
    include:
      - template: radarr-custom-formats-sqp-5
      - template: radarr-quality-profile-sqp-5
```

after:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

radarr:
  radarr_hq:
    base_url: !secret radarr_hq_url
    api_key: !secret radarr_hq_key
    delete_old_custom_formats: true
    # include:
    #   - template: radarr-custom-formats-sqp-5
    #   - template: radarr-quality-profile-sqp-5
```
