### ISSUE TITLE
Allow usage of additional custom repos for custom formats

### ISSUE THREAD

**Issue by nuxencs** [recyclarr/recyclarr#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Due to the nuisances of automating fork updates, I would like to be able to specify a custom repo (that is not a Guides fork) in the [`settings.yml`](https://recyclarr.dev/wiki/yaml/settings-reference/#repo-settings) to be able to sync additional custom formats that are not present in the Guides.

The new part in `settings.yml` would look something like this:

```yaml
repositories:
  custom:
    - clone_url: https://github.com/nuxen/my-cfs.git              
      clone_path: my_cfs # ends up in /config/repositories/my_cfs
      branch: master
```
