### ISSUE TITLE
Share custom formats with YML alias and insert

### ISSUE THREAD

**Issue by juanca** [recyclarr/recyclarr#251]
Hello. I was wondering if it would make sense to set up aliases on the provided templates to make them more reusable? For example, I have my own quality profile (named "Any") but I basically want the custom formats provided in non-anime templates. At the moment, it's pretty simple to copy and paste from the provided source files. However, I would like to ensure my own profile gets synced with any changes to the provided templates.

Something like:

```yml
sonarr:
  sonarr-v4:
    custom_formats:
      - quality_profiles:
          - name: Any
        trash_ids:
          << : *sonarr-v4-custom-formats-web-2160p # merge template cfs
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
```

which could be accomplished with something like:

```yml
custom_formats:
  - trash_ids: &sonarr-v4-custom-formats-web-2160p
      # Movie Versions
      - 570bc9ebecd92723d2d21500f4be314c # Remaster
      - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
      - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
      - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
      - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
      - 957d0f44b592285f26449575e8b1167e # Special Edition
      - eecf3a857724171f968a66cb5719e152 # IMAX
      - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

      # HQ Release Groups
      - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
      - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
      - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
      - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
      - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
      - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03

      # Misc
      - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
      - ae43b294509409a6a13919dedd4764c4 # Repack2

      # Unwanted
      - ed38b889b31be83fda192888e2286d83 # BR-DISK
      - 90a6f9a284dff5103f6346090e6280c8 # LQ
      - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
      - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
      - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
      - 0a3f082873eb454bde444150b70253cc # Extras

      # Streaming Services
      - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
      - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
      - 2a6039655313bf5dab1e43523b62c374 # MA
```

This could make the source files a bit more messy and have implications on how the resulting recyclarr YML gets generated -- so not sure if it is a good fit for the project.
