### ISSUE TITLE
recyclarr.yml configuration example returns error: [ERR] recyclarr.yml: Exception at line 34: While parsing a block collection, did not find expected '-' indicator.

### ISSUE THREAD

**Issue by leninsaccountant** [recyclarr/recyclarr#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have successfully created a recyclarr.yml file using the command `recyclarr config create`. I edited this with Notepad, and copied and pasted the example configuration file located at https://recyclarr.dev/wiki/yaml/config-examples/. I made sure to update Sonarr and Radarr `base_url` and `api-key`. This is what I have for the recyclarr.yml file (I have redacted my API keys):

```yml
sonarr:
  main:
    base_url: http://localhost:8989/
    api_key: REDACTED
    quality_definition:
      type: series
    custom_formats:
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
        quality_profiles:
          - name: WEB-1080p

radarr:
  main:
    base_url: http://localhost:7878/
    api_key: REDACTED
    quality_definition:
      type: movie
      preferred_ratio: 0.5
    custom_formats:
      - trash_ids:
        # HQ Release Groups
        - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
        - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
        - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
        - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
        - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
      quality_profiles:
        - name: HD`
```

However, when I save the .yml file and run `recyclarr sync`, I receive the following error: 

`[ERR] recyclarr.yml: Exception at line 34: While parsing a block collection, did not find expected '-' indicator.
[ERR] recyclarr.yml: Due to previous exception, this config will be skipped`

### Expected Behavior

`recyclarr sync` should successfully sync.

### Steps To Reproduce

Fresh download of recyclarr on Windows 11

### Environment & Versions

```bash
- Operating System: Windows 11
- Architecture: 64-bit / x64
- Recyclarr Version: 7.0.0
- Recyclarr Build: .exe executable
- Sonarr Version: 4.0.5.1710
- Radarr Version: 5.7.0.8882
```

### Recyclarr Log File(s)

[recyclarr_2024-06-29_09-22-51.debug.log](https://github.com/user-attachments/files/16039365/recyclarr_2024-06-29_09-22-51.debug.log)

### Configuration YAML

```YAML
`sonarr:
  main:
    base_url: http://localhost:8989/
    api_key: REDACTED
    quality_definition:
      type: series
    custom_formats:
      - trash_ids:
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
        quality_profiles:
          - name: WEB-1080p

radarr:
  main:
    base_url: http://localhost:7878/
    api_key: REDACTED
    quality_definition:
      type: movie
      preferred_ratio: 0.5
    custom_formats:
      - trash_ids:
        # HQ Release Groups
        - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
        - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
        - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
        - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
        - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
        - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
      quality_profiles:
        - name: HD`
```
