### ISSUE TITLE
Add support for Docker Secrets

### ISSUE THREAD

**Issue by andrewvaughan** [recyclarr/recyclarr#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Docker and Docker Compose have built-in secrets management, which provides significantly-more flexible, instance-based secrets management than the current `secrets.yml` construct:

https://docs.docker.com/compose/compose-file/09-secrets/

Given the dynamic nature of recyclarr, the standard `_FILE` pattern Docker recommends to append to environment variables won't work; however, I believe a unique solution can be added.

Currently, the [URL precedence](https://recyclarr.dev/wiki/yaml/secrets-reference/#implicit-key-url-precedence) is in the order:

1. `recyclarr.yml`
2. `secrets.yml`

I recommend keeping this precedence and adding one more; namely, a file loaded by an environment variable `SECRETS_FILE`. An example Docker Compose configuration might be:

```yaml
services:

  recyclarr:
    
    # ... normal configuration
    
    secrets:
      - "recyclarr-keys"
     
    environment:
      SECRETS_FILE: "/run/secrets/recyclarr-keys"  # This will be the YAML file, regardless of extension

secrets:
  recyclarr-keys:
    file: "./recyclarr/secrets.yml"
```

This file can maintains the same `secrets.yml` schema currently in use, it would simply allow for these secrets to now be loaded through the Docker Secrets mechanism. This is entirely backwards compatible, if implemented in this way.

I believe this would also be a simple implementation, as there would simply be a tertiary lookup to see if the `SECRETS_FILE` environment variable is set, and, if so, loading that file in using normal constructs.

**Comment by andrewvaughan** [comment]
Another idea may be to extend the existing Environment Variables functionality:

https://recyclarr.dev/wiki/yaml/env-vars/

This would actually add even more flexibility (you could even support both patterns). For example, where this loads from the environment variable directly:

```yml
load_from_env: !env_var MY_ENV_VAR my_default_value
```

An additional command could be added for indirect environment loading (that is, where the environment variable contains a filename that should be loaded):

```yml
load_from_env: !env_var_file MY_ENV_SECRET my_default_value
```

I actually like this method more, personally, as it adds the most amount of flexibility for users by allow all of their secrets to be managed explicitly and separately, as Docker Secrets are intended.

This would, for example, give admins the ability to give some people access to, say, Radarr secrets, while other people access to Sonarr secrets. Or would allow for complex multi-instance management.

**Comment by rcdailey** [comment]
Hi Andrew and thank you for the very detailed, well thought-out enhancement request. This statement at the start of your OP stood out to me:

> significantly-more flexible

I think claims like this, especially within the context of a feature request, need to be persuasive, logical, objective, and detailed. Could you take some more time to describe what _specific_ additional flexibility this offers over the current solution? Remember, you're trying to convince developers to spend their free time on this, given an already-large backlog. Without this additional detail, it'll be challenging to prioritize this.

I want you to know I'm not picking on you here but I already have a lot to do and it'll take some convincing to make me understand exactly what benefits you see over the current solutions. Secrets and env vars already add a layer of overhead that's complicated for most users I think, and to continue to add more flavors of this just to satisfy specific tastes isn't good UX, IMO. 

Your answer is also a good opportunity to teach me and others about Docker secrets and how they are relevant here. At the moment, I'm not convinced that this kind of information belongs in any docker configuration; it's purely an application concern, in my view. While I use the word "secrets" that's probably a bit of a misnomer since they're really just a mechanism to split configuration.

I look forward to your response! Thanks again for the feedback.

**Comment by andrewvaughan** [comment]
Sure -

For a long time the secrets file pattern has been used, even by Docker. In that case, you would create a `.env` file and control who had access to it with file permissions. They did this for the same reason you likely went with the `secrets.yml` pattern - to allow users to prevent secrets from inadvertently being committed into repositories. What was found is that is did little to help with day-to-day operational infosec with managing UAC.

Additionally, Docker Secrets add significantly more security than `.env` or `.yml` files, for instance, from the Docker [documentation](https://docs.docker.com/engine/swarm/secrets/):

> Secrets are encrypted during transit and at rest in a Docker [Compose]. A given secret is only accessible to those services which have been granted explicit access to it, and only while those service tasks are running.

As opposed to file loading, where anyone with access to the container can enter it and view the `secrets.yml` file.

You can also:

> use Docker secrets to centrally manage this data and securely transmit it to only those containers that need access to it.

For the latter quickly arose because you had different individuals with different access levels in the secret management arena. Having all of your secrets in a single file leaves you with one single option: giving someone access to _ALL_ your API keys to every admin on the system or none of them. You can imagine operations where folks who may want to manage UAC at a finer level of control than that with multiple instances of radarr/sonarr/etc.

So Docker introduced the `_FILES` pattern for secrets as a backwards-compatible way to granularly control who has access to which files by separating each of these variables into their own, independent files which can be individually managed. In nearly every project I've submitted a PR to for this, it's been less than 10 lines of code to override environment variables (usually identifying that the `_FILE` variable is set and overriding any environment variable with the contents of the file).

So I think this is less of an "if" but "when" the recyclarr project will meet the latest standard for secrets management (I say latest, but this has been pretty standard since AWS introduced IAM). If the recommended method to run recyclarr is through Docker (I think I saw this in the docs?) it makes sense to use their secrets-management best-practices, as well.

More information here:
https://docs.docker.com/compose/use-secrets/

**Comment by rcdailey** [comment]
Thanks for the additional clarification. 

It sounds like all you're really asking for is to be able to specify the location to a custom `secrets.yml` file. In your case, you'd point it to the mounted file provided by Docker's secrets attribute. However, Recyclarr wouldn't be aware that this is anything other than a normal YAML file.

If I understand you correctly, I think that's a perfectly reasonable request, and it's also useful outside of Docker (which is another use case I need to consider).

I could support configuring a custom secrets location in two ways:

1. Modify the existing secrets location to be a default added to `settings.yml`, e.g.
   ```yml
   secrets_file: secrets.yml # Relative paths start at the app data directory
   ```

2. Add a new `RECYCLARR_SECRETS_FILE` env var that allows that path to be provided.

**Comment by rcdailey** [comment]
@andrewvaughan Have you had spare time to review & respond to my last comment? Thanks again for your interest & time.

**Comment by Cheezzhead** [comment]
Not OP, but I'd like to add my 2 cents.

First off, there is a secure solution (at least as secure as docker secrets) that hasn't been mentioned before that I think will be satisfactory for most people, which is to simply mount the `secrets.yml` file as a docker secret:

```
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    # ...
    secrets:
      - source: recyclarr_secrets_file
        target: /config/secrets.yml
    volumes:
      - ${DOCKER_CONF_DIR}/recyclarr:/config

secrets:
  recyclarr_secrets_file:
    file: ./recyclarr/secrets.yml
```

Secrets are mounted to `/run/secrets/<secret_name>` by default, but docker compose provides a [long syntax](https://docs.docker.com/reference/compose-file/services/#long-syntax-4) which allows us to define the target location.

**However**, this is not secure because the `/config` folder (which `secrets.yml` **must** be placed into) is usually mounted to the host system (this is also recommended in the docs). Which means that the `secret.yml` file is placed into that folder and therefore copied to the host volume (in the example above, it will be copied to `${DOCKER_CONF_DIR}/recyclarr/secrets.yml` upon starting). So any security applied to the file is practically gone.

There are 2 ways to solve this:
 - Don't mount the `/config` directory to the host, but to a named docker volume instead. I would argue this is good practice regardless of the current topic, however it's not what the documentation recommends and it's also not what most people are used to; I think for inexperienced docker users, mounting the folder to the host should remain the easiest and most straight-forward method of running the app.
 - Allow users to specify the location of their secrets folder, i.e. by using an environment variable or command argument. This is by far the easiest solution IMO; in fact one of the first things that stood out to me when reading Recyclarr's logs was why all of the YAML files **had** to be placed in a specific location without any customization.

With the second option, the above could be simplified to:

```
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    # ...
    secrets: [recyclarr_secrets_file]
    environment:
      RECYCLARR_SECRETS_FILE: /run/secrets/recyclarr_secrets_file
    volumes:
      - ${DOCKER_CONF_DIR}/recyclarr:/config

secrets:
  recyclarr_secrets_file:
    file: ./recyclarr/secrets.yml
```

-------------

Finally, regarding actual docker secrets. Apart from the aforementioned reasons wrt sharing secrets, I would add that most other docker images provide support for reading environment variables directly from files. It's a standard that's recommended by Docker nowadays (to the point that they use it in their official images) and for Recyclarr to properly participate in the ecosystem I think it's necessary to add support for this.

As an example for how we can benefit today from granular secrets, consider the following Sonarr setup:
```
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # ...
    secrets: [postgres_pass, sonarr_api_key]
    environment:
      FILE__SONARR__AUTH__APIKEY: /run/secrets/sonarr_api_key
```

I have the Sonarr API key stored as a secure file on my host system. Not only sonarr uses this secret, but also auxiliary apps like Kometa (and potentially other apps in the future). If I have to use the `secrets.yml` file for Recyclarr - and only Recyclarr - then my API key will be stored in 2 different places. If the key ever changes, I need to not only update my `sonarr_api_key` secret, but *also* my Recyclarr secrets file. This is inconvenient and introduces room for error - 2 years from now I might not remember that the API key is also stored in `secrets.yml`.
