### ISSUE TITLE
Merging Configs 409 error constraint failed

### ISSUE THREAD

**Issue by backstab5983** [recyclarr/recyclarr#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After adding the Anime config to a radarr instance, recyclarr cannot sync and throws a 409 error.

### Expected Behavior

Should sync fine without complaining.

### Steps To Reproduce

1. Try to merge two configs as in the .yaml provided
2. Try to `recyclarr sync radarr`
3. See error in console

### Environment & Versions

```bash
- Operating System: Ubuntu 22.04.4 LTS
- Architecture: x64
- Recyclarr Version: v7.0.0
- Recyclarr Build: Docker
- Sonarr Version: 4.0.6.1805
- Radarr Version: 5.7.0.8882
```

### Recyclarr Log File(s)

[recyclarr_2024-07-05_05-18-20.debug.log](https://github.com/user-attachments/files/16109189/recyclarr_2024-07-05_05-18-20.debug.log)
[recyclarr_2024-07-05_05-18-20.verbose.log](https://github.com/user-attachments/files/16109190/recyclarr_2024-07-05_05-18-20.verbose.log)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

###################################################################################################
# Recyclarr Configuration Template: WEB-1080p (V4)                                                #
# Updated: 2023-12-30                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
# This config file is for use with Sonarr V4 only                                                 #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  web-1080p-v4:
    base_url: REDACTED
    api_key: REDACTED
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
           - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
           - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
           - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
           - 06d66ab109d4d2eddb2794d21526d140 # Retags
           - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        quality_profiles:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          #   - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          # quality_profiles:
          #  - name: WEB-1080p
          #   score: 0
               #  - trash_ids:
               # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        quality_profiles:
          - name: WEB-1080p
    quality_profiles:
      - name: WEB-1080p
        reset_unmatched_scores:
          enabled: true
          except:
            - WEBDL Boost # Don't overwrite custom edit to trump WEBRip
  anime-sonarr-v4:
    base_url: REDACTED
    api_key: REDACTED

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired
###################################################################################################
# Recyclarr Configuration Template: SQP-1 (1080p)                                                 #
# Updated: 2023-12-30                                                                             #
# Documentation: https://recyclarr.dev                                                            #
# Note: If you are using multiple profiles in a single instance, please read the following        #
# documentation about file merging:                                                               #
# https://recyclarr.dev/wiki/yaml/config-examples/#merge-single-instance                          #
###################################################################################################

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
radarr:
  sqp-1-1080p:
    base_url: REDACTED
    api_key: REDACTED
    delete_old_custom_formats: true
    quality_profiles:
      - name: SQP-1 (1080p)
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEB|Bluray-1080p
          until_score: 10000
        min_format_score: 1000
        score_set: sqp-1-1080p
        quality_sort: top
        qualities:
          - name: WEB|Bluray-1080p
            qualities:
              - WEBDL-1080p
              - WEBRip-1080p
              - Bluray-1080p
          - name: WEB|Bluray-720p
            qualities:
              - WEBDL-720p
              - WEBRip-720p
              - Bluray-720p

    include:
      # Comment out any of the following includes to disable them
      #      - template: radarr-quality-definition-sqp-streaming
    #  - template: radarr-quality-profile-sqp-1-1080p
      - template: radarr-custom-formats-sqp-1-1080p
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      - trash_ids:
          - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 0
      - trash_ids:
          - c2998bd0d90ed5621d8df281e839436e # DD
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 0
      - trash_ids:
          - 185f1dd7264c4562b9022d963ac37424 # DD+
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 10
      - trash_ids:
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 12
      - trash_ids:
          - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hallowed
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 0
      - trash_ids:
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 15
      - trash_ids:
          - eecf3a857724171f968a66cb5719e152 # IMAX
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 126
      - trash_ids:
          - 820b09bb9acbfde9c35c71e0e565dad8 # 1080p
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 0
      - trash_ids:
          - b2be17d608fc88818940cd1833b0b24c # 720p
        quality_profiles:
          - name: SQP-1 (1080p)
            score: 0

      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 0 # Adjust scoring as desired

      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        quality_profiles:
          - name: Remux-1080p - Anime
            score: 2000 # Adjust scoring as desired  

      - trash_ids:
      # Uncomment the next line if you prefer WEBDL with IMAX Enhanced to BHDStudio
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
      # Optional - uncomment any of the following if you want them added to your profile
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
      #   - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        quality_profiles:
          - name: SQP-1 (1080p)
```
