### ISSUE TITLE
Dockerfile /config permissions issue when running as any user except root and UID 1000.

### ISSUE THREAD

**Issue by CarlLusty** [recyclarr/recyclarr#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When supplying a non-root user to run the container, and when not mounting all of /config, there can be insufficient permissions on /config for recyclarr to run.

Obviously, when mounting all of /config into your host there is little that the Dockerfile can do about the permissions as /config is essentially replaced at runtime.
But, what if all I want to do is mount my configuration file into /config? This is where the issue is.
The issue is also present if I mount nothing. Related to #111 

Currently: 
https://github.com/recyclarr/recyclarr/blob/8f908556deb70d64b2a6fec90ffe4adca3f4347e/Dockerfile#L45
The Dockerfile uses root to create /config and then assigns ownership to UID 1000.
This gives UID 1000 write access to /config.

If I run recyclarr using UID 1000, it works fine.
If I run as UID 1001, that user does not have permission to write to /config and recyclarr errors.

# Examples:
Testing with: 8f908556deb70d64b2a6fec90ffe4adca3f4347e
I added the following to the entrypoint script:
```
ls -la /
id
```

## Default:
```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
#    user: 1001:1001
#    volumes:
#      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```
**Runs**
Config Perms: drwxr-xr-x    2 1000     1000          4096 Jul 11 22:52 config
id: uid=1000 gid=1000 groups=1000

## Change user:
```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1001:1001
#    volumes:
#      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```
**Fails: Permission denied in /config**
Config Perms: drwxr-xr-x    2 1000     1000          4096 Jul 11 22:55 config
id: uid=1001 gid=1001 groups=1001

## Mount my config file:
```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1001:1001
    volumes:
      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```
**Fails: Permission denied in /config**
Config Perms: drwxr-xr-x    2 1000     1000          4096 Jul 11 22:57 config
id: uid=1001 gid=1001 groups=1001

## Specifying user 1000 and mounting just my config file:
```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1000:1000
    volumes:
      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```
**Runs**
Config Perms: drwxr-xr-x    2 1000     1000          4096 Jul 11 23:02 config
id: uid=1000 gid=1000 groups=1000

### Expected Behavior

Per the installation instructions:
> "user
Optional User and Group ID you want to run the container as. Recyclarr will run using this UID:GID and any files it creates in your /config volume will also be owned by this user and group. The default for this, if not specified, is 1000:1000." - https://recyclarr.dev/wiki/installation/docker/

Any specified runtime user, either set through the compose user flag or --user, needs permission to write to /config.

If someone mounts all of /config somewhere, those permissions are up to them.
If /config is not mounted elsewhere, the container should still be able to run.

### Steps To Reproduce

See examples.

### Environment & Versions

```bash
Not that relevant but:
- Operating System: Debian GNU/Linux 12 (bookworm)
- Architecture: x86_64
- Recyclarr: 8f908556deb70d64b2a6fec90ffe4adca3f4347e
```

### Recyclarr Log File(s)

NA

### Configuration YAML

```YAML
sonarr:
  web-1080p-v4:
    base_url: foo
    api_key: foo

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
```

**Comment by rcdailey** [comment]
Thanks for the report.

Sounds like there's a couple of things to address here.

First of all, I'll say that the documentation you quoted could definitely be improved. It does seem to imply that file permissions follow whatever user and group you specify; which simply isn't true. It doesn't manipulate permissions when you change the UID/GID; as you correctly indicated, that is up to the user to do.

Secondly, I want to address how you're mounting volumes in the container. I do not support "partial mounting". You must mount the whole `/config` directory. There's several reasons for that:

1. As you observed, if you don't mount to the target `/config` then you run into permission users when using a UID:GID other than `1000:1000`. Even though the file *inside* that path is accessible (i.e. the correct UID), Recyclarr can never reach it because the ownership on `/config` itself are at their default, which you have no way of changing. And because the container is rootless, it can't fix it for you.
2. There's several other files and directories under `/config` that are important to be retained between runs. The `/config/cache` directory is one of the more important ones out of a few others. Ultimately, it's much easier to just map `/config` to a volume. In the official recyclarr container, I do not support partial mounting as you have done.

What are you trying to achieve? Why do you want only 1 file mounted in the volume instead of mapping to `/config`? It seems like you might be making this more difficult for yourself. I certainly am not seeing a bug so far.

**Comment by CarlLusty** [comment]
Thanks for taking the time.

I agree with your first point about documentation.
The second is a little more complex. In my examples above, the containers did still mount all of '/config'. My compose file did not specify a bind mount or named volume for '/config', as such, an anonymous volume is created automatically. The VOLUME command in the Dockerfile ensures it.

You are right that I was not retaining anything between runs. I was treating the entire thing as a one-shot method of running 'sync', with a mounted config file. I will take your word that there are benefits to retaining the data in '/config' and I will use a named volume to store it. 

When using a volume, the permissions changes (chown) in the Dockerfile for '/config' persist. With a bind mount things are different. Let's focus on using a volume for now. Let's also not worry about the configuration file for now.
Let's just see if we can start recyclarr, with a different user, a named volume mount for '/config', and the right permissions to write in '/config'.

### Example 5: Change user, use a named volume for '/config'.
Command:  ```docker compose run recyclarr sync sonarr --preview --debug```
Compose: 
```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1001:1001
    volumes:
      - recyclarr-config:/config
    environment:
      - TZ=America/Santiago
volumes:
  recyclarr-config:
```
**Fails: Permission denied in /config**
Config Perms: drwxr-xr-x    2 1000     1000          4096 Jul 13 02:01 config
id: uid=1001 gid=1001 groups=1001

### Issue
Our user, UID 1001, does not own '/config' and does not have write access to '/config'.

## In the dockerfile:
- root creates '/config', as a result, the permissions on '/config' are 755 (rwxr-xr-x).
- Ownership of '/config' is changed to UID 1000.

### When running as UID 1001 (or any user not root or UID 1000):
- UID 1001 is not the owner of '/config'.
- No one, other than the owner, has write permissions to '/config'.
- When UID 1001 starts recyclarr, it crashes when attempting to write into '/config'.

### When running as UID 1000:
- UID 1000 owns '/config'.
- '/config' owner has write permission.
- Recyclarr can run and write to '/config' as needed.


## Proposed Solution: Give other users write access to '/config' in the Dockerfile.

Dockerfile:
```
-    mkdir -p /config && chown 1000:1000 /config;
+    mkdir -p /config && chown 1000:1000 /config && chmod 757 /config;
```

A chmod 777 or 757 on '/config' would allow other container UIDs to write there.

### Caviat:
This only addresses the permission issue for volumes, it changes nothing if '/config' is mounted using a bind mount.

**Comment by rcdailey** [comment]
> My compose file did not specify a bind mount or named volume for '/config', as such, an anonymous volume is created automatically. The VOLUME command in the Dockerfile ensures it.

I appreciate you calling this out. I should have clarified: I'm only referring to the scenarios where you do a "partial mount", that is, you do not mount a target for `/config` explicitly but rather some path under it. I understand the "anonymous volume" is created in the case you do not specify *any* bind mounts; that wasn't the specific scenario I was interested in addressing, though. 

> When using a volume, the permissions changes (chown) in the Dockerfile for '/config' persist. With a bind mount things are different. Let's focus on using a volume for now. Let's also not worry about the configuration file for now. Let's just see if we can start recyclarr, with a different user, a named volume mount for '/config', and the right permissions to write in '/config'.

I forgot to address this scenario from your original post -- I apologize. I also intended to point out that specifying a user for the container when there are no bind mounts doesn't make much sense. As far as I'm concerned, the only real benefit to specifying a custom UID/GID is to ensure continuity of ownership between the host and the container filesystems. If you're using actual volumes instead of bind mounts, it doesn't really matter what the file permissions are inside of that volume since the container has full ownership of it. 

In this scenario, why do you need a custom UID/GID?

This takes me back to the question I had at the end of my last reply, which you have yet to answer:

> What are you trying to achieve?

Frankly, I'm not interested in solutions without fully understanding the context. I need to understand why you're trying to do some of these things.

**Comment by CarlLusty** [comment]
> I'm only referring to the scenarios where you do a "partial mount", that is, you do not mount a target for /config explicitly but rather some path under it. I understand the "anonymous volume" is created in the case you do not specify any bind mounts or volume mapping; that wasn't the specific scenario I was interested in addressing, though.

I see your concern, this may be a slight misunderstanding regarding volume creation. In all of the above examples, a volume for '/config' is created, this is regardless of any other mounts that are specified. 
Even in the examples where I was bind mounting '/config/recyclarr.yml', a volume is still created for '/config'.
That said, you do not need to take my word for it, let's inspect the container mounts and see:

<details>
<summary>Container mounts for each example...</summary>

### Test 'compose1', listed above as: 'Default:':
<details>
<summary>Compose file...</summary>

```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
#    user: 1001:1001
#    volumes:
#      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```

</details>

<details>
<summary>Test commands...</summary>

```
mkdir ./testing_dir
cp compose1.yaml ./testing_dir/compose.yaml
cd ./testing_dir && ln -s ../../recyclarr
cd ./testing_dir && docker compose run recyclarr --help > /dev/null
rm -rf ./testing_dir
```

</details>

Container mounts:

```
[
  {
    "Type": "volume",
    "Name": "12b862e3ea1bde5e6694c1667ca5b7bbff5f22efe2a994f04c31aff2f606fd89",
    "Source": "/var/lib/docker/volumes/12b862e3ea1bde5e6694c1667ca5b7bbff5f22efe2a994f04c31aff2f606fd89/_data",
    "Destination": "/config",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```


### Test 'compose2', listed above as: 'Change user:':
<details>
<summary>Compose file...</summary>

```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1001:1001
#    volumes:
#      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```

</details>

<details>
<summary>Test commands...</summary>

```
mkdir ./testing_dir
cp compose2.yaml ./testing_dir/compose.yaml
cd ./testing_dir && ln -s ../../recyclarr
cd ./testing_dir && docker compose run recyclarr --help > /dev/null
rm -rf ./testing_dir
```

</details>

Container mounts:

```
[
  {
    "Type": "volume",
    "Name": "85f83065fe24ca76f993b03c16d9628af679611eac65cb5d6169b7bcca3eccc5",
    "Source": "/var/lib/docker/volumes/85f83065fe24ca76f993b03c16d9628af679611eac65cb5d6169b7bcca3eccc5/_data",
    "Destination": "/config",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```


### Test 'compose3', listed above as: 'Mount my config file:':
<details>
<summary>Compose file...</summary>

```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1001:1001
    volumes:
      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```

</details>

<details>
<summary>Test commands...</summary>

```
mkdir ./testing_dir
cp compose3.yaml ./testing_dir/compose.yaml
cd ./testing_dir && ln -s ../../recyclarr
cd ./testing_dir && docker compose run recyclarr --help > /dev/null
rm -rf ./testing_dir
```

</details>

Container mounts:

```
[
  {
    "Type": "volume",
    "Name": "210bf245372c04e960cc9ea0747bb5d0f0c9b8be663c562d9adf18e39faa119b",
    "Source": "/var/lib/docker/volumes/210bf245372c04e960cc9ea0747bb5d0f0c9b8be663c562d9adf18e39faa119b/_data",
    "Destination": "/config",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
  {
    "Type": "bind",
    "Source": "/XXXX/volTest/testing_dir/config.yml",
    "Destination": "/config/recyclarr.yml",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  }
]
```


### Test 'compose4', listed above as: 'Specifying user 1000 and mounting just my config file:':
<details>
<summary>Compose file...</summary>

```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1000:1000
    volumes:
      - ./config.yml:/config/recyclarr.yml:ro
    environment:
      - TZ=America/Santiago
```

</details>

<details>
<summary>Test commands...</summary>

```
mkdir ./testing_dir
cp compose4.yaml ./testing_dir/compose.yaml
cd ./testing_dir && ln -s ../../recyclarr
cd ./testing_dir && docker compose run recyclarr --help > /dev/null
rm -rf ./testing_dir
```

</details>

Container mounts:

```
[
  {
    "Type": "bind",
    "Source": "/XXXX/volTest/testing_dir/config.yml",
    "Destination": "/config/recyclarr.yml",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  },
  {
    "Type": "volume",
    "Name": "fac26ab1ab6faa1093d8a2db7260c0e19b737d095755b1c07470061c11a9f2e7",
    "Source": "/var/lib/docker/volumes/fac26ab1ab6faa1093d8a2db7260c0e19b737d095755b1c07470061c11a9f2e7/_data",
    "Destination": "/config",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```


### Test 'compose5', listed above as: 'Example 5: Change user, use a named volume for /config.':
<details>
<summary>Compose file...</summary>

```
services:
  recyclarr:
    container_name: recyclarr
    build: recyclarr/.
    user: 1001:1001
    volumes:
      - recyclarr-config:/config
    environment:
      - TZ=America/Santiago
volumes:
  recyclarr-config:
```

</details>

<details>
<summary>Test commands...</summary>

```
mkdir ./testing_dir
cp compose5.yaml ./testing_dir/compose.yaml
cd ./testing_dir && ln -s ../../recyclarr
cd ./testing_dir && docker compose run recyclarr --help > /dev/null
[+] Creating 1/0
 ✔ Volume "testing_dir_recyclarr-config"  Created0.0s 
rm -rf ./testing_dir
```

</details>

Container mounts:

```
[
  {
    "Type": "volume",
    "Name": "testing_dir_recyclarr-config",
    "Source": "/var/lib/docker/volumes/testing_dir_recyclarr-config/_data",
    "Destination": "/config",
    "Driver": "local",
    "Mode": "z",
    "RW": true,
    "Propagation": ""
  }
]
```
</details>

> specifying a user for the container when there are no bind mounts doesn't make much sense. As far as I'm concerned, the only real benefit to specifying a custom UID/GID is to ensure continuity of ownership between the host and the container filesystems. If you're using actual volumes instead of bind mounts, it doesn't really matter what the file permissions are inside of that volume since the container has full ownership of it.

I believe the potential cause of the issue here might be linked to the last part of your statement about container ownership of volumes. It seems to imply that containers have sole access to 'their' volumes. Please correct me if I have misunderstood your point.

To be clear, with Docker, containers do not own volumes. Docker creates and manages volumes, and these volumes can be mounted into multiple containers concurrently. See https://docs.docker.com/storage/#volumes for more details.

In general, I believe the same argument you make for permissions management between the host and a container when using bind mounts also applies to volumes shared between multiple containers.

> In this scenario, why do you need a custom UID/GID?
>
> This takes me back to the question I had at the end of my last reply, which you have yet to answer:
> 
> > What are you trying to achieve?

I am configuring all of my containers to run as distinct non-root users. I have multiple reasons for this approach, including file permission management, process monitoring, and security. There are many discussions that could be had over the merits and frankly the detriments of doing this, but I do not think they are all that relevant to this issue.

At the end of the day, my goal is to run this project with a non-root user that I specify. This capability is documented as an available feature, but based on the examples above, I believe there is an issue that needs to be addressed.

Cheers,
Carl
