### ISSUE TITLE
Sync fails when a size CF has a decimal.

### ISSUE THREAD

**Issue by ghost** [recyclarr/recyclarr#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sync fails when radarr has a size custom format with a decimal place.

### Expected Behavior

Should sync as normal.

### Steps To Reproduce

1. Add a size custom format to radarr with a decimal place. I used min 10.1 max 20. (also tried min 10 max 20.1)
2. Sync

### Environment & Versions

```bash
- Operating System: unRAID
- Architecture: x64
- Recyclarr Version: v7.2.1
- Recyclarr Build: Docker
- Sonarr Version: 4.0.8.1874
- Radarr Version: 5.8.3.8933
```

### Recyclarr Log File(s)

[recyclarr_2024-08-27_00-00-00.verbose.log](https://github.com/user-attachments/files/16754588/recyclarr_2024-08-27_00-00-00.verbose.log)
[recyclarr_2024-08-27_00-00-00.debug.log](https://github.com/user-attachments/files/16754589/recyclarr_2024-08-27_00-00-00.debug.log)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  series:
    base_url: http://sonar:8989
    api_key: xxxxxxxxxx

    quality_profiles:
      - name: WEB-1080p
        reset_unmatched_scores:
          # enabled: true     #is included in the template just here for ref
           except:           # excludes these custom formats from having score changed
            - magicstar
            - Language Not Original
      - name: WEB-2160p
        reset_unmatched_scores:
           except:
            - magicstar
            - Language Not Original
    include:
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
    delete_old_custom_formats: false # Deletes any custom formats that have been removed from this file. Won't touch custom formats I've added manually to radarr/sonarr
    replace_existing_custom_formats: true # syncs the guides custom formats and overides any i've made myself if they have the same name

    custom_formats:
      - trash_ids:
           - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
           - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p 
      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
           - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
            score: 0
      #    - name: WEB-2160p   # don't use this for 4k but can be applied to it so leaving for ref
      - trash_ids:
           - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p
      #    - name: WEB-2160p    # don't use this for 4k but can be applied to it so leaving for ref
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
           - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          # HDR10+ Boost - Uncomment the next two lines if any of your devices DO support HDR10+
           - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
           - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          # - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
           - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
        assign_scores_to:
          - name: Anime
            score: 199
          - name: Remux-1080p - Anime
            score: 250
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: Anime
            score: 0
          - name: Remux-1080p - Anime
            score: 0
      - trash_ids:
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Anime
            score: -100
          - name: Remux-1080p - Anime
            score: 0


# Configuration specific to Radarr.
radarr:
  movies:
    base_url: http://radar:7878
    api_key: xxxxxxxxxxxxxxx
    
    quality_profiles:
      - name: HD Bluray + WEB
        reset_unmatched_scores:
           except:        
            - Black & White Versions
            - Language Not Original
        min_format_score: 165
      - name: UHD Bluray + WEB
        reset_unmatched_scores:
           except:           
            - Black & White Versions
            - Language Not Original
        min_format_score: 165
      - name: SQP-1 (1080p)
        reset_unmatched_scores:
           except:       
            - Black & White Versions
            - Language Not Original
        min_format_score: 165
      - name: SQP-1 (2160p)
        reset_unmatched_scores:
           except:  
            - Black & White Versions
            - Language Not Original
        min_format_score: 165
      - name: SQP-2
        reset_unmatched_scores:
           except:         
            - Black & White Versions
            - Language Not Original
      - name: SQP-3
        reset_unmatched_scores:
           except:      
            - Black & White Versions
            - Language Not Original
      - name: SQP-4
        reset_unmatched_scores:
           except:    
            - Black & White Versions
            - Language Not Original
      - name: SQP-5
        reset_unmatched_scores:
           except:      
            - Black & White Versions
            - Language Not Original
      - name: Remux-1080p - Anime
        reset_unmatched_scores:
           except:    
            - magicstar
            - Language Not Original
        upgrade:
     #     allowed: true
       #   until_quality: WEB 1080p
          until_score: 20000
     #   min_format_score: 0
    include:
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web
      - template: radarr-quality-profile-sqp-1-1080p
      - template: radarr-custom-formats-sqp-1-1080p
      - template: radarr-quality-profile-sqp-1-2160p-default
      - template: radarr-custom-formats-sqp-1-2160p
      - template: radarr-quality-profile-sqp-2
      - template: radarr-custom-formats-sqp-2
      - template: radarr-quality-profile-sqp-3
      - template: radarr-custom-formats-sqp-3
      - template: radarr-quality-profile-sqp-4
      - template: radarr-custom-formats-sqp-4
      - template: radarr-quality-profile-sqp-5
      - template: radarr-custom-formats-sqp-5
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
    delete_old_custom_formats: false # Deletes any custom formats that have been removed from this file. Won't touch custom formats I've added manually to radarr/sonarr
    replace_existing_custom_formats: true # syncs the guides custom formats and overides any i've made myself if they have the same name

    custom_formats:
      - trash_ids:
           - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
           - 2f22d89048b01681dde8afe203bf2e95 # DTS X
           - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
           - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
           - 3cafb66171b47f226146a0770576870f # TrueHD
           - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
           - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
           - e7c2fcae07cbada050a0af3357491d7b # PCM
           - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
           - 185f1dd7264c4562b9022d963ac37424 # DD+
           - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
           - 1c1a4c5e823891c75bc50380a6866f73 # DTS
           - 240770601cc226190c367ef59aba7463 # AAC
           - c2998bd0d90ed5621d8df281e839436e # DD
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: HD Bluray + WEB
      - trash_ids:
           - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4
            score: 0
          - name: SQP-5
          - name: HD Bluray + WEB
          - name: UHD Bluray + WEB
      - trash_ids:
           - 89dac1be53d5268a7e10a19d3c896826 # 2.0 Stereo
        assign_scores_to:
          - name: SQP-1 (1080p)
            score: -175
          - name: Remux-1080p - Anime
            score: 100
      - trash_ids:
           - 5153ec7413d9dae44e24275589b5e944 # BHDStudio
        assign_scores_to:
          - name: SQP-1 (1080p)
            score: 200
          - name: SQP-1 (2160p)
            score: 200
      - trash_ids:
           - 7a0d1ad358fee9f5b074af3ef3f9d9ef # hollowed this is to prefer WEBDL over BHD in sqp-1(1080p) and works in combo with the lower score of BHDStudio
        assign_scores_to:
          - name: SQP-1 (1080p)
            score: 650 
      - trash_ids: 
           - 957d0f44b592285f26449575e8b1167e # Special edition CF score overide, Premade iucludes give this a score but trash said that shouldn't be the case for the streaming sqp's
        assign_scores_to:
          - name: SQP-1 (1080p)
            score: 0
          - name: SQP-1 (2160p)
            score: 0
      - trash_ids:
           - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
           - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
           - f537cf427b64c38c8e36298f657e4828 # Scene
           - f700d29429c023a5734505e77daeaea7 # DV (Disk)
        assign_scores_to:
          - name: SQP-1 (1080p)
          - name: SQP-1 (2160p)
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4
          - name: SQP-5
          - name: Remux-1080p - Anime
          - name: HD Bluray + WEB
          - name: UHD Bluray + WEB
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
           - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
          # Uncomment the next two lines if you have a setup that supports HDR10+
           - b17886cb4158d9fea189859409975758 # HDR10+ Boost
           - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
        assign_scores_to:
          - name: SQP-1 (2160p)
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4
          - name: SQP-5
          - name: UHD Bluray + WEB
      - trash_ids:
          - 2899d84dc9372de3408e6d8cc18e9666 # x264 | score: 0 to enable x264 releases
        assign_scores_to:
          - name: SQP-2
          - name: SQP-3
          - name: SQP-4
          - name: SQP-5
      - trash_ids:
          # Uncomment the next six lines to block all x265 HD releases
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: SQP-5
            score: 0
      - trash_ids:
           - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: SQP-5      
      # Optional SDR Only ever use ONE of the following TWO custom formats:
      - trash_ids:
          - 9c38ebb7384dada637be8899efa68e6f # SDR - block ALL SDR releases
        assign_scores_to:
          - name: SQP-2
          - name: SQP-3
          - name: SQP-5
      - trash_ids:
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
        assign_scores_to:
          - name: SQP-1 (2160p)
          - name: SQP-4
          - name: UHD Bluray + WEB
      - trash_ids:
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 200
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10
      - trash_ids:
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: -1000
# FEEL FREE TO REMOVE/CHANGE THE ABOVE 3 FORMATS I ADDED THEM TO AVOID DOLBY VISION VIDEO ONLY BUT NOT SURE IF IT WAS CORRECT.
```
