### ISSUE TITLE
Error after latest sonarr update: CF field of type False is not supported

### ISSUE THREAD

**Issue by milindpatel63** [recyclarr/recyclarr#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[ERR] HTTP error: Response could not be deserialized to JSON: GET http://REDACTED:8989/api/v3/customformat [ CF field of type False is not supported ]
[ERR] Reason: Unable to determine. Please report this as a bug and attach your `debug.log` and `verbose.log` files.

### Expected Behavior

It should run without any errors

### Steps To Reproduce

1. run recyclarr sync
2. i get this error

### Environment & Versions

```bash
- Operating System: Ubuntu 20.04
- Architecture: x86
- Recyclarr Version: 7.2.2+Branch.master.Sha.08b88fa0b774f609e49a86e70ac0a7b2b14608e4
- Recyclarr Build: Docker
- Sonarr Version: 4.0.9.2332
- Radarr Version: 5.9.1.9070
```

### Recyclarr Log File(s)

[recyclarr_2024-09-04_01-24-33.debug.log](https://github.com/user-attachments/files/16854764/recyclarr_2024-09-04_01-24-33.debug.log)
[recyclarr_2024-09-04_01-24-33.verbose.log](https://github.com/user-attachments/files/16854767/recyclarr_2024-09-04_01-24-33.verbose.log)

### Configuration YAML

```YAML
# Configuration specific to Sonarr
sonarr:
  sonarr1080p:
    base_url: http://127.0.0.1:8989
    api_key: xxx
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: sonarr-quality-definition-anime
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
```
