### ISSUE TITLE
Property 'notifications' not found on type 'Recyclarr.Config.Parsing.RootConfigYaml'.

### ISSUE THREAD

**Issue by WindowsFreak123** [recyclarr/recyclarr#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have added the notification example to my configuration .yml from the wiki (https://recyclarr.dev/wiki/yaml/settings-reference/notifications/#stateless) and edited the Apprise url and Discord webhook url.

`notifications:
  apprise:
    mode: stateless
    base_url: http://192.168.1.15:8000
    urls:
      - https://discord.com/api/webhooks/[redacted]/[redacted]`
When running the sync, it wil throw the following error.

`user@Recyclarr:~$ /usr/local/bin/recyclarr sync -c /home/user/recyclarr.yml
[ERR] recyclarr.yml: Exception at line 354: Property 'notifications' not found on type 'Recyclarr.Config.Parsing.RootConfigYaml'.
[ERR] recyclarr.yml: Due to previous exception, this config will be skipped
user@Recyclarr:~$`

The yml worked in the past and stopped working after adding the lines for the notifications. I have verified my apprise-api server is working, and running the command `curl -X GET http://192.168.1.15:8000/status` from the server Recyclarr is running on returns "OK"

### Expected Behavior

I expected the config to work after adding the new lines.

### Steps To Reproduce

1. Add the notifications lines from the example located at https://recyclarr.dev/wiki/yaml/settings-reference/notifications/
2. Edit the lines so it's supposed to work for you instances
3. Run a sync with the updated config.yml
4. Error

### Environment & Versions

```bash
- Operating System: Debian GNU/Linux 12 (bookworm)
- Architecture: x64
- Recyclarr Version: v7.4.0 (Branch.master.Sha.4f105f859ad8fd371dbe252062252be07bfd1e17)
- Recyclarr Build: linux-x64
- Sonarr Version: 4.0.11.2680 (Sonarr), 4.0.11.2680 (SonarrAnime)
- Radarr Version: 5.15.1.9463 (Radarr), 5.15.1.9463 (RadarrAnime)
```

### Recyclarr Log File(s)

[recyclarr_2024-11-27_12-34-37.debug.log](https://github.com/user-attachments/files/17933952/recyclarr_2024-11-27_12-34-37.debug.log)

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/

# Configuration specific to Sonarr
sonarr:
  Sonarr:
    # Set the URL/API Key to your actual instance
    base_url: http://192.168.1.9:8989
    api_key: [REDACTED]

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    #Use `recyclarr list custom-formats sonarr` for values you can put here.
    # https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/
    replace_existing_custom_formats: true
    custom_formats:
      # Series
      - trash_ids:
          # HQ Source Groups
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
           # Audio Advanced #1
          - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
          - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD ATMOS
          # Audio Advanced #2
          - dbe00161b08a25ac6154c55f95e6318d # DD
          # HDR Formats
          - 6d0d8de7b57e35518ac0308b0ddf404e # DV
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - 1f733af03141f068a540eec352589a89 # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd # DV SDR
          - 3e2c4e748b64a1a1118e0ea3f4cf6875 # HDR
          - bb019e1cd00f304f80971c965de064dc # HDR (undefined)
          - 3497799d29a085e2ac2df9d468413c94 # HDR10
          - 17e889ce13117940092308f48b48b45b # HLG
          # General Streaming Services
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - 77a7b25585c18af08f60b1547bb9b4fb # CC
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
          - d34870697c9db575f17700212167be23 # NF
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
          # Misc
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          # Optional
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
          # Qualities
          - 290078c8b266272a5cc8e251b5e2eb0b # 1080p
          - c99279ee27a154c2f20d1d505cc99e25 # 720p
          # Unwanted
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
    quality_profiles:
      - name: Serie

  SonarrAnime:
    # Set the URL/API Key to your actual instance
    base_url: http://192.168.1.14:8989
    api_key: [REDACTED]

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: anime

    # Use `recyclarr list custom-formats sonarr` for values you can put here.
    # https://trash-guides.info/Sonarr/Sonarr-Release-Profile-RegEx/
    replace_existing_custom_formats: true
    custom_formats:
      - trash_ids:
          # Anime Source Groups
          - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers)
          - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers)
          - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers)
          - 30feba9da3030c5ed1e0f7d610bcadc4 # Anime BD Tier 04 (SeaDex Muxers)
          - 545a76b14ddc349b8b185a6344e28b04 # Anime BD Tier 05 (Remuxes)
          - 25d2afecab632b1582eaf03b63055f72 # Anime BD Tier 06 (FanSubs)
          - 0329044e3d9137b08502a9f84a7e58db # Anime BD Tier 07 (P2P/Scene)
          - c81bbfb47fed3d5a3ad027d077f889de # Anime BD Tier 08 (Mini Encodes)
          - e3515e519f3b1360cbfc17651944354c # Anime LQ Groups
          - b4a1b3d705159cdca36d71e57ca86871 # Anime Raws
          - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01 (Muxers)
          - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02 (Top FanSubs)
          - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03 (Official Subs)
          - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04 (Official Subs)
          - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 05 (FanSubs)
          - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 06 (FanSubs)
          # Audio Advanced #1
          - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
          - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD ATMOS
          # Audio Advanced #2
          - dbe00161b08a25ac6154c55f95e6318d # DD
          # HDR Formats
          - 6d0d8de7b57e35518ac0308b0ddf404e # DV
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - 1f733af03141f068a540eec352589a89 # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd # DV SDR
          - 3e2c4e748b64a1a1118e0ea3f4cf6875 # HDR
          - bb019e1cd00f304f80971c965de064dc # HDR (undefined)
          - 3497799d29a085e2ac2df9d468413c94 # HDR10
          - 17e889ce13117940092308f48b48b45b # HLG
          # Anime Misc
          - d2d7b8a9d39413da5f44054080e028a3 # v0
          - 273bd326df95955e1b6c26527d1df89b # v1
          - 228b8ee9aa0a609463efca874524a6b8 # v2
          - 0e5833d3af2cc5fa96a0c29cd4477feb # v3
          - 4fc15eeb8f2f9a749f918217d4234ad8 # v4
          # General Streaming Services
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - d34870697c9db575f17700212167be23 # NF    
          # Anime Streaming Services
          - a370d974bc7b80374de1d9ba7519760b # ABEMA
          - d54cd2bf1326287275b56bccedb72ee2 # ADN
          - 7dd31f3dee6d2ef8eeaa156e23c3857e # B-Global
          - 4c67ff059210182b59cdd41697b8cb08 # Bilibili
          - 3e0b26604165f463f3e8e192261e7284 # CR
          - 1284d18e693de8efe0fe7d6b3e0b9170 # FUNi
          - 570b03b3145a25011bf073274a407259 # HIDIVE
          - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV
          - e5e6405d439dcd1af90962538acd4fe0 # WKN
          # Anime Optional
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
          - 9c14d194486c4014d422adc64092d794 # Dubs Only
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
          - 07a32f77690263bb9fda1842db7e273f # VOSTFR
          # Optional
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
          # Qualities
          - 290078c8b266272a5cc8e251b5e2eb0b # 1080p
          - c99279ee27a154c2f20d1d505cc99e25 # 720p
          # Unwanted
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
    quality_profiles:
      - name: Anime

# Configuration specific to Radarr.
radarr:
  Radarr:
    # Set the URL/API Key to your actual instance
    base_url: http://192.168.1.9:7878
    api_key: [REDACTED]
    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true
    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          # HQ Release Groups
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
          # Audio Advanced #1
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          # Audio Advanced #2
          - c2998bd0d90ed5621d8df281e839436e # DD
          # HDR Formats
          - 58d6a88f13e2db7f5059c41047876f00 # DV
          - e23edd2482476e595fb990b12e7c609c # DV HDR10
          - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
          - a3e19f8f627608af0211acd02bf89735 # DV SDR
          - e61e28db95d22bedcadf030b8f156d96 # HDR
          - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
          - 9364dd386c9b4a1100dde8264690add7 # HLG
          # General Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
          # Movie Versions
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - 09d9dd29a0fc958f9796e65c2a8864b4 # Open Matte
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # Misc
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          # Optional
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - f537cf427b64c38c8e36298f657e4828 # Scene
          # Qualities
          - 820b09bb9acbfde9c35c71e0e565dad8 # 1080p
          - b2be17d608fc88818940cd1833b0b24c # 720p
          # Unwanted
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - cae4ca30163749b891686f95532519bd # AV1
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 0a3f082873eb454bde444150b70253cc # Extras
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
    quality_profiles:
      - name: HD-1080p

  RadarrAnime:
    # Set the URL/API Key to your actual instance
    base_url: http://192.168.1.14:7878
    api_key: [REDACTED]

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true
    custom_formats:
      # A list of custom formats to sync to Radarr.
      # Use `recyclarr list custom-formats radarr` for values you can put here.
      # https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/
      - trash_ids:
          # Anime
          - fb3ccc5d5cc8f77c9055d4cb4561dded # Anime BD Tier 01 (Top SeaDex Muxers)
          - 66926c8fa9312bc74ab71bf69aae4f4a # Anime BD Tier 02 (SeaDex Muxers)
          - fa857662bad28d5ff21a6e611869a0ff # Anime BD Tier 03 (SeaDex Muxers)
          - f262f1299d99b1a2263375e8fa2ddbb3 # Anime BD Tier 04 (SeaDex Muxers)
          - ca864ed93c7b431150cc6748dc34875d # Anime BD Tier 05 (Remuxes)
          - 9dce189b960fddf47891b7484ee886ca # Anime BD Tier 06 (FanSubs)
          - 1ef101b3a82646b40e0cab7fc92cd896 # Anime BD Tier 07 (P2P/Scene)
          - 6115ccd6640b978234cc47f2c1f2cadc # Anime BD Tier 08 (Mini Encodes)
          - b0fdc5897f68c9a68c70c25169f77447 # Anime LQ Groups
          - 06b6542a47037d1e33b15aa3677c2365 # Anime Raws
          - 8167cffba4febfb9a6988ef24f274e7e # Anime Web Tier 01 (Muxers)
          - 8526c54e36b4962d340fce52ef030e76 # Anime Web Tier 02 (Top FanSubs)
          - de41e72708d2c856fa261094c85e965d # Anime Web Tier 03 (Official Subs)
          - 9edaeee9ea3bcd585da9b7c0ac3fc54f # Anime Web Tier 04 (Official Subs)
          - 22d953bbe897857b517928f3652b8dd3 # Anime Web Tier 05 (FanSubs)
          - a786fbc0eae05afe3bb51aee3c83a9d4 # Anime Web Tier 06 (FanSubs)
          - c259005cbaeb5ab44c06eddb4751e70c # v0
          - 5f400539421b8fcf71d51e6384434573 # v1
          - 3df5e6dfef4b09bb6002f732bed5b774 # v2
          - db92c27ba606996b146b57fbe6d09186 # v3
          - d4e5e842fad129a3c097bdb2d20d31a0 # v4
          # Anime Optional
          - a5d148168c4506b55cf53984107c396e # 10bit
          - 4a3b087eea2ce012fcc1ce319259a3be # Anime Dual Audio
          - b23eae459cc960816f2d6ba84af45055 # Dubs Only
          - 064af5f084a0a24458cc8ecd3220f93f # Uncensored
          - 9172b2f683f6223e3a1846427b417a3d # VOSTFR
          # HQ Release Groups
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
          # Audio Advanced #1
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          # Audio Advanced #2
          - c2998bd0d90ed5621d8df281e839436e # DD
          # HDR Formats
          - 58d6a88f13e2db7f5059c41047876f00 # DV
          - e23edd2482476e595fb990b12e7c609c # DV HDR10
          - 55d53828b9d81cbe20b02efd00aa0efd # DV HLG
          - a3e19f8f627608af0211acd02bf89735 # DV SDR
          - e61e28db95d22bedcadf030b8f156d96 # HDR
          - 2a4d9069cc1fe3242ff9bdaebed239bb # HDR (undefined)
          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
          - 9364dd386c9b4a1100dde8264690add7 # HLG
          # Anime Streaming Services
          - 60f6d50cbd3cfc3e9a8c00e3a30c3114 # VRV          
          # General Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          # Qualities
          - 820b09bb9acbfde9c35c71e0e565dad8 # 1080p
          - b2be17d608fc88818940cd1833b0b24c # 720p
          # Unwanted
          - cae4ca30163749b891686f95532519bd # AV1
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
    quality_profiles:
      - name: HD-1080p

# Configuration regarding notifications
notifications:
  apprise:
    mode: stateless
    base_url: http://192.168.1.15:8000
    urls:
      - https://discord.com/api/webhooks/[REDACTED]/[REDACTED]
```
