### ISSUE TITLE
Improper Error reporting for config validation

### ISSUE THREAD

**Issue by sdooweloc** [recyclarr/recyclarr#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a `recyclarr sync sonarr` with templates and an invalid radarr config section the system errors out reporting that the issue exists with the included file rather than with the base config file.

Error:
```
docker compose run --rm recyclarr sync sonarr
WARN[0000] /mnt/docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[ERR] Include sonarr-v4-quality-profile-web-1080p.yml: Config Validation: 'custom_formats' must not be empty.
[ERR] Include sonarr-v4-quality-profile-web-1080p.yml: Config Validation: 'quality_profiles' must not be empty.
```

Config:
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# An empty starter config to use with Recyclarr. Update the values below as needed for your
# instance. You will be required to update the `api_key` and `base_url` for each instance you want
# to use.
#
# If you'd rather use pre-built configuration instead of building your own from scratch, see these
# pages:
# - Config Templates: https://recyclarr.dev/wiki/guide-configs/
# - CLI Command: https://recyclarr.dev/wiki/cli/config/list/templates/
#
# This file WILL NOT WORK as it currently is. You need to read the documentation and build this
# configuration from scratch. Note that there's no "one size fits all" configuration. Please refer
# to the TRaSH Guides to understand how to build the appropriate configuration based on your
# hardware setup and capabilities.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/
#
# Want a more flexible file layout?
# See: https://recyclarr.dev/wiki/file-structure/

# Configuration specific to Sonarr. For Radarr, the layout is the same.
# See: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  WEB-1080p-v4:
    # Set the URL/API Key to your actual instance
    base_url: REDACTED
    api_key: REDACTED
    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      - template: sonarr-v4-quality-profile-web-1080p
      # - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # assign_scores_to:
          # - name: WEB-1080p
            # score: 0
      # - trash_ids:
          # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p

radarr:
  movies:
    base_url: REDACTED
    api_key: REDACTED

    quality_definition:

    quality_profiles:

    custom_formats:

    media_naming:
```

### Expected Behavior

I would expect the error to point to the recyclarr.yml file as the source of the error/invalid formatting/empty parameters. 

### Steps To Reproduce

Config for replication:
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# An empty starter config to use with Recyclarr. Update the values below as needed for your
# instance. You will be required to update the `api_key` and `base_url` for each instance you want
# to use.
#
# If you'd rather use pre-built configuration instead of building your own from scratch, see these
# pages:
# - Config Templates: https://recyclarr.dev/wiki/guide-configs/
# - CLI Command: https://recyclarr.dev/wiki/cli/config/list/templates/
#
# This file WILL NOT WORK as it currently is. You need to read the documentation and build this
# configuration from scratch. Note that there's no "one size fits all" configuration. Please refer
# to the TRaSH Guides to understand how to build the appropriate configuration based on your
# hardware setup and capabilities.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/
#
# Want a more flexible file layout?
# See: https://recyclarr.dev/wiki/file-structure/

# Configuration specific to Sonarr. For Radarr, the layout is the same.
# See: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  WEB-1080p-v4:
    # Set the URL/API Key to your actual instance
    base_url: REDACTED
    api_key: REDACTED
    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      - template: sonarr-v4-quality-profile-web-1080p
      # - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # assign_scores_to:
          # - name: WEB-1080p
            # score: 0
      # - trash_ids:
          # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p

radarr:
  movies:
    base_url: REDACTED
    api_key: REDACTED

    quality_definition:

    quality_profiles:

    custom_formats:

    media_naming:
```

Run a `recyclarr sync sonarr`
Observe that the error being reported points to the included template rather than the base file.

### Environment & Versions

```bash
- Operating System:Docker on Debian 12
- Architecture: x64
- Recyclarr Version: 7.4.0
- Recyclarr Build: 
- Sonarr Version: 4.0.12.2825
- Radarr Version: 5.17.2.9580
```

### Recyclarr Log File(s)

recyclarr_2025-01-10_10-34-22.debug.log
https://gist.github.com/notifiarr-bot/1bf4728a264abc7389582b95b6da9686

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# An empty starter config to use with Recyclarr. Update the values below as needed for your
# instance. You will be required to update the `api_key` and `base_url` for each instance you want
# to use.
#
# If you'd rather use pre-built configuration instead of building your own from scratch, see these
# pages:
# - Config Templates: https://recyclarr.dev/wiki/guide-configs/
# - CLI Command: https://recyclarr.dev/wiki/cli/config/list/templates/
#
# This file WILL NOT WORK as it currently is. You need to read the documentation and build this
# configuration from scratch. Note that there's no "one size fits all" configuration. Please refer
# to the TRaSH Guides to understand how to build the appropriate configuration based on your
# hardware setup and capabilities.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/
#
# Want a more flexible file layout?
# See: https://recyclarr.dev/wiki/file-structure/

# Configuration specific to Sonarr. For Radarr, the layout is the same.
# See: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  WEB-1080p-v4:
    # Set the URL/API Key to your actual instance
    base_url: REDACTED
    api_key: REDACTED
    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      - template: sonarr-v4-quality-profile-web-1080p
      # - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

# Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # assign_scores_to:
          # - name: WEB-1080p
            # score: 0
      # - trash_ids:
          # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p

radarr:
  movies:
    base_url: REDACTED
    api_key: REDACTED

    quality_definition:

    quality_profiles:

    custom_formats:

    media_naming:
```
