### ISSUE TITLE
process reaping disabled, not pid 1

### ISSUE THREAD

**Issue by Joloxx9** [recyclarr/recyclarr#435]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

As in the title, my logs contains this line, not sure why, running latest truenas scale, my yaml file used to create , same thing was happening on my previous device.

### Expected Behavior

There should be no warning message

### Steps To Reproduce

Run a container 

### Environment & Versions

```bash
- Operating System: Truenas Scale
- Architecture: 
- Recyclarr Version:  latest
- Recyclarr Build: latest
- Sonarr Version:
- Radarr Version:
```

### Recyclarr Log File(s)

[EXT] Starting cron schedule using: @daily
time="2025-03-06T08:06:56Z"level=warning msg="process reaping disabled, not pid 1" 
time="2025-03-06T08:06:56Z" level=info msg="read crontab: /tmp/crontab"

### Configuration YAML

```YAML
recyclarr:

networks:
  recyclarr:
    name: recyclarr
    external: true

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    networks: [recyclarr]
    volumes:
      - /mnt/nvme/appdata/recyclarr:/config
    environment:
      - TZ=Europe/London
```
