### ISSUE TITLE
Deleted custom formats not recreated in newest `edge` version

### ISSUE THREAD

**Issue by jonasgeiler** [recyclarr/recyclarr#442]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

For issue #278 I was trying out the newest `edge` version of Recyclarr to test the new `!file` substitution. Everything seemed to be working at first (it could connect to Radarr/Sonarr without error), but to test if the sync worked correctly I deleted one of my custom formats on Radarr, expecting it to be recreated automatically by Recyclarr when I re-ran the `sync` command.

But for some reason it was not recreated.

I was confused and thought this was a feature, not a bug. Like a feature to prevent accidental overwrites or something.
But then I tried out version `7.4.1` again, and suddenly the custom format was recreated.
Then I also tried changing my naming formats for Radarr, to see if they're re-synced correctly. But they also remained unchanged on `edge`, but re-synced correctly on `7.4.1`.

I should also note that it looks like no cache files are being created when running the `edge` version of Recyclarr. It says it's saving stuff to cache, but the cache files mentioned in the logs aren't created?

It looks like you may have broken something in Recyclarr. Or maybe `edge` is still a **heavy** work in progress within a partial migration of code and you're currently working on it to have the same functionality again - sorry for creating an issue if that is the case.

### Expected Behavior

Recyclarr correctly recreates the deleted custom formats, and correctly replaces the modified file naming formats.

### Steps To Reproduce

1. Start a Docker container with image `recyclarr/recyclarr:edge@sha256:6e2828b5f87e13c42abb6acd1af33e70ccd1b03093aafbc98f8b3412577ec244`.
2. Exec into the Docker container and run the sync using `recyclarr sync`.
3. Delete a Recyclarr-managed custom format in Radarr or Sonarr.
4. Re-run the sync using `recyclarr sync`. The missing custom format will not be recreated.
5. Start a Docker container with image `recyclarr/recyclarr:7.4.1@sha256:759540877f95453eca8a26c1a93593e783a7a824c324fbd57523deffb67f48e1`.
6. Exec into the Docker container and re-run the sync again using `recyclarr sync`. The missing custom format will be recreated.

### Environment & Versions

```bash
- Operating System: Debian 12 Bookworm
- Architecture: x64
- Recyclarr Version: `edge@sha256:6e2828b5f87e13c42abb6acd1af33e70ccd1b03093aafbc98f8b3412577ec244`
- Recyclarr Build: Docker
- Sonarr Version: `4.0.13.2932`
- Radarr Version: `5.19.3.9730`
```

### Recyclarr Log File(s)

Re-sync logs in Recyclarr `7.4.1`, AFTER running the sync for the first time, and then deleting the `3D` custom format:

[recyclarr_2025-03-18_07-00-02.debug.log](https://github.com/user-attachments/files/19307631/recyclarr_2025-03-18_07-00-02.debug.log)

[recyclarr_2025-03-18_07-00-02.verbose.log](https://github.com/user-attachments/files/19307633/recyclarr_2025-03-18_07-00-02.verbose.log)

Re-sync logs in Recyclarr `edge`, AFTER running the sync for the first time, and then deleting the `3D` custom format (aka. the logs where `3D` should have been re-created but wasn't):

[recyclarr_2025-03-18_07-07-28.debug.log](https://github.com/user-attachments/files/19307703/recyclarr_2025-03-18_07-07-28.debug.log)

[recyclarr_2025-03-18_07-07-28.verbose.log](https://github.com/user-attachments/files/19307706/recyclarr_2025-03-18_07-07-28.verbose.log)

### Configuration YAML

Note that I'm not using the new `!file` substitution here because it is unrelated to the problem and allows switching back and forth between `edge` and `7.4.1`.

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
# Based on: https://github.com/recyclarr/config-templates/blob/aee0a4108c5cfc11b57bb91ee6659d5bb7b87e43/radarr/templates/sqp/sqp-1-1080p.yml

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
radarr:
  my_radarr:
    base_url: !env_var RADARR_BASE_URL
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_profiles:
      - name: SQP-1 WEB (1080p)
        # Uncomment the below line if you don't have access to top-tier indexers
        min_format_score: 10

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-web-1080p
      - template: radarr-custom-formats-sqp-1-web-1080p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Movie Versions
      - trash_ids:
          # Uncomment any of the next six lines to prefer these movie versions
          # - 570bc9ebecd92723d2d21500f4be314c # Remaster
          # - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          # - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          # - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          # - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # - 957d0f44b592285f26449575e8b1167e # Special Edition

          # Uncomment the next line if you prefer WEBDL with IMAX Enhanced to BHDStudio
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced

          # Optional - uncomment any of the following if you want them added to your profile
          # - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          # - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          # - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          # - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          # - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          # - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          # - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: SQP-1 WEB (1080p)

      # Ignored
      - trash_ids:
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
        assign_scores_to:
          - name: SQP-1 WEB (1080p)
            score: 0

    # Media Naming: https://recyclarr.dev/wiki/yaml/config-reference/media-naming/
    media_naming:
      folder: plex-tmdb
      movie:
        rename: true
        standard: plex-tmdb
```

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
# Based on: https://github.com/recyclarr/config-templates/blob/98ef6bcc8dddf12ef55ddb9d9bfc070a2c99b998/sonarr/templates/web-1080p-v4.yml

# Instance Definition: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  my_sonarr:
    base_url: !env_var SONARR_BASE_URL
    api_key: !env_var SONARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      # Choose between the standard or alternative quality profile setup (choose one only)
      # - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-quality-profile-web-1080p-alternative
      - template: sonarr-v4-custom-formats-web-1080p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          # - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          # - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          # - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
        # Uncomment the next six lines to allow x265 HD releases with HDR/DV
        # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # assign_scores_to:
        # - name: WEB-1080p
        # score: 0
        # - trash_ids:
        # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p

    # Media Naming: https://recyclarr.dev/wiki/yaml/config-reference/media-naming/
    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default
```
