### ISSUE TITLE
ReleaseTypeSpecification is not a valid specification implementation

### ISSUE THREAD

**Issue by netpanic** [recyclarr/recyclarr#449]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Following error in Recyclarr (not in FAQ)

===========================================
Processing Sonarr Server: [series]
[ERR] HTTP error: Call failed with status code 500 (Internal Server Error): POST http://REDACTED:8988/api/v3/customformat
[ERR] Error message from remote service: ReleaseTypeSpecification is not a valid specification implementation

PS C:\tools\recyclarr-win-x64>

### Expected Behavior

Recyclarr to access Sonarr via API without errors 

### Steps To Reproduce

1. run `sync sonarr` command 
2. Command fails with following error; 

===========================================
Processing Sonarr Server: [series]
[ERR] HTTP error: Call failed with status code 500 (Internal Server Error): POST http://REDACTED:8988/api/v3/customformat
[ERR] Error message from remote service: ReleaseTypeSpecification is not a valid specification implementation

PS C:\tools\recyclarr-win-x64>

Thanks

### Environment & Versions

```bash
- Operating System: Windows 11 Pro
- Architecture: x64
- Recyclarr Version: v7.4.1 (Branch.master.Sha.5bcd1122e967c828fceceea9810ebd1a33ce344a)
- Recyclarr Build: Manual installation (Windows x64)
- Sonarr Version: 

Version
4.0.1.929
Package Version
4.0.1.929-ls224 by linuxserver.io

- Radarr Version:

N/A
```

### Recyclarr Log File(s)

===========================================
Processing Sonarr Server: [series]
[ERR] HTTP error: Call failed with status code 500 (Internal Server Error): POST http://REDACTED:8988/api/v3/customformat
[ERR] Error message from remote service: ReleaseTypeSpecification is not a valid specification implementation

PS C:\tools\recyclarr-win-x64>

### Configuration YAML

```YAML
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# An empty starter config to use with Recyclarr. Update the values below as needed for your
# instance. You will be required to update the `api_key` and `base_url` for each instance you want
# to use.
#
# If you'd rather use pre-built configuration instead of building your own from scratch, see these
# pages:
# - Config Templates: https://recyclarr.dev/wiki/guide-configs/
# - CLI Command: https://recyclarr.dev/wiki/cli/config/list/templates/
#
# This file WILL NOT WORK as it currently is. You need to read the documentation and build this
# configuration from scratch. Note that there's no "one size fits all" configuration. Please refer
# to the TRaSH Guides to understand how to build the appropriate configuration based on your
# hardware setup and capabilities.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/yaml/config-reference/
#
# Want a more flexible file layout?
# See: https://recyclarr.dev/wiki/file-structure/

# Configuration specific to Sonarr. For Radarr, the layout is the same.
# See: https://recyclarr.dev/wiki/yaml/config-reference/basic/
sonarr:
  sonarr_4k:
    # Set the URL/API Key to your actual instance
    base_url: http://REDACTED
    api_key: REDACTED
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # See: https://recyclarr.dev/wiki/yaml/config-reference/quality-definition/
    quality_definition:
      type: series

    # See: https://recyclarr.dev/wiki/yaml/config-reference/quality-profiles/
    quality_profiles:
    - name: Ultra-HD
      qualities:
        - name: Bluray-2160p Remux
        - name: Bluray-2160p
        - name: WEB-2160p
        - name: HDTV-2160p
        - name: Bluray-1080p Remux
        - name: Blurray-1080p
        - name: WEB 1080p
        - name: Bluray-720p
        - name: WEB 720p
        - name: HDTV-1080p
        - name: HDTV-720p
        
      upgrade: 
        allowed: true
        until_quality: Bluray-2160p
        until_score: 10000

    # See: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    custom_formats:
      # [No Category]
      - trash_ids: 
          - 6f808933a71bd9666531610cb8c059cc # BR-DISK (BTN)
          - 5d9fd1b1e06cd8a475462f40214b7df6 # FLUX
          - 4a20cfb76b5f92a8ca22b894b32e71be # Multi-Episode
          - 133589380b89f8f8394320901529bac1 # Not German or English
          - e0c1a67f23908a55b6ae9834e8ed6727 # Single Episode
        assign_scores_to:
          - name: Ultra-HD
        
        # Audio Advanced #1
      - trash_ids: 
          - b6fbafa7942952a13e17e2b1152b539a # ATMOS (undefined)
          - 63487786a8b01b7f20dd2bc90dd4a477 # DD+
          - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS
          - 5964f2a8b3be407d083498e4459d05d0 # DTS
          - 9d00418ba386a083fbf4d58235fc37ef # DTS X
          - c1a25cd67b5d2e08287c957b1eb903ec # DTS-ES
          - c429417a57ea8c41d57e6990a8b0033f # DTS-HD MA
          - 1808e4b9cee74e064dfae3f1db99dbfe # TrueHD
          - 0d7824bb924701997f874e7ff7d4844a # TrueHD ATMOS
        assign_scores_to:
          - name: Ultra-HD
          
        # Audio Advanced #2
      - trash_ids: 
          - a50b8a0c62274a7c38b09a9619ba9d86 # AAC
          - dbe00161b08a25ac6154c55f95e6318d # DD
          - cfa5fbd8f02a86fc55d8d223d06a5e1f # DTS-HD HRA
          - 851bd64e04c9374c51102be3dd9ae4cc # FLAC
          - 3e8b714263b26f486972ee1e0fe7606c # MP3
          - 28f6ef16d61e2d1adfce3156ed8257e3 # Opus
          - 30f70576671ca933adbdcfc736a69718 # PCM
        assign_scores_to:
          - name: Ultra-HD
        
        # Audio Channels
      - trash_ids: 
          - bd6dd5e043aa27ff4696a08d011c7d96 # 1.0 Mono
          - 834e534f103938853ffced4203b53e72 # 2.0 Stereo
          - 42cba7e38c7947a6d1d0a62580ee6d62 # 3.0 Sound
          - 1895195e84767de180653914ce207245 # 4.0 Sound
          - 3fbafa924f361e66fbc6187af82dfa85 # 5.1 Surround
          - 9fb6d778592c293467437593ef394bf1 # 6.1 Surround
          - 204c8c3e7315bb0ea81332774fa888d6 # 7.1 Surround
        assign_scores_to:
          - name: Ultra-HD
          
        # General Streaming Services
      - trash_ids:         
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - f67c9ca88f463a48346062e8ad07713f # ATVP
          - 77a7b25585c18af08f60b1547bb9b4fb # CC
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
          - d34870697c9db575f17700212167be23 # NF
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
          - 9623c5c9cac8e939c1b9aedd32f640bf # SYFY
        assign_scores_to:
          - name: Ultra-HD
        
        # HDR Formats
      - trash_ids:         
          - 6d0d8de7b57e35518ac0308b0ddf404e # DV
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - 2b239ed870daba8126a53bd5dc8dc1c8 # DV HDR10+
          - 1f733af03141f068a540eec352589a89 # DV HLG
          - 27954b0a80aab882522a88a4d9eae1cd # DV SDR
          - 3e2c4e748b64a1a1118e0ea3f4cf6875 # HDR
          - bb019e1cd00f304f80971c965de064dc # HDR (undefined)
          - 3497799d29a085e2ac2df9d468413c94 # HDR10
          - a3d82cbef5039f8d295478d28a887159 # HDR10+
          - 17e889ce13117940092308f48b48b45b # HLG
          - 2a7e3be05d3861d6df7171ec74cad727 # PQ
        assign_scores_to:
          - name: Ultra-HD
        
        # HQ Source Groups
      - trash_ids:         
          - d6819cba26b1a6508138d25fb5e32293 # HD Bluray Tier 01
          - c2216b7b8aa545dc1ce8388c618f8d57 # HD Bluray Tier 02
          - 9965a052eb87b0d10313b1cea89eb451 # Remux Tier 01
          - 8a1d0c3d7497e741736761a1da866a2e # Remux Tier 02
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
        assign_scores_to:
          - name: Ultra-HD
        
        # Miscellaneous
      - trash_ids:         
          - 290078c8b266272a5cc8e251b5e2eb0b # 1080p
          - 1bef6c151fa35093015b0bfef18279e5 # 2160p
          - c99279ee27a154c2f20d1d505cc99e25 # 720p
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - ef4963043b0987f8485bc9106f16db38 # DV (Disk)
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
          - d7c747094a7c65f4c2de083c24899e8b # FreeLeech
          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          - 1bd69272e23c5e6c5b1d6c8a36fce95e # HFR
          - 5ab46ff851b76c337e13e81a4353875f # INTERNAL
          - 4aee45b0868229c4fbd8bad3e315f1d0 # MPEG2
          - 7ba05c6e0e14e793538174c679126996 # MULTi
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
          - 7470a681e6205243983c4410ee4c920f # VC-1
          - 90501962793d580d011511155c97e4e5 # VP9
          - cddfb4e32db826151d97352b8e37c648 # x264
          - c9eafd50846d299b862ca9bb6ea91950 # x265
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
          - 041d90b435ebd773271cea047a457a6a # x266
        assign_scores_to:
          - name: Ultra-HD
        
        # Series Versions
      - trash_ids: 
          - 3a4127d8aa781b44120d907f2cd62627 # Hybrid
          - b735f09d3c025cbb7d75a5d38325b73b # Remaster
        assign_scores_to:
          - name: Ultra-HD
        
        # UK Streaming Services
      - trash_ids: 
          - bbcaf03147de0f73be2be4a9078dfa03 # 4OD
          - fcc09418f67ccaddcf3b641a22c5cfd7 # ALL4
          - dc503e2425126fa1d0a9ad6168c83b3f # IP
          - fa5a16b951004c23e980d2913694a137 # ITVX
          - 9f72dc1059a6b277c21cee6a1f15f13f # MY5
          - b66a699fba6f9df91becab798d7502e5 # NOW
        assign_scores_to:
          - name: Ultra-HD
          
        # Unwanted
      - trash_ids: 
          - 15a05bc7c1a36e2b57fd628f8977e2fc # AV1
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title)
          - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: Ultra-HD
        
    # See: https://recyclarr.dev/wiki/yaml/config-reference/media-naming/
    media_naming:



radarr:
  radarr_4k:
    # Set the URL/API Key to your actual instance
    base_url: http://REDACTED
    api_key: REDACTED
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # See: https://recyclarr.dev/wiki/yaml/config-reference/quality-definition/
    quality_definition:
      type: movie

    # See: https://recyclarr.dev/wiki/yaml/config-reference/quality-profiles/
    quality_profiles:
```

### Sonarr / Radarr Logs

SONARR LOGS 
(may be unrelated as Basic Authentication is disabled for local addresses and shouldn't be needed for API access?)

2025-03-20 11:59:36.7|Info|Bootstrap|Starting Sonarr - /app/sonarr/bin/Sonarr - Version 4.0.1.929
2025-03-20 11:59:37.0|Info|AppFolderInfo|Data directory is being overridden to [/config]
2025-03-20 11:59:37.0|Info|AppFolderInfo|Data directory is being overridden to [/config]
2025-03-20 11:59:37.5|Info|Sonarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.

Thanks
