### ISSUE TITLE
System.AccessViolationException on macOS M1 during sync (v7.4.1)

### ISSUE THREAD

**Issue by nephilimreborn** [recyclarr/recyclarr#454]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Recyclarr consistently crashes on my M1 Mac Mini (macOS) with a System.AccessViolationException when running recyclarr sync --preview.

I followed the official manual installation guide [https://recyclarr.dev/wiki/installation/manual-install/] using:
	•	Recyclarr version: v7.4.1
	•	macOS: Apple M1 Mac mini
	•	Git version: 2.49.0
	•	Installed to: /usr/local/bin/recyclarr
	•	Config file: ~/Library/Application Support/recyclarr/recyclarr.yml (generated with recyclarr config create)

I’ve confirmed:
	•	The file is executable via chmod u+rx
	•	Git works (I can clone TRaSH-Guides manually without issue)
	•	The config file is valid YAML
	•	Running recyclarr config create works fine
	•	Only recyclarr sync crashes with memory-related error

I am not using Docker or any sandboxed environment.

### Expected Behavior

Expected Recyclarr to run successfully using the `sync --preview` command and apply TRaSH Guide configurations to Sonarr and Radarr. No memory-related exceptions or crashes should occur.

### Steps To Reproduce

recyclarr config create
open ~/Library/Application\ Support/recyclarr/recyclarr.yml
# edited config with valid base_url + api_key
recyclarr sync --preview

Error Output (Partial):

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Net.Sockets.Socket.ReceiveAsync...

### Environment & Versions

```bash
- Operating System: macOS 15.3.2
- Architecture: arm64 (Apple Silicon - M1)
- Recyclarr Version: v7.4.1
- Recyclarr Build: osx-arm64
- Sonarr Version: 3.0.10.1567
- Radarr Version: 4.3.2.6857
```

### Recyclarr Log File(s)

[recyclarr_2025-03-30_20-13-25.debug.log](https://github.com/user-attachments/files/19529378/recyclarr_2025-03-30_20-13-25.debug.log)
[recyclarr_2025-03-30_20-13-25.verbose.log](https://github.com/user-attachments/files/19529377/recyclarr_2025-03-30_20-13-25.verbose.log)
[recyclarr_2025-03-30_20-17-12.debug.log](https://github.com/user-attachments/files/19529379/recyclarr_2025-03-30_20-17-12.debug.log)
[recyclarr_2025-03-30_20-17-12.verbose.log](https://github.com/user-attachments/files/19529380/recyclarr_2025-03-30_20-17-12.verbose.log)
[recyclarr_2025-03-30_20-32-37.debug.log](https://github.com/user-attachments/files/19529381/recyclarr_2025-03-30_20-32-37.debug.log)
[recyclarr_2025-03-30_20-32-37.verbose.log](https://github.com/user-attachments/files/19529376/recyclarr_2025-03-30_20-32-37.verbose.log)

### Configuration YAML

```YAML
radarr:
  base_url: http://localhost:7878
  api_key: REDACTED
  quality_profiles:
    - name: WEB 1080p
      upgrade:
        allowed: true
        until_quality: WEB 1080p
        until_score: 10000
      reset_unmatched_scores:
        delete_old_custom_formats: true
        score_set: true
  custom_formats:
    - name: x264
      score: 1000
      quality_profiles:
        - name: WEB 1080p
    - name: WEB-DL
      score: 500
      quality_profiles:
        - name: WEB 1080p

sonarr:
  base_url: http://localhost:8989
  api_key: REDACTED
  quality_profiles:
    - name: WEB 1080p
      upgrade:
        allowed: true
        until_quality: WEB 1080p
        until_score: 10000
      reset_unmatched_scores:
        delete_old_custom_formats: true
        score_set: true
  custom_formats:
    - name: x264
      score: 1000
      quality_profiles:
        - name: WEB 1080p
    - name: WEB-DL
      score: 500
      quality_profiles:
        - name: WEB 1080p
```
