### ISSUE TITLE
Unable to find config template 'radarr-quality-definition-anime'

### ISSUE THREAD

**Issue by darkylein** [recyclarr/recyclarr#484]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Recyclarr is unable to find the config template [radarr-quality-definition-anime](https://github.com/recyclarr/config-templates/blob/9eb539ba72fafd98ee65c737a9ba2c26ce75a29a/radarr/includes/quality-definitions/radarr-quality-definition-anime.yml).

It exits with these lines:

```text
[ERR] Exiting due to fatal error: For service type 'Radarr', unable to find config template with name 'radarr-quality-definition-anime'
ERROR: 1
```

This happens on the docker image latest and edge tag.

Adding the quality definition manually didn't work either.

### Expected Behavior

The quality definition to work.

### Steps To Reproduce

Run `docker-compose run recyclarr sync`.

### Environment & Versions

```bash
- Operating System: Debian 12
- Architecture: x86-64
- Recyclarr Version: v7.5.0-dev.61 / Also happens on v7.4.1
- Recyclarr Build: Docker
- Radarr Version: 5.25.0.10024
```

### Recyclarr Log File(s)

[recyclarr_2025-06-03_22-38-15.debug.log](https://gist.github.com/darkylein/cd61135a17943c76754597e677292cc8)

### Configuration YAML

```YAML
radarr:
  radarr_anime:
    base_url: !secret radarr_anime_base_url
    api_key: !secret radarr_anime_api_key
    include:
      - template: radarr-quality-definition-anime
```
