### ISSUE TITLE
Allow Custom Quality Sizes like Configarr

### ISSUE THREAD

**Issue by UnluckyForSome** [recyclarr/recyclarr#487]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

Configarr has recently added ability for custom quality sizes:

https://github.com/raydak-labs/configarr/commit/f41891bd87b877cc3c292c737d0dca8e060932d8diff-491581067f451cc1440f589d94794d02ad648725a63f17a9fc1a9afb63419dbf

Can Recyclarr do the same? This would allow eg:
```
     quality_definition:
       qualities:
         - quality: HDTV-720p
           min: 10
           preferred: 995
           max: 1000
         - quality: HDTV-1080p
           min: 15
           preferred: 995
           max: 1000
         - quality: WEBRip-720p
           min: 10
           preferred: 995
           max: 1000
         - quality: WEBDL-720p
           min: 10
           preferred: 995
           max: 1000
         - quality: Bluray-720p
           min: 17.1
           preferred: 995
           max: 1000
```
