### ISSUE TITLE
strict negative scores is not applied

### ISSUE THREAD

**Issue by JonzaUK** [recyclarr/recyclarr#66]
doing some testing with v2 everything seems to work as intended except for strict negative scores are not applied when set to true

my config is below... everything syncs fine but with negative scores as normal (i.e -10) instead of must not contain.

see config below:

```
sonarr:
  - base_url: http://IPHERE:PORT
    api_key: APIKEYHERE

    # Quality Definition Settings
    quality_definition: series

    # Release Profile Settings
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: true
      - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
        filter:
          exclude:
            - bc7a6383cbe88c3ee2d6396e1aacc0b3 # Ignore prefer HDR
            - fa47da3377076d82d07c4e95b3f13d07 # Ignore prefer Dolby Vision
```

results below in my sonarr test instance:
[https://i.imgur.com/eEnD8Fg.png](https://i.imgur.com/eEnD8Fg.png)
