### ISSUE TITLE
Add optionals trash_ids to default recyclarr.yml template

### ISSUE THREAD

**Issue by rshxyz** [recyclarr/recyclarr#68]
Change the [config-template.yml](https://github.com/recyclarr/recyclarr/blob/master/src/Recyclarr/config-template.yml
) to include optional trash_ids from https://github.com/TRaSH-/Guides/blob/master/docs/json/sonarr/optionals.json

potential problems
- ids change in the future 
- adding new ids to maintain template 

I modified the default template to include optionals 
```
# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/rcdailey/recyclarr/wiki/Configuration-Reference

# Configuration specific to Sonarr
sonarr:
    # Set the URL/API Key to your actual instance
  - base_url: http://localhost:8989
    api_key: f7e74ba6c80046e39e076a27af5a8444

    # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
    quality_definition: hybrid

    # Release profiles from the guide to sync to Sonarr.
    # You can optionally add tags and make negative scores strictly ignored
    release_profiles:
      # Series
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper

      # - trash_ids: [76e060895c5b8a765c310933da0a5357] # Optionals
      #   filter:
      #     include:
      #     - cec8880b847dd5d31d29167ee0112b57 # Golden rule
      #     - 436f5a7d08fbf02ba25cb5e5dfe98e55 # Ignore Dolby Vision without HDR10 fallback.
      #     - f3f0f3691c6a1988d4a02963e69d11f2 # Ignore The Group -SCENE
      #     - 5bc23c3a055a1a5d8bbe4fb49d80e0cb # Ignore so called scene releases
      #     - ea83f4740cec4df8112f3d6dd7c82751 # Prefer Season Packs
      #     - bc7a6383cbe88c3ee2d6396e1aacc0b3 # Prefer HDR
      #     - fa47da3377076d82d07c4e95b3f13d07 # Prefer Dolby Vision
      #     - 6f2aefa61342a63387f2a90489e90790 # Dislike retags: rartv, rarbg, eztv, TG
      #     - 19cd5ecc0a24bf493a75e80a51974cdd # Dislike retagged groups
      #     - 6a7b462c6caee4a991a9d8aa38ce2405 # Dislike release ending: en
      #     - 236a3626a07cacf5692c73cc947bc280 # Dislike release containing: 1-

      # Anime (Uncomment below if you want it)
#      - trash_ids:
#          - d428eda85af1df8904b4bbe4fc2f537c # Anime - First release profile
#          - 6cd9e10bb5bb4c63d2d7cd3279924c7b # Anime - Second release profile

# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  - base_url: http://localhost:7878
    api_key: bf99da49d0b0488ea34e4464aa63a0e5

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: false

    custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
      # Do NOT use the heading names here, those do not work! These are case-insensitive.
      - names:
          - BR-DISK
          - EVO (no WEB-DL)
          - LQ
          - x265 (720/1080p)
          - 3D

        # Uncomment the below properties to specify one or more quality profiles that should be
        # updated with scores from the guide for each custom format. Without this, custom formats
        # are synced to Radarr but no scores are set in any quality profiles.

#        quality_profiles:
#          - name: Quality Profile 1
#          - name: Quality Profile 2
#            #score: -9999 # Optional score to assign to all CFs. Overrides scores in the guide.
#            #reset_unmatched_scores: true # Optionally set other scores to 0 if they are not listed in 'names' above.
```
