### ISSUE TITLE
Help with new command

### ISSUE THREAD

**Issue by ahatdude** [recyclarr/recyclarr#73]
Hello,
A while ago I had an issue with with a new version of trash-updater (it was still the name at the time) and someone was kind enough to help me adapt my script on unraid to automatically do everything. I've tried updating it according to the new repo, but I've been unsuccessful. 
This was my previous script:

```
#!/bin/bash
cd /mnt/user/data/scripts/trash-updater

echo Updating the latest version
wget -O trash.zip https://github.com/rcdailey/trash-updater/releases/latest/download/trash-linux-x64.zip \
    && unzip -o trash.zip && rm trash.zip && chmod +x trash

echo "Update Sonarr/Radarr Quality definition and release profiles..."
/mnt/user/data/scripts/trash-updater/trash sonarr && /mnt/user/data/scripts/trash-updater/trash radarr
echo Updates completed...
```

This is what I tried:

```
#!/bin/bash
cd /mnt/user/data/scripts/recyclarr

echo Updating the latest version
wget -O recyclarr.zip https://github.com/recyclarr/recyclarr/releases/download/v2.0.2/recyclarr-linux-x64.zip \
    && unzip -o recyclarr.zip && rm recyclarr.zip && chmod +x recyclarr

echo "Update Sonarr/Radarr Quality definition and release profiles..."
/mnt/user/data/scripts/recyclarr/recyclarr sonarr && /mnt/user/data/scripts/recyclarr/recyclarr radarr
echo Updates completed...
```

I transfered the old yml file and called it "recyclarr.yml" into the newly created "recyclarr" folder.
Here is what my recyclarr.yml looks like:

```
# A starter config to use with Trash Updater. Most values are set to "reasonable defaults".
# Update the values below as needed for your instance. You will be required to update the
# API Key and URL for each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/rcdailey/trash-updater/wiki/Configuration-Reference

# Configuration specific to Sonarr
sonarr:
    # Set the URL/API Key to your actual instance
  - base_url: http://192.168.1.118:8989
    api_key: API

    # Quality definitions from the guide to sync to Sonarr. Choice: anime, series, hybrid
    quality_definition: hybrid

    # Release profiles from the guide to sync to Sonarr. Types: anime, series
    # You can optionally add tags and make negative scores strictly ignored
    release_profiles:
      - type: series
        strict_negative_scores: false
        filter:
          include_optional: true
        tags:
          - animated-tv
          - documentary-tv
          - educational-tv
          - reality-tv
          - tv
    #release_profiles:
      - type: anime
        strict_negative_scores: true
        tags:
          - anime-tv

# Configuration specific to Radarr.
radarr:
  # Set the URL/API Key to your actual instance
  - base_url: http://192.168.1.118:7878
    api_key: API

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie
      preferred_ratio: 0.5

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    custom_formats:
      # A list of custom formats to sync to Radarr. Must match the "name" in the importable JSON.
      # Do NOT use the heading names here, those do not work! These are case-insensitive.
      - trash_ids:
          ##################################
          #         Audio Advanced         #
          ##################################
          - 496f355514737f7d83bf7aa4d24f8169 #TrueHD ATMOS
          - 2f22d89048b01681dde8afe203bf2e95 #DTS X
          - 417804f7f2c4308c1f4c5d380d4c4475 #ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e #DD+ ATMOS
          - 3cafb66171b47f226146a0770576870f #TrueHD
          - dcf3ec6938fa32445f590a4da84256cd #DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b #FLAC
          - e7c2fcae07cbada050a0af3357491d7b #PCM
          - 8e109e50e0a0b83a5098b056e13bf6db #DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 #Dolby Digital Plus or DD+
          - f9f847ac70a0af62ea4a08280b859636 #DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 #DTS or Basic DTS
          - 240770601cc226190c367ef59aba7463 #AAC
          - c2998bd0d90ed5621d8df281e839436e #Dolby Digital or DD
        quality_profiles:
          - name: Any
          - name: Anime
      - trash_ids:
          - 6ba9033150e7896bdc9ec4b44f2b230f #MP3
          - a061e2e700f81932daf888599f8a8273 #Opus
        quality_profiles:
          - name: Any
            score: 0
          - name: Anime
            score: 0
      - trash_ids:
          ##################################
          #         Audio Channels         #
          ##################################
          - b124be9b146540f8e62f98fe32e49a2a #1.0 Mono
          - 89dac1be53d5268a7e10a19d3c896826 #2.0 Stereo
          - 205125755c411c3b8622ca3175d27b37 #3.0 Sound
          - 373b58bd188fc00c817bd8c7470ea285 #4.0 Sound
          - 77ff61788dfe1097194fd8743d7b4524 #5.1 Surround
          - 6fd7b090c3f7317502ab3b63cc7f51e3 #6.1 Surround
          - e77382bcfeba57cb83744c9c5449b401 #7.1 Surround
          - f2aacebe2c932337fe352fa6e42c1611 #9.1 Surround
        quality_profiles:
          - name: Any
            score: 0
          - name: Anime
            score: 0
      - trash_ids:
          ##################################
          #          HDR metadata          #
          ##################################
          - e23edd2482476e595fb990b12e7c609c #DV HDR10
          - 58d6a88f13e2db7f5059c41047876f00 #DV
          - 55d53828b9d81cbe20b02efd00aa0efd #DV HLG
          - a3e19f8f627608af0211acd02bf89735 #DV SDR
          - b974a6cd08c1066250f1f177d7aa1225 #HDR10+
          - dfb86d5941bc9075d6af23b09c2aeecd #HDR10
          - e61e28db95d22bedcadf030b8f156d96 #HDR
          - 2a4d9069cc1fe3242ff9bdaebed239bb #HDR (undefined)
          - 08d6d8834ad9ec87b1dc7ec8148e7a1f #PQ
          - 9364dd386c9b4a1100dde8264690add7 #HLG
        quality_profiles:
          - name: Any
          - name: Anime
      - trash_ids:
          ##################################
          #         Movie Versions         #
          ##################################
          - 0f12c086e289cf966fa5948eac571f44 #Hybrid
          - 570bc9ebecd92723d2d21500f4be314c #Remaster
          - eca37840c13c6ef2dd0262b141a5482f #4K Remaster
          - e0c07d59beb37348e975a930d5e50319 #Criterion Collection
          - 957d0f44b592285f26449575e8b1167e #Special Edition
          - eecf3a857724171f968a66cb5719e152 #IMAX
        quality_profiles:
          - name: Any
          - name: Anime
      - trash_ids:
          - e9001909a4c88013a359d0b9920d7bea #Theatrical Cut
        quality_profiles:
          - name: Any
            score: 0
          - name: Anime
            score: 0
      - trash_ids:
          ##################################
          #         Misc (-10000)          #
          ##################################
          - ed38b889b31be83fda192888e2286d83 #BR-DISK
          - 90cedc1fea7ea5d11298bebd3d1d3223 #EVO (no WEBDL)
          - 90a6f9a284dff5103f6346090e6280c8 #LQ
          - dc98083864ea246d05a42df0d05f81cc #x265 (720/1080p)
          - b8cd450cbfa689c0259a01d9e29ba3d6 #3D
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 #No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 #Obfuscated
          - 923b6abef9b17f937fab56cfcf89e1f1 #DoVi (WEBDL)
        quality_profiles:
          - name: Any
          - name: Anime
      - trash_ids:
          ##################################
          #              Misc              #
          ##################################
          - e7718d7a3ce595f289bfee26adc178f5 #Repack Proper
          - 0d91270a7255a1e388fa85e959f359d8 #FreeLeech
      - trash_ids:    
          - ff86c4326018682f817830ced463332b #MPEG2
        quality_profiles:
          - name: Any
            score: 0
          - name: Anime
            score: 0
      - trash_ids:
          - 1c7d7b04b15cc53ea61204bebbcc1ee2 #HQ
          - 403f3f6266b90439cacc1e07cae4dc2d #HQ-Remux          
          - 26fa26253af4001701fedb56cec376dc #HQ-WEBDL
        quality_profiles:
          - name: Any
      - trash_ids:
          - 2899d84dc9372de3408e6d8cc18e9666 #x264
          - 9170d55c319f4fe40da8711ba9d8050d #x265
        quality_profiles:
          - name: Any
            score: 0
          - name: Anime
            score: 0
      - trash_ids:
          - 4b900e171accbfb172729b63323ea8ca #Multi
        quality_profiles:
          - name: Any
            score: 0
          - name: Anime
            score: 0
```

In all honesty, I'm eagerly waiting for the docker to be able to simply plug it into unRAID and make my life easier, but until then I'd love to have this running.

Thank you for your time!
