### ISSUE TITLE
Ability to import *arr configs from git or a file

### ISSUE THREAD

**Issue by Kha-kis** [recyclarr/recyclarr#93]
It would be super awesome to be able import each of the *.arr types using a file in git or specify a file

for example:

```
sonarr:
  - base_url: http://localhost:8989
    api_key: f7e74ba6c80046e39e076a27af5a8444
  - git: https://github.com/recyclarr/recyclarr/blob/master/wiki/pathtoconfig
```
 OR
```
sonarr:
  - base_url: http://localhost:8989
    api_key: f7e74ba6c80046e39e076a27af5a8444
  -  file: /path/to/my/sonarr/config
```

This would allow for me to manage multiple instances either from git or from configuration files specific to each *arr type and allow for profile/config sharing across the community.
