### ISSUE TITLE
Add name property for sonarr/radarr instances

### ISSUE THREAD

**Issue by saltydk** [recyclarr/recyclarr#95]
Something like: 
```yaml
sonarr:
  - base_url: http://sonarr:8989
    name: sonarr
    api_key: f7e74ba6c80046e39e076a27af5a8444
    quality_definition: hybrid
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
        tags: [tv]

  - base_url: http://sonarr4k:8989
    name: sonarr4k
    api_key: f7e74ba6c80046e39e076a27af5a8444
    quality_definition: hybrid
    release_profiles:
      - trash_ids:
          - EBC725268D687D588A20CBC5F97E538B # Low Quality Groups
          - 1B018E0C53EC825085DD911102E2CA36 # Release Sources (Streaming Service)
          - 71899E6C303A07AF0E4746EFF9873532 # P2P Groups + Repack/Proper
        strict_negative_scores: false
        tags: [tv]

radarr:
  - base_url: http://radarr:7878
    name: radarr
    api_key: bf99da49d0b0488ea34e4464aa63a0e5
    quality_definition:
      type: movie
      preferred_ratio: 0.5

  - base_url: http://radarr4k:7878
    name: radarr4k
    api_key: bf99da49d0b0488ea34e4464aa63a0e5
    quality_definition:
      type: movie
      preferred_ratio: 0.5
```
Which would allow more sane logging for multi instance users. Idea being that the logging would show something like this:
```
[INF] Processing server radarr at http://hostname:7878
[INF] Processing Quality Definition: Movie
[INF] Number of updated qualities: 14
```
or some other way of making it clear which block of text belongs to what instance.
