### ISSUE TITLE
[Docker] Failure processing application bundle. Failed to create directory [/tmp/.net/recyclarr/] for extracting bundled files.

### ISSUE THREAD

**Issue by azumukupoe** [recyclarr/recyclarr#99]
```
recyclarr | Failure processing application bundle.
recyclarr | Failed to create directory [/tmp/.net/recyclarr/] for extracting bundled files.
```

docker-compose.yml
```
version: '3'
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    init: true
    volumes:
      - .\config:/config
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped

```

Docker for Windows v4.10.1
